### ISSUE TITLE
Add pensioners for eligibility check function testing

### ISSUE THREAD

**Issue by MaxBlesch** [iza-institute-of-labor-economics/gettsim#10]
- [ ] Pensioners for the eligibility check

**Comment by hmgaudecker** [comment]
Please change the title to "Add tests for pension eligiblity check" or the like - Rather more issues than having some that never get closed :-)

**Comment by hmgaudecker** [comment]
Still relevant?

**Comment by MaxBlesch** [comment]
No. There is now a test case in `test_zu_versteuerndes_eink` with a person over 64.
