### ISSUE TITLE
Automate documenting input and output tables

### ISSUE THREAD

**Issue by MaxBlesch** [iza-institute-of-labor-economics/gettsim#106]
### Current and desired situation

We wrote a first draft on the required inputs and desired outputs by hand in [`getting-started.rst`](https://github.com/iza-institute-of-labor-economics/gettsim/blob/master/docs/getting-started.rst).
This came with #93 in place.

### Proposed implementation

We want to have a yaml file that is converted by sphinx to the desired part in the documentation. See https://github.com/iza-institute-of-labor-economics/gettsim/issues/91#issuecomment-554300133 for more details.

**Comment by hmgaudecker** [comment]
Still relevant? Can we automate this based on the DAG? @MaxBlesch @tobiasraabe ?

**Comment by MaxBlesch** [comment]
I suggest we do two things. I will write an updated table with explanations for each variable and we already agreed to separate the function for setting and executing the DAG. This will make it possible to return the required inputs for each variable.

**Comment by hmgaudecker** [comment]
Yeah, would be good to closely coordinate with @tobiasraabe; if we can link parameters and graph, that would be ideal. If possible, we should avoid extra explanations.

**Comment by MaxBlesch** [comment]
But I think, we should still provide explanations of the format and meaning of our basic variables?!

**Comment by hmgaudecker** [comment]
Seems outdated.
