### ISSUE TITLE
Child income treatment at ALG II

### ISSUE THREAD

**Issue by mjbloemer** [iza-institute-of-labor-economics/gettsim#110]
The current modelling of `einkommensanrechnungsfrei(household, tb)` replaces the `ekanrefrei` for children as follows:

````python
    # Children income is fully deducted, except for the first 100 €.
    household.loc[(household["child"]), "ekanrefrei"] = np.maximum(
        0, household["m_wage"] - 100
    )
````

Two issues here:

1. Say the Bedarfsgemeinschaft has a child with `m_wage=80` (`m_wage=0` for other household members), then the `ekanrefrei` would be 0. If there was a 100 Euro allowance and nothing more I think it should be 80. With `m_wage=120` for the child it should be 100. I think in the test data there is a household with a child `m_wage=200` which leads to the correct 100 euro anrechnungsfrei by accident so pytest passes.
2. What is the exact source for this rule? It should be added as a comment to the code and maybe the number 100 should be added as an additional parameter. Or is it just the "Grundfreibetrag" of 100 Euro, currently `a2grf` defined in § 11b (2) 1? If it is the identical parameter, why do the second and third intervals not apply for children too?

**Comment by hmgaudecker** [comment]
I cannot provide any details, but I have a strong opinion that no "100" should appear in the code. It should be defined among the `arbeitsl_geld_2` parameters.

**Comment by mjbloemer** [comment]
Maybe [§ 1 (1) 9. Alg II-V](https://www.buzer.de/gesetz/8014/a153226.htm)?

**Comment by mjbloemer** [comment]
https://www.hartziv.org/hartz-iv-rechner.html treats child income with the normal withdrawal schedule (0-80-90-100 percent). E.g. 200 Euro gross child income will lead to 80 Euro Anrechnung. Also no apparent difference wrt age of the child.

**Comment by hmgaudecker** [comment]
I do not see kids being treated in any other way than other people, either. Unless they are in high school and have a summer job...

**Comment by Eric-Sommer** [comment]
We should keep this in mind when defining "Bedarfsgemeinschaften" (#83). I feel that the SGBII-Definition of an independent child more or less lines up with the tax code .
