### ISSUE TITLE
Decide on form and review docstrings

### ISSUE THREAD

**Issue by MaxBlesch** [iza-institute-of-labor-economics/gettsim#113]
### Bug description

The docstrings in the code follow no general rule and are differing heavily in quality. We need to formulate a set of criterias and either write them down in a GEP or at some part in the documentation. This issue serves as a discussion platform about these criterias and should also be a collection of critical points on the current implemented docstrings.

### Implementation

We will review all docstrings and therefore improve quality and readability of the code.

**Comment by hmgaudecker** [comment]
What did you choose for the DAG rewrite in the end? I think we can just go with that. @tobiasraabe

**Comment by tobiasraabe** [comment]
We chose NumPy docstrings. https://numpydoc.readthedocs.io/en/latest/format.html

**Comment by hmgaudecker** [comment]
Cool, can you please add to the "How to contribute" section of the docs and close it?

While I am at it: On that [page](https://gettsim.readthedocs.io/en/latest/how-to-contribute.html), please break up the numbered list into:

## Prerequisites 
1.  - 2.

## GitHub and Development workflow

3. - 5.

## Code style

Docstrings and other important stuff.
