### ISSUE TITLE
Remove silent year assignment in pensions

### ISSUE THREAD

**Issue by MaxBlesch** [iza-institute-of-labor-economics/gettsim#114]
### Current and desired situation

As we not have the data to calculate the pension claim later than 2016, we just assume the data for 2016 in

https://github.com/iza-institute-of-labor-economics/gettsim/blob/d72b94a4a74bf2230b547e52976466702056dcd7/gettsim/pensions.py#L24

### Proposed implementation

We should not assume anything without letting the user know about it. We should therefore raise an ImplementationError or have some kind of custom message

**Comment by hmgaudecker** [comment]
Still relevant? Include in #185 ? @MaxBlesch

**Comment by MaxBlesch** [comment]
Sorry for the late response. Let's close this. I removed all the silent assignments. I think we discussed enough elsewhere enough how we check year and target combinations!
