### ISSUE TITLE
Treatment of east/west differences

### ISSUE THREAD

**Issue by MaxBlesch** [iza-institute-of-labor-economics/gettsim#115]
### Current and desired situation

In

https://github.com/iza-institute-of-labor-economics/gettsim/blob/d72b94a4a74bf2230b547e52976466702056dcd7/gettsim/social_insurance.py#L31

we create a dictionary to save east/west specific variables. We need to agree on a general treatment of east/west differences.

### Possible alternatives

- Create extra dictionary for east/west specific variables.(Current Situation)

- Store parameters in arrays. See https://gettsim.zulipchat.com/#narrow/stream/212222-general/topic/Plan.20until.20Christmas/near/181733445 on #75

- Carry the variable `westost` through all subfunctions.

- Create new variables in the existing `params` dictionary.

**Comment by Eric-Sommer** [comment]
Since we are now running this function individually, it's probably the easiest to carry `westost` through all the subfunctions and use it to choose the correct parameter.

**Comment by MaxBlesch** [comment]
We solved this issue when regrouping the parameters with #161 to # 172.
