### ISSUE TITLE
Storing of params on ges_renten_ver

### ISSUE THREAD

**Issue by MaxBlesch** [iza-institute-of-labor-economics/gettsim#116]
### Current and desired situation

For the calculation of the pension claim we need demographic data from the past three years. An example for this is the average wage. With #111 came in place that we store the variables in `ges_renten_ver_data` with `variablename +  _ + year`. This can be found in 

https://github.com/iza-institute-of-labor-economics/gettsim/blob/8d9949798a7e6724d0fd0165609946f2f6119e21/gettsim/policy_for_date.py#L116

We want to find an more elegant implementation, which avoids this hard structure in the variables

### Possible alternatives

- Leave this structure in place.

- Store params in a DataFrame.

**Comment by Eric-Sommer** [comment]
Related: the param visualization reveals that one value of `rentenvol` is misspecified. Might be corrected along the way...

![Unbenannt](https://user-images.githubusercontent.com/44068467/70230253-3ad7bf00-1758-11ea-9bcf-7f06fc18d784.PNG)

**Comment by Eric-Sommer** [comment]
Another bit: the 0.036 faktor in `_zugangsfaktor()` needs to be parametrized. Source: [§ 77 (2) Nr. 2 a)](https://www.buzer.de/s1.htm?a=77&g=SGB+VI)

**Comment by MaxBlesch** [comment]
We have different data storage now and the problem is solved. I will reintroduce the pension claim with #195. If you want you can debug the data there @Eric-Sommer. Then we can close here!
