### ISSUE TITLE
Check whether some collaborative editing / communication tools are useful for us

### ISSUE THREAD

**Issue by hmgaudecker** [iza-institute-of-labor-economics/gettsim#12]
E.g., 

- https://stackedit.io/
- https://hackmd.io/

look nice for drawing not-so-heavy coders into the community. 

Any experiences?

**Comment by hmgaudecker** [comment]
Via numpy mailing list: Slack alternative 

FWIW we use Zulip for scikit-image and we are very happy with it. See https://skimage.zulipchat.com

Advantages over Slack:

- free for FOSS, including unlimited archives (https://zulipchat.com/for/open-source/)
- login with GitHub
- Zulipchat is itself FOSS (I have successfully set up my own instance before)
- (upcoming) public archive (read without login)

**Comment by mjbloemer** [comment]
On communication tools: I have never used slack or zulip. They seem as full featured communication solutions to me. Plus mainly web browser or electron based client software.

As slim chat alternatives I would suggest:
- IRC
- XMPP
- matrix

In these cases I imagine we could have a public community room and a nonpublic room.

I am also fine with mailing lists.

**Comment by Eric-Sommer** [comment]
Let me express strong distaste for mailing lists 😃. Slack seems the way to go to me, with the downside of not being FOSS.

**Comment by janosg** [comment]
I have a strong preference for using one tool for everything. It looks like Zulip has some advantages over Slack, but I am only in favor of using it if it also replaces Slack for internal communication. Ideally, we would also align the tools between GETTSIM and OpenSourceEconomics ...

**Comment by hmgaudecker** [comment]
Browsing a little bit, I would favor Zulip: 

- Free for FOSS (=us). IIRC, Slack ends up being quite expensive for many users, so it would not scale well. The 10k-searchable messages limit of the free version is reached quite early. 
- Searchable archives. This is at least as much for users as it is for developers. You do not want to open an issue just because as a Python newbie, some error is puzzling you (re @tobiasraabe's comment [here](https://github.com/iza-institute-of-labor-economics/gettsim/pull/47#issuecomment-544968923)). If some problem crops up repeatedly, google will pick that up (well, eventually [Coming soon: Allow users to read and search public stream history in Zulip's UI without first creating an account.](https://github.com/zulip/zulip/issues/13172)).

**Comment by hmgaudecker** [comment]
> I have a strong preference for using one tool for everything. It looks like Zulip has some advantages over Slack, but I am only in favor of using it if it also replaces Slack for internal communication. Ideally, we would also align the tools between GETTSIM and OpenSourceEconomics ...

While the slack channel at IZA still exists, it has been essentially unused for a while and it is no option going forward.

**Comment by mjbloemer** [comment]
From what I read here zulip sounds a bit nicer than slack. Can we simply test it? (If IRC, XMPP or matrix are still candidates, I could set up a public or private gettsim channel/room. There are also browser based clients.)

One disadvantage of both slack and zulip is the underlying electron framework of the client software. It would be necessary to be able to use it without any client software both mobile and on the desktop (so only a browser). Some users might have a strong distaste™ for electron based software. These apps are [inaccessible](https://github.com/signalapp/Signal-Desktop/issues/2178#issuecomment-384911415), have memory leaks, some are heavily bloated with outdated libraries, use a lot of telemetry... people say it is the next Flash ;)

**Comment by hmgaudecker** [comment]
As an empirical economist, I am in favour of gathering data rather than theorising. So here you go:

https://gettsim.zulipchat.com/join/05mhvu6lg7mgqt7qhvy30msz/

I will set you up as administrators once you have signed up; I will not have a whole lot of time the next few days.

Btw, I have not tried to understand the exact architecture, but it seems to work in the browser without installing anything.

**Comment by hmgaudecker** [comment]
Done via https://gettsim.zulipchat.com -- still need to update settings to make it publicly visible.
