### ISSUE TITLE
Extend Profitability check for benefits

### ISSUE THREAD

**Issue by Eric-Sommer** [iza-institute-of-labor-economics/gettsim#120]
### Current and desired situation

There are three main benefits: ALG2, Wohngeld, Kinderzuschlag (for families with kids). If a household has low income, it may claim positive amounts for several of those. The rule as implemented now is:

1. If Wohngeld + Kiz > ALG2, you get Wohngeld + Kiz. The same holds if either of the Wohngeld and Kiz is larger than the ALG claim.
2. If (1) does not hold, you get ALG2 and neither Wohngeld nor Kiz.

While this rule is in general not wrong, the recent [Starke-Familien-Gesetz](https://www.buzer.de/Starke-Familien-Gesetz.htm) introduced some degree of freedom here:

 ```
(1a) Ein Anspruch auf Kinderzuschlag besteht abweichend von Absatz 1 Nummer 3, wenn

1. bei Bezug von Kinderzuschlag Hilfebedürftigkeit besteht, der Bedarfsgemeinschaft zur Vermeidung von Hilfebedürftigkeit aber mit ihrem Einkommen, dem Kinderzuschlag und dem Wohngeld höchstens 100 Euro fehlen,

2. sich bei der Ermittlung des Einkommens der Eltern nach § 11b Absatz 2 und 3 des Zweiten Buches Sozialgesetzbuch wegen Einkommen aus Erwerbstätigkeit Absetzbeträge in Höhe von mindestens 100 Euro ergeben und

3. kein Mitglied der Bedarfsgemeinschaft Leistungen nach dem Zweiten oder nach dem Zwölften Buch Sozialgesetzbuch erhält oder beantragt hat."
```

This means that if a household is less than 100€ below the threshold where ALG2 pays less than the other benefit(s), it may forego some ALG2 amount in exchange for not being stigmatized, having more duties to the employment office etc.

### Proposed implementation

Extending the rule which benefit to choose would require a behavioral assumption on how households value money against stigma (and other cost related to ALG2 receipt).  This is non-trivial.

### Considered alternatives

Leave as is, which is what I would prefer. I mainly wanted to raise this issue for the sake of completeness.

**Comment by hmgaudecker** [comment]
Thanks, very good catch! 

This is related to the more general question of program take-up (#8) and also caseworker discretion (e.g., https://gettsim.zulipchat.com/#narrow/stream/212222-general/topic/tax.20units.20within.20households/near/180677312). 

An issue is probably not the ideal place for that discussion. I created [a new stream for this on Zulip](https://gettsim.zulipchat.com/#narrow/stream/215726-Take-Up-and.20Discretion/topic/stream.20events/near/182052539),  if someone wants to start filling it with one topic per precise question, that would be great. I am a bit overwhelmed this week. This issue and #8 can then be closed, it will be a while until we can tackle that.

**Comment by Eric-Sommer** [comment]
closed...moved to zulip

**Comment by hmgaudecker** [comment]
Precise link https://gettsim.zulipchat.com/#narrow/stream/215726-Take-Up-and.20Discretion/topic/Which.20benefit.20to.20claim.3F/near/182159872
