### ISSUE TITLE
param style guidelines

### ISSUE THREAD

**Issue by mjbloemer** [iza-institute-of-labor-economics/gettsim#127]
Let us have a short guideline how to format the description and note key in the parameter yaml files.

Initial thoughts:

> I have not much to say about note style guidelines. This really is a detail. We can have a separate discussion on that, sure (about the comma, the full stop and things like "Artikel.."). [Here](https://github.com/iza-institute-of-labor-economics/gettsim/pull/69) I basically just follow the principle to make it is as easy as possible to look up the parameter in the law over on offenegesetze.de and buzer.de plus just have a consistent citing style (it is the citing style  buzer.de uses btw. So it is even very easy to copy and paste the citation).

_Originally posted by @mjbloemer in https://github.com/iza-institute-of-labor-economics/gettsim/pull/74_

> Well, that sounds like a guideline, but it would need to be made consistent in all files. Actually, in order to make full-text search work, one would need to replace the month to words. ('September' instead of '.09.'). Using this bit: `2017 BGBl. I S. 3525` should however lead to the correct bit.

_Originally posted by @Eric-Sommer in https://github.com/iza-institute-of-labor-economics/gettsim/pull/74_

**Comment by Eric-Sommer** [comment]
Add-on: The main purpose is to enable full-text search at [offenegesetze.de](offenegesetze.de). It seems to be enough to stick to the format `[YYYY] BGBL. I S. [SSSS]`. What's before or after is of less importance.

**Comment by mjbloemer** [comment]
suggestion/opinion:

the `name` key
* should have a short (!) name without stating the realm (e.g. "ALG II" or "Kinderzuschlag") again
* is not a sentence
* should always have a `de` and `en` name

the `description` key
* should give a good and full explanation of the parameter
* show the § and Gesetzbuch/Paragraph (history) of that parameter ([Example](https://github.com/iza-institute-of-labor-economics/gettsim/blob/79ca7cedd79566c453f41d4bd6ddddfb81731219/gettsim/data/arbeitsl_geld_2.yaml#L18): this parameter was initially defined in § 30 SBG II, later in § 11b SGB II).
* It should mention bigger amendments/Neufassungen and be as helpful as possible to make sense of that parameter.
* if an english translation is added it should state the same information.

for the `note` key:
* style `Artikel [n] [G./V./B.] v. [DD.MM.YYYY] BGBl. I S. [SSSS]. [optional note].`
  * following the citation stile buzer.de uses: citing the law (Gesetz "G. v."), decree (Verordnung "V. v.") or proclamation (Bekanntmachung "B. v."). See right column header in [this](https://www.buzer.de/gesetz/11821/al64917-0.htm) example.
  * do not add stuff like "geändert durch" (it is always a change) or the date the law gets ito force (this is exaclty the date key in the following line)
* `[optional note]` can be added. Examples: 
  * [Here](https://github.com/iza-institute-of-labor-economics/gettsim/blob/79ca7cedd79566c453f41d4bd6ddddfb81731219/gettsim/data/arbeitsl_geld_2.yaml#L127): In some rare cases I add a date/value for a parameter that did not change the parameter. This is usually the case when a whole block of parameters is changed but one of the parameters did not change (by coincidence or not). In these cases there the same value is still listed in the BGBl. I add a "Betrag unverändert." to the note. This is also to signal that the BGBl. has been taken into account.
  * [here](https://github.com/iza-institute-of-labor-economics/gettsim/blob/79ca7cedd79566c453f41d4bd6ddddfb81731219/gettsim/data/arbeitsl_geld_2.yaml#L109), [here](https://github.com/iza-institute-of-labor-economics/gettsim/blob/79ca7cedd79566c453f41d4bd6ddddfb81731219/gettsim/data/arbeitsl_geld_2.yaml#L673). If a parameter is calculated the note will also give information on the calculation.[^These two examples should not be the norm and should be avoided if possible.]

**Comment by Eric-Sommer** [comment]
I fully agree. Just one remark: Not all parameters are states in laws (e.g. Düsseldorfer Tabelle)

**Comment by mjbloemer** [comment]
Yes. Let's make a short list of parameters that are not stated in the BGBl.

At ifo:
* Zusatzbeitrag GKV.
  Here we make assumptions. Currently (2019), our parameter `akvbs_an`:
  ```csv
  gkvbs_ag,.078,"Artikel 2 G. v. 11.12.2018 BGBl. I S. 2387, 2018 BGBl. I S. 2394: Seit 2019 gleichmäßige Aufteilung Zusatzbeitrag. Annahme Zusatzbeitrag=0.01. Berechnung: (0.146+0.01)/2." 
  ```
  for GETTSIM we should take the part that is stated in the law/BGBl as one parameter and add another parameter for the assumed values. The note key should add a (stable) source.
* Kindliches Existenzminimum.
  ```csv
   kiexmin,4896,"12. Existenzminimumbericht S. 9, Drucksache 19/5400."
  ```
  probably not needed anymore
* Düsseldorfer Tabelle.
  ```csv
  ahunt06o,418,"Düsseldorfer Tabelle 2018 (Stand: 01.01.2018). Wert für Nettoeinkommen 3101-3500."
  ```
  we do not use it. Do you use it in izamod?

do you have more cases?

**Comment by hmgaudecker** [comment]
> (Btw, I also think for SSC parameters we should take the values as given in the law and do the `/2`  spliting ssc between employer and employee on the python side.Which actually reduces the number of parameters.)

Does that work for all years? At some point there was some parameter (GKV?) that was capped at some level for employers and increases would have purely gone to employees? Not sure whether that is still in place or ever had bite though. 

What shall we do about PKV contributions? On the one hand, we would obligated be able to come up with rough guesses. On the other hand, the government now mandates insurance purchase and it seems weird to leave them out. 

Maybe check whether they are passed in (users could have a better model) and use those, else guess?

**Comment by Eric-Sommer** [comment]
the general GKV parameter is still formulated as the total contribution, with the additional contribution specified elsewhere.

Our SOEP preparation collects private contributions in principle, so we could generate moments from that. Right now, we only use the indicator `phv` which is used to calculate public contributions for self-employed.

**Comment by hmgaudecker** [comment]
> the general GKV parameter is still formulated as the total contribution, with the additional contribution specified elsewhere.

This is not what I meant. Quoting good old [Wikipedia](https://de.wikipedia.org/wiki/Arbeitgeberbeitrag): In Deutschland werden die Beiträge zur Renten-, Kranken- und Pflegeversicherung sowie zur Arbeitslosenversicherung grundsätzlich je zur Hälfte vom Arbeitgeber und vom Arbeitnehmer getragen. Abweichend von dem Prinzip der paritätischen Finanzierung haben die Arbeitnehmer seit dem 1. Juli 2005 0,9 Beitragssatzpunkte zur Krankenversicherung allein zu tragen. In der Pflegeversicherung müssen kinderlose Arbeitnehmer einen Beitragszuschlag in Höhe von 0,25 Beitragssatzpunkten alleine tragen. Die Beiträge zur gesetzlichen Unfallversicherung (Berufsgenossenschaft) werden vom Arbeitgeber allein getragen. 

> Our SOEP preparation collects private contributions in principle, so we could generate moments from that. Right now, we only use the indicator `phv` which is used to calculate public contributions for self-employed.

We should really separate concerns. Please forget about the SOEP in this sort of discussion. 

We want to simulate taxes and transfers making minimal assumptions about variables that are relevant for their values. There is no dataset that perfectly gives us everything. E.g., the Tax Payer Panel has everything in even more detail than what we could handle in our code on the tax side. But it does not have anything on transfers. The SOEP is somewhere in the middle on both.

But it is good to have this discussion. So I guess we should require a column with "beitrag_pkv" and maybe one with the fraction that is tax deductible.

**Comment by hmgaudecker** [comment]
> (Btw, I also think for SSC parameters we should take the values as given in the law and do the `/2` spliting ssc between employer and employee on the python side.Which actually reduces the number of parameters.)

So this is exactly how we should do it, except that it is not quite as easy as dividing by two.

**Comment by mjbloemer** [comment]
Regarding the Zusatzbeitrag and employer/employee split:

We define two parameters
* `gkvbs` as defined in the law
* `average_zusatzb` taken from some source


There are three regimes:

1. Old regime (no Zusatzeitrag):

  ```python
  gkvbs_an = param["`gkvbs`"]/2
  gkvbs_ag = param["`gkvbs`"]/2
  ```

2. Regime with Zusatzeitrag, but only employee pays it:

  ```python
  gkvbs_an = param["`gkvbs`"]/2 + `average_zusatzb`
  gkvbs_ag = param["`gkvbs`"]/2
  ```

3. Current regime with paritätische Aufteilung Zusatzeitrag:

  ```python
  gkvbs_an = ( param["`gkvbs`"] + `average_zusatzb`)/2
  gkvbs_ag = ( param["`gkvbs`"] + `average_zusatzb`)/2
  ```

Looks easy enough to me (maybe I missed something from he discussion above, tlnr).

**Comment by hmgaudecker** [comment]
This is a separate concern. The stuff I linked above is a general deviation from the 50:50 split (done back then because of concerns about labour costs to employers). Note that that regime change happened in 2005 already whereas the Zusatzbeitrag came into existence ten years later.

**Comment by mjbloemer** [comment]
Do we need two different parameters for Zusatzebeitrag?

* `gkvbs` as defined in the law (this is [§ 241 Allgemeiner Beitragssatz](https://www.buzer.de/241_SGB_V.htm)).
* `gkvbs_an_only` the 0.9 in § 241a (aufgehoben)?
* `average_zusatzb` taken from some source

Maybe like this?

1. Old regime (no Zusatzeitrag), until 2005-06:
  ```python
  gkvbs_an = param["gkvbs"]/2
  gkvbs_ag = param["gkvbs"]/2
  ```

2. New Regime since 2005-07: employee pays 0.9:
  ```python
  gkvbs_an = (param["gkvbs"] + param["gkvbs_an_only"])/2
  gkvbs_ag = (param["gkvbs"] - param["gkvbs_an_only"])/2
  ```

3. New Regime since 2015 with Zusatzbeitrag:
  ```python
  gkvbs_an = (param["gkvbs"])/2 + param["average_zusatzb"]
  gkvbs_ag = (param["gkvbs"])/2
  ```

4. Current regime with since 2019-01, paritätische Aufteilung Zusatzeitrag:
  ```python
  gkvbs_an = ( param["gkvbs"] + param["average_zusatzb"])/2
  gkvbs_ag = ( param["gkvbs"] + param["average_zusatzb"])/2
  ```

**Comment by hmgaudecker** [comment]
Ah, this really seems like Pandora's box...  Looks about right, except I would interpret regime 2 as:

```
gkvbs_an = (param["gkvbs"] - param["gkvbs_an_only"])/2 + param["gkvbs_an_only"]
gkvbs_ag = (param["gkvbs"] - param["gkvbs_an_only"])/2
```
where the presence of `- param["gkvbs_an_only"]` in the formula would depend on how exactly `gkvbs` is stored.

In all this we should allow users to override stuff. E.g., one might have precise infos on Zusatzbeitrag. Or, in the old days (mid-1990s - mid 2000s) sickness funds were able to set fees themselves so long as they cover all costs. it made a pretty large difference in terms of contributions depending on where you were insured. If somebody wants to investigate that, why make it hard on them?

What would you think about adding a pre-processing step that would add such columns (=often educated guesses / averages are the best one can do, but it is not inconceivable that someone has precise data) before diving into the actual taxes & transfers calculation? Other examples would be the Mietstufen for Wohngeld, Werbungskosten, Vorsorgeaufwendungen (e.g. how much of PKV contribution counts), ... 

This is probably getting a bit too far off -topic, maybe we should continue on Zulip.
