### ISSUE TITLE
Add features for taxable income (zve function)

### ISSUE THREAD

**Issue by MaxBlesch** [iza-institute-of-labor-economics/gettsim#13]
- [ ]  Model all seven income sources separately. This means to split the current `gross_e1` to differentiate between income from farming, business, self-employment and *freie Berufe*.

- [x] If this is done, check which income sources are relevant for which benefits (Elterngeld, ALG I, Wohngeld, ALG II,...). **Edit:** This is obsolete as you don't need the income definitions from the income tax, but rather the *actual* gross incomes (e.g. self-employment and employment income for Elterngeld)

- [ ]  Lohnsteuer: Model withholding tax depending on Steuerklasse. (see also #18)

- [ ]  *Progressionsvorbehalt*: There are a couple of income items (e.g. Elterngeld, Unemployment Benefit) which are not taxed, but they increase the individual tax rate. Not yet modelled. (see #126)

- [ ] Taxable Income: Model the most important deductions (fiscal-wise), e.g. Entfernungspauschale, Unterhaltsfreibetrag.

**Comment by hmgaudecker** [comment]
Still relevant?

**Comment by Eric-Sommer** [comment]
Mostly still relevant.

**Comment by hmgaudecker** [comment]
This is horribly outdated, no use in keeping it open.
