### ISSUE TITLE
Add unemployment benefit(alg2 func) features

### ISSUE THREAD

**Issue by MaxBlesch** [iza-institute-of-labor-economics/gettsim#15]
- [ ] Sozialhilfe acc. to SGB XII for disabled persons is not yet modelled.

- [ ] *Armutsgewöhnungszuschlag*: Until 2010, you got something on top if you went from Unemployment Benefit to ALG2.

- [ ] BuT (Bildungs- und Teilhabepaket): 120€ per child and year for ALG2 recipients to spend for school stuff. params are there.

- [ ] ALG2 asset test: There are additional allowances for *monetary assets* like life insurances which we do not model yet. params are there however.

**Comment by hmgaudecker** [comment]
Still relevant / any progress?

**Comment by Eric-Sommer** [comment]
still relevant, no progress. I could tackle one or two of them as soon as I got acquainted with the new structure.

**Comment by hmgaudecker** [comment]
Closing this as too unspecific now.
