### ISSUE TITLE
Local Variables in tax transfer functions

### ISSUE THREAD

**Issue by MaxBlesch** [iza-institute-of-labor-economics/gettsim#17]
As we parallelize the tax transfer functions on different levels (hh, tu, persons), the functions them self can be simplified.

**Comment by hmgaudecker** [comment]
Still relevant? Not sure where this is supposed to be going...

**Comment by MaxBlesch** [comment]
As we now wrote the individual functions on Series level and adapted the other to their called level, this is done so far. Of course we will still encounter more clever ways to use the information on the called level to simplify functions.
