### ISSUE TITLE
Revise SSC GKV for self employed

### ISSUE THREAD

**Issue by mjbloemer** [iza-institute-of-labor-economics/gettsim#174]
### Bug description

* For self employed who are in GKV, is there really a general cap at 75% of *Bezugsgröße*? This is how it is modeled in https://github.com/iza-institute-of-labor-economics/gettsim/blob/b46acc07ae130215f7b4838acfd83dc4c1d2fd9e/gettsim/soz_vers.py#L117-L142
* This cap at 75% of *Bezugsgröße* might still be relevant for individuals who are not mainly self employed (less than 20 hour of work in self employed), see e.g.: https://selbststaendigkeit.de/sites/default/files/merkblatt_-_die_krankenversicherung_fuer_nebenberuflich_selbststaendige.pdf
* Mindestbemessungsgrundlage for self employed is missing, see [§ 240 SGB V (4)](https://www.buzer.de/240_SGB_V.htm). E.g. Mindestbemessungsgrundlage: 1.061,67 (from [example](https://www.bundesgesundheitsministerium.de/beitraege-und-tarife.html#c4754)) can be calculated as `bezgr_w/90 * 30 = 3185/90 * 30 = 1061,67`.

**Comment by ChristianZimpelmann** [comment]
Hi,
@JHermann99 addressed this issue in #405 where we among other:

- remove cap at 75% of Bezugsgröße
- add Mindestbemessungsgrundlage 

@mjbloemer, would you like to have a look over the PR?
