### ISSUE TITLE
Calculate Lohnsteuer

### ISSUE THREAD

**Issue by MaxBlesch** [iza-institute-of-labor-economics/gettsim#18]
We want to implement the option, that taxes are simulated as Lohnsteuer and not as Einkommenssteuer, as it is of now. The following discussion leads the foundation:

Eric Sommer: 

As of now, our income tax calculation mimics the situation *after* the household filed the tax declaration and received the rebate. This is however not the same what the household pays when receiving wages. This is a fundamental choice one has to make.

1. Simulate Income Tax
     - income from all sources, compare tax due to child benefit payments
2. Simulate withholding tax (Lohnsteuer) on earnings
     - taxable earnings are wages minus
       - Werbungskostenpauschale (2019: 1000€)
       - Sonderausgabenpauschale (2019: 36€)
       - Vorsorgepauschale (similar, but not identical to "Vorsorgeaufwendungen")
     - child tax credit is irrelevant for Lohnsteuer, but not for Soli!
     - everybody receives child benefit.
     - for the remaining income sources, calculate income taxes as before.
     - There is no income splitting for married couples. Instead, the basic allowances might be distributed among couples ("Steuerklassen")

Currently, (1) is implemented, but there might be good reasons to opt for (2) as it more closely resembles the actual disposable income people are facing. It is questionable whether everybody anticipates the future tax rebate. One problem is that "Steuerklassen", which have a major impact on disposable income, are usually not available and would need to be assumed. A second problem is that withholding taxes are attributed to the individual. In order for them to have an impact on labor supply, one would need to drop the unitary household model and think about how common income is distributed among couples. 

On a sidenote, the withdrawal tax is the revelant item when calculating benefit amounts for ALG2 and Housing Benefit.

HMG:

Thanks for the heads-up! Tricky thing indeed, but I do not think that the decision should be that fundamental. We should be able to handle both cases in the code eventually, picking whichever one is relevant for a project. 

We might even be mixing both -- think of female labour supply with tax classes 3 (husband) / 5 (wife) -- she will look at a huge marginal tax rate when looking at her wage bill, but things might look much nicer when filing the tax return. 

As for data on Steuerklassen: We might not get the joint distribution of them with all relevant variables, but we can always get marginals (and some joints) from other data sets. That income tax database for sure, but maybe even Microcensus and EVS have something?

Eric Sommer:

> she will look at a huge marginal tax rate when looking at her wage bill, but things might look much nicer when filing the tax return.

Presumably, but only if she gets her share of the tax rebate (=> Intra-household bargaining). 

EVS and microcensus do not have information on tax brackets. SOEP asked it in 2016, but lots of unrealistic cases (eg. 3/4 combinations).

**Comment by Eric-Sommer** [comment]
related paper on the matter: [Büttner et al (2019): Tax planning of married couples and intra-household income inequality](https://www.sciencedirect.com/science/article/abs/pii/S0047272719301070)
