### ISSUE TITLE
Document data requirements.

### ISSUE THREAD

**Issue by tobiasraabe** [iza-institute-of-labor-economics/gettsim#189]
### Current and desired situation

The old data requirements - shown [here](https://github.com/iza-institute-of-labor-economics/gettsim/blob/903ba2102c8ae6c8b1bdaae0221a5556efd0aa5d/docs/getting-started.rst) - are no longer valid since gettsim is now more dynamic.

Some names have probably changed as well.

### Proposed implementation

Document the data requirements again as a tutorial or explanation. The form should be discussed below.

**Comment by hmgaudecker** [comment]
Seems to be obsolete with #106, tackle in conjunction

**Comment by MaxBlesch** [comment]
Yes, I agree!
