### ISSUE TITLE
Allow for int / DateTime as policy date

### ISSUE THREAD

**Issue by hmgaudecker** [iza-institute-of-labor-economics/gettsim#190]
Requiring `get_policies_for_date("2020")` is counterintuitive and should be trivial to fix.

Allow int in `range(1950, 2050)` or so; DateTimes in similar range ?

**Comment by MaxBlesch** [comment]
I think the range should be replaced on the particular checks on the targets!

**Comment by hmgaudecker** [comment]
I do not understand this sentence.

**Comment by MaxBlesch** [comment]
Sorry. The range checks should be unnecessary as soon as we have the check on the validity of the combination date and target. E.g. requiring income tax for 1940 is not a valid request!

**Comment by hmgaudecker** [comment]
Fair enough, if that works automatically, even better.

**Comment by tobiasraabe** [comment]
Close?

**Comment by hmgaudecker** [comment]
Fixed in #196

**Comment by MaxBlesch** [comment]
I would suggest. Maybe create a new issue for the date checks. We have not yet tackled the time checking. But I think this is not that urgent!
