### ISSUE TITLE
Links to PRs in docs / docs structure

### ISSUE THREAD

**Issue by hmgaudecker** [iza-institute-of-labor-economics/gettsim#193]
### Bug description

The links in changes.rst to issues are (great!!! but) broken. Should be:

`https://github.com/iza-institute-of-labor-economics/gettsim/pull/191`

Is:

`https://github.com/iza-institute-of-labor-economics/gettsim/pulls/188`

i.e., `pulls` should be `pull`

Overloading this: Let us please stick to the 0.3 version of column names instead of the [crosswalk 0.2 - 0.3](https://gettsim.readthedocs.io/en/latest/crosswalk.html). We could put the latter somewhere towards the end for the benefits of us / early adopters. But we have too few of those (I suppose) to make it that salient.

**Comment by tobiasraabe** [comment]
The broken link will be resolved in #198.

**Comment by tobiasraabe** [comment]
Actually, link issue was resolved in #200.

**Comment by hmgaudecker** [comment]
Fixed in #200
