### ISSUE TITLE
Introduce time checks

### ISSUE THREAD

**Issue by MaxBlesch** [iza-institute-of-labor-economics/gettsim#204]
### Current and desired situation

Not all components exist at all times. E.g., `elterngeld` was only introduced in 2007, etc.. In the current version, if a user requests `elterngeld` as a target for 2006, `compute_taxes_and_transfers` will either fail or produce nans. 

### Proposed implementation

We want to have checks, which rule out invalid combinations of date and target. An informative error message should tell the user, considered alternatives like defining a replacement function which yields zero for that time.

**Comment by hmgaudecker** [comment]
Probably this should be a check upon setting up the DAG. Not clear whether we want to have an error or whether missing values are not the right way to go. But this should happen explicitly!

**Comment by hmgaudecker** [comment]
Superseded by #178, #334
