### ISSUE TITLE
Return full set of missing root nodes if DAG cannot be set up

### ISSUE THREAD

**Issue by Eric-Sommer** [iza-institute-of-labor-economics/gettsim#209]
When running SOEP through gettsim, the following is returned: 

``` KeyError: "Missing variable or function 'alleinerziehend_freib_tu'. It is required to compute ['_zu_verst_eink_kein_kinderfreib_tu']."```

This is obviously an internal variable which should not be provided by the user.

If I add a user column `alleinerziehend_freib_tu`, I get also errors for:
- `sonderausgaben`
- `vorsorge`
- `sum_brutto_eink`
(After that I stopped)

i wonder thy this does not yield errors in the test for `compute_taxes_and_transfers`

I run the following
```python
# Load SOEP (simplified)
df = read_soep()
params, policies = get_policies_for_date("2020")
out = compute_taxes_and_transfers(data=df, params=params)
```

`df` has the following columns: 
```
hh_id,
p_id,
syear,
marstat,
d11105,
hhsize,
laborinc,
assetinc,
imp_rent,
sose_pension,
laborinc_ind,
retirement,
pweight,
hweight,
eink_selbstst_m,
divdy,
alg2,
persnr,
partner_id,
tenure,
pgsndjob,
pgemplst,
expft,
exppt,
expue,
pgpartz,
pnr,
sample1,
plb0021,
plc0131_h,
alg_m_l1,
alg_l1,
behinderungsgrad,
ple0097,
plk0001,
D_alg_current,
months_ft,
months_pt,
arbeitsl_lfdj_m,
months_pen,
months_mj,
stell_h,
k_rel,
k_nrinhh,
k_inco,
k_pmum,
kd_amtp,
kc_amtp,
sumkids,
algII_m_l1,
algII_l1,
wgeld_m_l1,
wgeld_l1,
zinszahl,
D_kiz_current,
D_sozh_current,
D_wg_current,
D_alg2_current,
bula,
hgtyp1hh,
counter,
alter,
geburtsjahr,
jahr_renteneintr,
head_num,
tu_id,
hhsize_tu,
kind0_1_num,
kind1_2_num,
kind2_num,
kind2_3_num,
kind3_6_num,
kind6_num,
kind7_16_num,
kind7_11_num,
kind7_13_num,
kind11_num,
kind12_15_num,
kind14_17_num,
kind14_24_num,
kind14_num,
kind15_num,
kind18_num,
kind0_1_num_tu,
kind1_2_num_tu,
kind2_num_tu,
kind2_3_num_tu,
kind3_6_num_tu,
kind6_num_tu,
kind7_16_num_tu,
kind7_11_num_tu,
kind7_13_num_tu,
kind11_num_tu,
kind12_15_num_tu,
kind14_17_num_tu,
kind14_24_num_tu,
kind14_num_tu,
kind15_num_tu,
kind18_num_tu,
hhsize_hh,
anz_erw_hh,
anz_erw_tu,
hh_korr,
betreuungskost_m,
qualification,
hhtyp,
transfers,
alg_soep,
months,
prv_rente_beitr_m,
pensions,
ges_rente_m,
sonstig_eink_m,
childinc,
kapital_eink_m,
vermiet_eink_m,
miete_unterstellt,
miete_unterstellt_tu,
versbez,
welfare,
arbeitsstunden_w,
bruttolohn_m,
othwage_ly,
bruttolohn_m_l1,
months_l1,
arbeitsl_lfdj_m_l1,
bruttolohn_m_l2,
months_l2,
wgeld_l2,
wgeldm__l2,
alg_l2,
algm__l2,
arbeitsl_lfdj_m_l2,
h_wage,
worker_sum,
age2,
age3,
ln_wage,
exper,
exper2,
expue2,
tenure2,
heck_wage,
h_wage_pred,
wohnfläche,
immobilie_baujahr,
baujahr_klasse,
kaltmiete,
heizkost_m,
kapdienst,
kaltmiete_m,
wealth_finan,
wealth_gross,
wealth_net
```

**Comment by hmgaudecker** [comment]
Could you post your the precise call of the function and the column names
in your dataset? Thanks!

**Comment by hmgaudecker** [comment]
I think there was an issue with leaving the list of targets empty, right @tobiasraabe @MaxBlesch ?

But the error message above is not great indeed for the reason Eric mentioned — should we try to go always back to root nodes?

**Comment by tobiasraabe** [comment]
When ``targets`` is empty, gettsim tries to compute everything. If some inputs are missing, some variables will not be computed and eventually a missing variable is requested and everything fails.

What we can do is check before the execution whether all root nodes are available in the data (or are functions which do not require any data if that is possible at all?). This error would be much more informative than the one you had, Eric.

**Comment by MaxBlesch** [comment]
Yes, the problem is the empty target! Then gettsim tries to execute every function in the modules. So far, there are subfunctions in gettsim, which do have more general variable names as input. Thus there exists no input or calculated data that matches these variable names. I suggested earlier, that we do not calculate everything and instead choose the list of all relevant outputs when target is empty. This list can be found [here](https://github.com/iza-institute-of-labor-economics/gettsim/blob/2e1ae4eb74ef879ed73c350159958a5ad22a00f3/gettsim/tests/test_tax_transfer.py#L54). Otherwise we could develop some kind of decorator, which marks such functions!

**Comment by Eric-Sommer** [comment]
I also get the problem if I specify the targets as in the interface tutorial:

```
  targets = [
        "eink_st_tu",
    "soli_st_tu",
    "ges_krankenv_beitr_m",
    "rentenv_beitr_m",
    "arbeitsl_v_beitr_m",
    "rentenv_beitr_m"]
```

**Comment by hmgaudecker** [comment]
Right, thanks for the clarification. I think we should just require the
user to supply targets. There is no way we can set up a list that is valid
across policy environments.

Maybe we could have `policy_for_date` return the standard targets for a
particular year?

**Comment by Eric-Sommer** [comment]
By the way...in my view, `verfügb_eink_m` is the most natural target. Which seems to have been renamed:

```
networkx.exception.NetworkXError: The node verfügb_eink_m is not in the graph.
```

**Comment by MaxBlesch** [comment]
The calculation of `verfügb_eink_m` is not yet calculated. We probably will introduce it back later. But it was not relevant for the course of HMG and hence we did not rewrite the function in the DAG format.

**Comment by hmgaudecker** [comment]
The main problem is that there is no single definition at the individual
level.

We could calculate it at the household level already, though.

**Comment by Eric-Sommer** [comment]
> We could calculate it at the household level already, though.

which is more appropriate anyway.

Any ideas on why the error persists with targets that should be working?

**Comment by hmgaudecker** [comment]
You are still missing some necessary inputs. The error message currently stops upon the first ancestors it cannot compute, it seems. We should go back to the root nodes, though.

E.g., if you do:
```python
compute_taxes_and_transfers(
    data=df,
    user_functions=policy_func_dict,
    params=params_dict,
    targets="sonderausgaben",
    debug=True
)
```
You will see that `sonderausgaben` depends on `hh_id`, `tu_id`, `kind`, `betreuungskost_m`, and `_anz_erwachsene_tu`:

|   p_id |   hh_id |   tu_id | kind   |   betreuungskost_m |   _anz_erwachsene_tu |   sonderausgaben |
|-------:|--------:|--------:|:-------|-------------------:|---------------------:|-----------------:|
|      0 |       0 |       0 | False  |                  0 |                    1 |                0 |
|      1 |       1 |       1 | False  |                  0 |                    1 |                0 |
|      2 |       2 |       2 | False  |                  0 |                    1 |                0 |
|      3 |       3 |       3 | False  |                  0 |                    1 |                0 |
|      4 |       4 |       4 | False  |                  0 |                    1 |                0 |

So eventually, the error here should be that not `sonderausgaben` is missing, but (presumably) `betreuungskost_m`.

**Comment by hmgaudecker** [comment]
For a fairly comprehensive list of targets (am I missing anything?):

```python
compute_taxes_and_transfers(
    data=df,
    user_functions=policy_func_dict,
    params=params_dict,
    targets=[
        "eink_st_tu",
        "soli_st_tu",
        "sozialv_beitr_m",
        "wohngeld_m_hh",
        "kindergeld_m_hh",
        "kinderzuschlag_m_hh",
        "arbeitsl_geld_m",
        "arbeitsl_geld_2_m_hh",
    ],
)
```
This set of columns (sorted alphabetically):

|                     |
|:--------------------|
| alleinerziehend     |
| alter               |
| anz_minderj_hh      |
| arbeitsl_lfdj_m     |
| arbeitsl_vor2j_m    |
| arbeitsl_vorj_m     |
| arbeitsstunden_w    |
| behinderungsgrad    |
| betreuungskost_m    |
| bewohnt_eigentum_hh |
| bruttolohn_m        |
| bruttolohn_vorj_m   |
| eink_selbst_m       |
| entgeltpunkte       |
| exper               |
| geburtsjahr         |
| geburtsmonat        |
| geburtstag          |
| ges_rente_m         |
| hat_kinder          |
| heizkosten_m_hh     |
| hh_id               |
| hh_typ              |
| in_ausbildung       |
| jahr_renteneintr    |
| kaltmiete_m_hh      |
| kapital_eink_m      |
| kind                |
| m_elterngeld        |
| m_elterngeld_mut    |
| m_elterngeld_vat    |
| miete_unterstellt   |
| mietstufe           |
| prv_krankenv        |
| prv_rente_beitr_m   |
| rentner             |
| selbstständig       |
| sonstig_eink_m      |
| tu_id               |
| tu_vorstand         |
| vermiet_eink_m      |
| vermögen_hh         |
| wohnfläche_hh       |
| wohnort_ost         |

works for me in 2020. This might be missing some corner cases, so please keep those questions coming and let @MaxBlesch where the crosswalk needs to be updated.

**Comment by Eric-Sommer** [comment]
My input data now contain all columns you specified (`hh_typ` is obsolete), but I still get the error message from above.

**Comment by MaxBlesch** [comment]
I am working with @Eric-Sommer on it. We probably found it. It was an interface issue!

**Comment by hmgaudecker** [comment]
I do not understand why this is closed. Do we have a fix that gives a more useful error message somewhere?

**Comment by Eric-Sommer** [comment]
The reason for the error was I did not enter any `user_functions`, assuming I only need them for reforms. This corresponds to your remark from yesterday on Zulip. But returning missing root nodes is probably still a good idea...
