### ISSUE TITLE
Remove pycodestyle restriction in .pre-commit-config.yaml

### ISSUE THREAD

**Issue by MaxBlesch** [iza-institute-of-labor-economics/gettsim#21]
Once https://gitlab.com/pycqa/flake8-docstrings/issues/36 is fixed and merged, we will delete the restricton for the version to be lower than 4. Then we add minimum version on flake8-docstrings.

**Comment by hmgaudecker** [comment]
Should work with restricting flake8-docstrings >= 1.3.1, IIUC. @raholler, could you please try for econ-project-templates and/or here, in no particular order or rush?

**Comment by raholler** [comment]
we do not use pydocstyle in econ-project-templates. Not sure what my task is here:

- add pydocstyle in econ-project-templates and add minimum version of flake8-docstrings?
- add minimum version of flake8-docstrings and unrestricted pydocstyle version in this repo?

**Comment by hmgaudecker** [comment]
Ah, I thought we were using it there, too, sorry. Nevermind, then --Max, can you check whether it works if you remove the <=4.0 restriction on pycodestyle and add the minimum version on flake8-docstrings?
