### ISSUE TITLE
`kost_unterk` of kinderzuschlag

### ISSUE THREAD

**Issue by MaxBlesch** [iza-institute-of-labor-economics/gettsim#220]
### Current and desired situation

Kinderzuschlag is the only benefit where the cost of housing is not capped at a certain threshold. Corresponding to #199 we should introduce some kind of capping mechanism which can be specified in params or via a reform. The corresponding code can be found [here](https://github.com/iza-institute-of-labor-economics/gettsim/blob/b4aa85f7d94337eb072cdfb6230e6dacb35d0854/gettsim/benefits/kinderzuschlag/kost_unterk.py#L5).

**Comment by Eric-Sommer** [comment]
It's probably correct as it is: "Bei  Ermittlung  des  eigenen  Bedarfs  der  Eltern  werden  folgende  Anteile der **tatsächlichen** Wohnkosten berücksichtigt" ([Merkblat, p. 13](https://www.arbeitsagentur.de/datei/kiz2-merkblattkinderzuschlag_ba015395.pdf)

There is also an inofficial [Kinderzuschlag-Recher](https://www.kinderzuschlag.org/kiz/rechner/) which might inform our tests.
