### ISSUE TITLE
Adopt design of starting page of documentation from respy

### ISSUE THREAD

**Issue by ChristianZimpelmann** [iza-institute-of-labor-economics/gettsim#237]
### Current and desired situation

Documentation is well structured, but could be nicer designed

### Proposed implementation

I really like the design of the respy package: https://respy.readthedocs.io/en/latest/ (not sure though how hard that is to implement)

### Considered alternatives

leave as is

**Comment by hmgaudecker** [comment]
Will redesign eventually, but no need for a forever-open issue and probably won't be based on respy.
