### ISSUE TITLE
Polish function table in documentation

### ISSUE THREAD

**Issue by ChristianZimpelmann** [iza-institute-of-labor-economics/gettsim#238]
### Current and desired situation

improve documentation

### Proposed implementation

For functions without docstring text a description of the first parameter is shown. The goal should be to have a docstring for each function.

Also: the second column is hard to read because one needs to scroll to the left. Can we do one of the following:

-    have line breaks?
-    increase the width of the documentation? It only spans 2/3 of my screen.

**Comment by ChristianZimpelmann** [comment]
Meanwhile, all functions should have docstrings.

The remaining problem is the visualisation of the table: Does anybody know how the table generated by

```
.. automodsumm:: gettsim.functions
   :functions-only:
```
can be adjusted? I didn't find anything during a quick search.

**Comment by hmgaudecker** [comment]
Closing as this does not seem worth spending much time on.
