### ISSUE TITLE
Rename gettsim.data

### ISSUE THREAD

**Issue by hmgaudecker** [iza-institute-of-labor-economics/gettsim#239]
### Current and desired situation

I believe this discussion ([Zulip](https://github.com/iza-institute-of-labor-economics/gettsim/pull/235#issuecomment-724778789), [GitHub](https://github.com/iza-institute-of-labor-economics/gettsim/pull/235#issuecomment-724778789)) has highlighted a deeper problem: The name of the namespace `gettsim.data` is very unspecific. 

The namespace currently holds the parameters of the taxes and transfers system which feed into the functions in `benefits` (next issue to be opened in a minute), `soz_vers`, and `taxes`. My view is that this is enough and we should not expand beyond this. This should be reflected in the name.

### Proposed implementation

Rename to `gettsim.parameters`

Thoughts, @MaxBlesch @amageh @janosg @ChristianZimpelmann @Eric-Sommer @mjbloemer @stichnoth ?

**Comment by ChristianZimpelmann** [comment]
sounds good

**Comment by Eric-Sommer** [comment]
I agree!

**Comment by mjbloemer** [comment]
Sounds good to me 

OpenFisca also named it `parameters`: https://github.com/openfisca/openfisca-france/tree/master/openfisca_france/parameters

**Comment by hmgaudecker** [comment]
Cool, I think you guys (@MaxBlesch @ChristianZimpelmann ?) can go ahead with this one for 0.4 then.

#240 as well? I assume the lack of activity there is due to similarity with this one. If not, please voice your concerns!

**Comment by MaxBlesch** [comment]
Sorry. This data is fine. Also, we can change benefits. But with soz_vers we have param files, variables, and functions, which carry this name. So maybe we should have a broader discussion on how to rename this!

**Comment by MaxBlesch** [comment]
We renamed to parameters, social insurance and transfers. Closes #240.
