### ISSUE TITLE
Set up development workflow

### ISSUE THREAD

**Issue by hmgaudecker** [iza-institute-of-labor-economics/gettsim#24]
Things like required reviews etc. over at OpenSourceEconomics / estimagic etc. look very useful to me. Now that we have ported everything from the old Gitlab repository, we can also be a bit more defensive on merging things. 

@tobiasraabe, @janosg: Do you have any workflow written up somewhere? We should discuss this eventually and I'll set up the Github Project accordingly.

**Comment by janosg** [comment]
We don't have anything written up. For me the most essential things are:

1) Only allow squash merges. This keeps the history clean.
2) Only merge into develop or master after at least one approving review. Of course, tests also have to pass. The reviews are very time consuming but very valuable if done properly. 
3) Pull requests are opened right when someone starts to work on a feature and have a meaningful description / to-do list. This can be encouraged by templates. 

We can debate if we need a develop branch or just have master and feature branches. I'm for a develop branch. PRs are then first merged into develop and the master branch always has the state of the last stable release.

Since gettsim is a large project, we will have to think more carefully about permissions. I suggest that all regular contributors have the permission to create and push to a feature branch. Otherwise we need forks and that is cumbersome. However, merging and reviewing should be restricted to a very small set of core contributors with a lot of python experience and knowledge of the project.

**Comment by tobiasraabe** [comment]
I agree with everything Janos said. The only addition I would make is that the decision for a develop branch hinges to some extent on the release cycle of the package. If there are frequent releases and merges from develop to master, than the frontpage conveys activity. If the releases are rather infrequent as with respy, but development is still going on on develop, there is a huge gap between the frontpage and the current version which confuses people and does not look good.

And another clarification. If there exist a master and a develop branch, use the normal merge to merge develop into master. Thus, all squashed PR commits are included in master.

**Comment by hmgaudecker** [comment]
Thanks. Given the nature of things, I would rather think that having a structure of master and release branches is more useful than master/develop. Makes it easier to backport things and if people develop policy reforms they should do so against the latest released branch. An additional distinction between master/develop would then be more confusing than helpful, or am I missing something? The only use case would be interacting features, right?

**Comment by janosg** [comment]
I agree. Basically our develop branch in other projects is a release branch that we just re-use every time. But real release branches with attached version number are cleaner.

**Comment by hmgaudecker** [comment]
@tobiasraabe: Can you include this in a draft for #36, please? I suggest to have branches with major version numbers and tags off them for releases.

**Comment by tobiasraabe** [comment]
I think what pandas is doing is a good start.

- They do everything on the master branch.
- For every minor release (version major.minor.patch), they maintain a separate branch. The branches can receive backports which triggers new patch releases.
- They use milestones to collect PRs and issues for the next patch, minor or major release.

Is that also what you two have in mind?

**Comment by tobiasraabe** [comment]
I am unfamiliar with backporting, but there seems to be a git command ``cherrypick`` which let's you pick a single commit. I would make a preliminary doc section for this and if we ever have to do a backport, we can rework the section.

https://stackoverflow.com/questions/13275223/git-strategy-to-backport-bugfixes-into-older-branches-cherry-pick-vs-merge

**Comment by hmgaudecker** [comment]
Sounds all good. 

Not sure of the milestones yet, I would add that only later. 

I use cherry-pick frequently. Works very well once a codebase is reasonably stable.

**Comment by hmgaudecker** [comment]
> I think what pandas is doing is a good start.
> 
>     * They do everything on the master branch.
> 
>     * For every minor release (version major.minor.patch), they maintain a separate branch. The branches can receive backports which triggers new patch releases.
> 
>     * They use milestones to collect PRs and issues for the next patch, minor or major release.
> 
> 
> Is that also what you two have in mind?

I believe I would prefer Numpy's model: 

* Branch major.minor once all relevant PRs (as outlined in milestones, for example) are merged.
* Create only tags major.minor.patch to setup version
* Backport relevant bugfixes from master to major.minor, release major.minor.patch with a new tag if useful.

I am not sure why I want to keep huge amount of branches major.minor.patch around if I only ever work on major.minor.max ? At least I personally almost never look at tags, but I do look around in the list of branches frequently. If we can avoid clutter there at low (zero?) cost in terms of workflow, at least one person would benefit :-). Or would bump2version not work with this model?

**Comment by tobiasraabe** [comment]
That was a misunderstanding, I think. Pandas maintains branches with names `0.1.x` which is used for all patch versions of `0.1.`. So I think it is the same branching model.

**Comment by hmgaudecker** [comment]
Okay, I gathered that from what you suggested in the GEP stream over on Zulip: 

> There exist branches for minor version which are still maintained by the GETTSIM
> team. These branches are called **major.minor.x. The branches comprise the latest
> released patch version, x, plus unreleased changes, e.g. backports.

The `, x,` in the last sentence should go IMHO.
