### ISSUE TITLE
17 character rule in GEP-1

### ISSUE THREAD

**Issue by MaxBlesch** [iza-institute-of-labor-economics/gettsim#244]
We specified in [GEP-1](https://gettsim.readthedocs.io/en/stable/geps/gep-01.html) that there is a hard limit of 17 characters on all column names, which are in the user-facing API. Additionally, we have a test, which enforces this convention.

We will only enforce this limit on most import column names, but not everywhere.

- [ ]  Reformulate GEP-1.

- [ ] Rewrite test.

**Comment by ChristianZimpelmann** [comment]
Following up on this.

Current status:
- The character limit is formulated in GEP-1, but not enforced.
- Several input variables are longer than 17 characters (e.g. `bewohnt_eigentum_hh`, `immobilie_baujahr_hh`, `gr_bewertungszeiten`)
- Several functions are much longer than 17 characters (e.g. `proxy_eink_vorj_elterngeld`, `regelbedarf_m_grunds_ia_vermögens_check_hh`)

In my opinion, the 17 characters are in some cases not enough for easily understandable function names.

My proposal:
- Increase character limit for input variables and main outcome variables (`DEFAULT_TARGETS`) to 20.
- Increase character limit for all other functions/potential targets to 25.
- Adjust all longer variables and functions accordingly
- Enforce the new limits using a test in the future.

That way we are still 7 characters below the STATA limit.

**Comment by hmgaudecker** [comment]
+1

We have run into this as a real limit now. It is just a difference whether you have your own codebase (abbreviations okay) or a library (name clarity much more important). We will not make Stata users' lives too difficult if we require them to use a renaming table should  they need more space.
