### ISSUE TITLE
generic hypothetical household data analysis

### ISSUE THREAD

**Issue by Eric-Sommer** [iza-institute-of-labor-economics/gettsim#26]
One of the main applications of the model will presumaby be the application of 'typical' households, as microdata access is restricted outside of academia. For this reason, we need at some point a framework for preparing such data and make them congruent to the `tax_transfer` module.

The building blocks can be found in `hypo.py` (in particular `create_hypo_data()`) and would need to made more generic. In particular, the user should be able to decide upon

1. mandatory
    1. Type of Household = ['single', 'single_parent', 'couple', 'couple with children']
    2. Amount/Range of monthly income 
    3. number of kids
2. optional
    1. Age for each member (default: 40 for adults, 6 for kids)
    2. Type of Dwelling (Default: 'rent')
    3. Monthly Rent / Housing Expenses (Default: average value from BA statistics)
    4. Monthly heating costs (Default: average value from BA statistics)
    4. Employment Type (default: 'Employee')
    5. In case of couples: Single-Earner or fixed income of one partner?
    6. East or West Germany

**Comment by hmgaudecker** [comment]
This seems obvious now from the documentation.

**Comment by Eric-Sommer** [comment]
Let me bring this up again. Providing an interfacte for hypothetical household data takes burden from users in providing own data and fiddling around with wrong data types, missing columns etc. Instead, he could ask "What's the tax burden for a single parent with two kids living in Mietstufe 5". It also serves as quality check for us. Finally, one can produce descriptives of the tax-ben system like this (this was done with v0.2):

![image](https://user-images.githubusercontent.com/44068467/84937793-98bc6a80-b0dc-11ea-979d-2b0163b4f0da.png)

I therefore think there's value in "shipping" this along with the core model.
