### ISSUE TITLE
CI fails for Python 3.7 and 3.8

### ISSUE THREAD

**Issue by Eric-Sommer** [iza-institute-of-labor-economics/gettsim#260]
### Bug description

The `pytest` for soli recently started [failing](https://github.com/iza-institute-of-labor-economics/gettsim/pull/259/checks?check_run_id=1633714318) for python 3.7 and 3.8, for all three platforms. On my local machine (Linux, python 3.7) everything runs smoothly.

This line causes the error: https://github.com/iza-institute-of-labor-economics/gettsim/blob/c1626f91864f8cf39ca2bdf86ff416d7ca169ce2/gettsim/piecewise_functions.py#L83-L88

**Comment by ChristianZimpelmann** [comment]
This should be fixed now.
