### ISSUE TITLE
Add the dates of last changes to gettsim links 

### ISSUE THREAD

**Issue by hendshe** [iza-institute-of-labor-economics/gettsim#265]
I figured out that my input list was outdated since you've updated the one on the website (I guess, apparently you introduced new variables in the input list, probably the mietstufe). I only figured this out by comparing the earlier version of the input list I was working on and the current one. 

I would suggest that you add at the end of the documentation pages/tutorials _when these were last edited. This would be of much help to draw attention to the changes you have made or that you applied ones. Also, maybe if you carried out crucial changes you could point this out in the section beneath the lists or elsewhere ( updates section/attention notes on the same link, etc.), if this is possible. For now, the dates of when last changes have been made would be helpful (it is also carried out on the [SOEP companion] links along with the attention notes for changes or important info.).

E.g. (Last change: Jan 26, 2021)

**Comment by hmgaudecker** [comment]
Thanks! 

I am not sure what you mean by "your input list" ? 

In general, you should use the version of the documentation that matches the version of GETTSIM you installed. If you go to  https://gettsim.readthedocs.io/en/stable/, you can select the version for the documentation at the bottom left of the screen.

The types of input variables generally only change with the major versions (0.3, 0.4, ...). 

We are a small team, so if there are broken links for older versions, they are unlikely to get fixed.

**Comment by Eric-Sommer** [comment]
@hmgaudecker : input list = List of [input variables](https://gettsim.readthedocs.io/en/stable/gettsim_objects/variables.html)

@hendshe : `mietstufe` has been mentioned in the list since 11/2020 [at least](https://github.com/iza-institute-of-labor-economics/gettsim/commit/c54f2359cd2a3a057ae0119e73a1d6051bc14218#diff-8bdfe2845577c6298098a88d7fc982e2682410f4855221846bab27b9c73dc553). Possibly it was omitted before.

**Comment by hendshe** [comment]
> 
> @hendshe : `mietstufe` has been mentioned in the list since 11/2020 and has been omitted [before](https://github.com/iza-institute-of-labor-economics/gettsim/commit/c54f2359cd2a3a057ae0119e73a1d6051bc14218#diff-8bdfe2845577c6298098a88d7fc982e2682410f4855221846bab27b9c73dc553).
Yes, thanks! That's what I mean and I also kind of expected.

**Comment by hendshe** [comment]
@Eric-Sommer following up on this, how could one get information to generate this input variable `mietstufe ` (i.e. to feed it into the model)? since it is now included among the input variables list. I found no info. on that. I guess this input variable is needed for the calculation of wohngeld_basis.

**Comment by hmgaudecker** [comment]
My best guess that it is just an integer with the Mietstufe in the municipality you are looking at. If you want to ignore it, just use some typical value? [background: we are trying to require users to be explicit about stuff like this, i.e., not make any assumptions/imputations ourselves]

**Comment by Eric-Sommer** [comment]
[Mietstufe](https://www.wohngeld.org/mietstufe.html) is an integer ranging from 1 (very low rent, a town in rural Rhineland Palatinate) to 7 (very high rent, Munich). Level 7 was introduced in 2020. It is specific to the municipality. Mietstufe 3 is supposed to reflect average rent.

**Comment by hendshe** [comment]
Great! Thank you for the helpful comments!
