### ISSUE TITLE
Actually run CI

### ISSUE THREAD

**Issue by hmgaudecker** [iza-institute-of-labor-economics/gettsim#27]
Looking back at this I just realised that the Azure pipeline was never run. Are we missing some trigger or so?

**Comment by tobiasraabe** [comment]
I triggered the pipeline manually. We should check whether a new build was triggered after merging another PR. If not, we probably have to delete ``pr: None``.

**Comment by hmgaudecker** [comment]
Thanks, looks good! We'll see when we merge #25 or whatever fixes #5.

**Comment by hmgaudecker** [comment]
Seems to work fine. Thanks!
