### ISSUE TITLE
kinderzuschlag_m/target has no corresponding function

### ISSUE THREAD

**Issue by hendshe** [iza-institute-of-labor-economics/gettsim#277]
The computation of Kinderzuschlag (targetvariable) is rejected because of the following error when using the compute_taxes_and_transfers.
Error message 
ValueError: The following targets have no corresponding function

![image](https://user-images.githubusercontent.com/77800456/110662410-c5159b00-81c5-11eb-8dbd-4a8df13c62b9.png)

**Comment by ChristianZimpelmann** [comment]
Kinderzuschlag is only calculated on the hh level and the variable is, hence, called `kinderzuschlag_m_hh`.

I just saw that the documentation is not up-to-date at this point -- will fix it.
