### ISSUE TITLE
Versioning: include last year for which policy environment is updated

### ISSUE THREAD

**Issue by ChristianZimpelmann** [iza-institute-of-labor-economics/gettsim#284]
### Current and desired situation

Might be helpful for users to include the last year for which we have updated the policy environment in our version numbers.

### Proposed implementation

e.g. `2021.0.3` or `0.5.7.2021`

### Considered alternatives

Don't do this at all.

**Comment by hmgaudecker** [comment]
Having thought a bit about this, I do not think it is very helfpul.

Implementation of changed parameters is typically very quick. To the extent that we will never be feature-complete, something like v1.5.4.2024 might give a false sense of security if 1.6.0.2024 adds features...

Anyone: Please re-open in case you disagree.
