### ISSUE TITLE
Fix Advanced Usage Tutorial

### ISSUE THREAD

**Issue by hendshe** [iza-institute-of-labor-economics/gettsim#289]
### Bug description
Not working for me for some time now 

![image](https://user-images.githubusercontent.com/77800456/118689779-a952f480-b807-11eb-925d-d4b5081f6bec.png)

### System
- OS: [e.g. Windows 10]

**Comment by Eric-Sommer** [comment]
what is your version of gettsim? `conda list gettsim`

**Comment by hendshe** [comment]
> what is your version of gettsim? `conda list gettsim`

0.4

**Comment by ChristianZimpelmann** [comment]
Then please update to the newest version (0.4.1): https://anaconda.org/gettsim/gettsim

It should work then.

**Comment by hendshe** [comment]
Great! Thanks for the tip. And how about this one?
![image](https://user-images.githubusercontent.com/77800456/118803744-08664700-b8a4-11eb-8468-8e4482599c82.png)

**Comment by ChristianZimpelmann** [comment]
Great, that it worked!

Is this the full traceback? I cannot see which file is missing.

**Comment by hendshe** [comment]
AttributeError: module 'os' has no attribute 'errno'

![image](https://user-images.githubusercontent.com/77800456/118970290-58114500-b96e-11eb-93da-f70105fe5306.png)

**Comment by hmgaudecker** [comment]
This is annoying. Looks like `os.errno` has become a builtin module `errno` in Python 3 and `os.errno` has been removed in Python 3.7.

Any chance that an updated pydot would give the correct message?

**Comment by Eric-Sommer** [comment]
@hendshe : can you try `conda update pydot` and try again?

**Comment by hendshe** [comment]
Now it works perfectly again, many thanks for your tips! Updating pydot was indeed the solution.
