### ISSUE TITLE
Data types conversion in Gettsim

### ISSUE THREAD

**Issue by hendshe** [iza-institute-of-labor-economics/gettsim#291]
### Bug description
I tried using the code for the variables' types conversion as per the script in config.py since after running the 'compute taxes and transfers' command, it complained about the types of my input data and that they have to be converted. I ran the code below (as taken from this config.py script) but, after that, despite that this below-code ran (and it indeed showed me the three different defined series in the variables explorer window; Bool, Int, Float), I still get the same error mesage as before. I have no clue why.

###The code which crashes (after running it, I still receive the types conversion message)
```
from gettsim.typing import BoolSeries
from gettsim.typing import FloatSeries
from gettsim.typing import IntSeries

STANDARD_DATA_TYPES =  {
    "hh_id": IntSeries,
    "tu_id": IntSeries,
    "p_id": IntSeries,
    "vermögen_hh": FloatSeries,
    "bruttolohn_m": FloatSeries,
    "alter": IntSeries,
    "selbstständig": BoolSeries,
    "wohnort_ost": BoolSeries,
    "hat_kinder": BoolSeries,
    "eink_selbst_m": FloatSeries,
    "ges_rente_m": FloatSeries,
    "prv_krankenv": BoolSeries,
    "prv_rente_beitr_m": FloatSeries,
    "bruttolohn_vorj_m": FloatSeries,
    "arbeitsl_lfdj_m": IntSeries,
    "arbeitsl_vorj_m": IntSeries,
    "arbeitsl_vor2j_m": IntSeries,
    "arbeitsstunden_w": FloatSeries,
    "geburtsjahr": IntSeries,
    "geburtstag": IntSeries,
    "geburtsmonat": IntSeries,
    "mietstufe": IntSeries,
    "entgeltpunkte": FloatSeries,
    "kind": BoolSeries,
    "rentner": BoolSeries,
    "betreuungskost_m": FloatSeries,
    "kapital_eink_m": FloatSeries,
    "vermiet_eink_m": FloatSeries,
    "kaltmiete_m_hh": FloatSeries,
    "heizkosten_m_hh": FloatSeries,
    "jahr_renteneintr": IntSeries,
    "behinderungsgrad": IntSeries,
    "wohnfläche_hh": IntSeries,
    "m_elterngeld": IntSeries,
    "m_elterngeld_vat": IntSeries,
    "m_elterngeld_mut": IntSeries,
    "in_ausbildung": BoolSeries,
    "alleinerziehend": BoolSeries,
    "bewohnt_eigentum_hh": BoolSeries,
    "immobilie_baujahr_hh": IntSeries,
    "sonstig_eink_m": FloatSeries,
    "jahr": IntSeries,
}
```

**Comment by Eric-Sommer** [comment]
Can you also include the call to `compute_taxes_and_transfers` which leads to the crash?

**Comment by hendshe** [comment]
```
result = compute_taxes_and_transfers(
    data=data,
    params=policy_params,
    targets=targets,
    functions=policy_functions,
    columns_overriding_functions=[
    "anz_kinder_hh",
    #"anz_kinder_tu",
    "anz_minderj_hh",
    #"kapital_eink_m_tu",
    #"vermiet_eink_m_tu",
]
)
```
![image](https://user-images.githubusercontent.com/77800456/121394013-372a8700-c951-11eb-8c43-bad4c18289b8.png)

**Comment by Eric-Sommer** [comment]
That means the column `data["p_id"]` differs from the required type. Your code does not provide anything on how `data` is created. Check whether `data.dtypes` is correct

**Comment by hendshe** [comment]
Yes, I know. But isn't  the `STANDARD_DATA_TYPES ` code above used to define the correct types?

**Comment by Eric-Sommer** [comment]
> Yes, I know. But isn't the `STANDARD_DATA_TYPES ` code above used to define the correct types?

It is used to check whether the input provided by the user has the correct `dtype`, which seems to be not the case for you.

**Comment by hendshe** [comment]
Yes, indeed, it was not the case (that might be because it was read from a Stata file). Ok, I was thinking this `STANDARD_DATA_TYPES` part is used to define the right types (correct the types in my case)...Isn't it used at all to define them? (I have done the types conversion commands already but I wanted to make use of the ready conversion part as per the STANDARD_DATA_TYPES).

**Comment by Eric-Sommer** [comment]
> Isn't it used at all to define them? (I have done the types conversion commands already but I wanted to make use of the ready conversion part as per the STANDARD_DATA_TYPES).

The `STANDARD_DATA_TYPES` dictionary is used to check whether user input has the right `dtype`. It does not alter the input data which might have unforeseen consequences.

**Comment by hendshe** [comment]
Good to know. Thanks a lot, Eric!
