### ISSUE TITLE
Check for non-unique p_id

### ISSUE THREAD

**Issue by JHermann99** [iza-institute-of-labor-economics/gettsim#293]
### Bug description

When passing non-unique p_id, GETTSIM gives the same output for all rows of that p_id, although they have different input parameters.

### To Reproduce

Dataset with same p_id but different bruttolohn_m:
``` python
data = pd.DataFrame(
    {
        "p_id": 1,
        "tu_id": 1,
        "hh_id": 1,
        "bruttolohn_m" : [2000,3000],
        "wohnort_ost": False,
        "kind": False,
        "alter": 35,
        "selbstständig": False,
        "hat_kinder": False,
        "eink_selbst_m": 0,
        "ges_rente_m": 0,
        "prv_krankenv": False,
        "arbeitsstunden_w": 40,
        "in_ausbildung": False,
        "kapital_eink_m": 0,
        "alleinerziehend": False,
        "vermiet_eink_m": 0,
        "behinderungsgrad": 0,
        "jahr_renteneintr": 0,
        "prv_rente_beitr_m": 0,
        "betreuungskost_m": 0,
    },
    index=[1,2],
)
```

applying gettsim:
```python
params_dict, policy_func_dict = set_up_policy_environment("2021")

ergebnis = compute_taxes_and_transfers(
    data=data,
    functions=policy_func_dict,
    params=params_dict,
    targets="eink_st_tu",
)
ergebnis
```
output:

![image](https://user-images.githubusercontent.com/85927891/123283127-61f90b80-d50b-11eb-8170-6028aa756800.png)

I would recommend outputting a warning, if p_id is not unique.
### System

- OS: Windows 10
- GETTSIM Version [0.4.1]

**Comment by ChristianZimpelmann** [comment]
Good catch! I think we should even throw an error in this case.

**Comment by Eric-Sommer** [comment]
It's a little tricky because at plain sight, `p_id` is unique. I'd rather argue to enforce equal length for all columns (on top of checking unique `p_id`).

**Comment by hmgaudecker** [comment]
It only seems that way because @JHermann99 used clever shortcuts :smile:. Have a look at the resulting df, two rows with same data (including `p_id`) everywhere except for income. 

I think the code internally requires `p_id` to be unique, so I also think we should enforce it by throwing an error as @ChristianZimpelmann suggested above.
