### ISSUE TITLE
Pension Earning points unclear

### ISSUE THREAD

**Issue by hendshe** [iza-institute-of-labor-economics/gettsim#295]
### Current and desired situation

Pension earning points variables are not fully clear (in terms of definition, reference time point, and which one is the cumulative). Dealing with the three variables (`entgeltpunkte`, `entgeltpunkte_lohn `,`entgeltpunkte_update`) is not so much straightforward .

1. Gettsim follows this calc.
  ```
R = EP * ZF * Rw
   return (entgeltpunkte_update * zugangsfaktor * rentenwert).clip(lower=0)

```
Then, I infer that EP= `entgeltpunkte_update `which should reflect-as per the source- "Summe der Entgeltpunkte aufgrund des Versicherungsverlaufs"is the cumulative one. 

2. The input list uses [`bruttolohn_m `] which should refer to the current year, while [`entgeltpunkte_lohn `] "[Return](https://gettsim.readthedocs.io/en/stable/gettsim_objects/functions.html?highlight=entgeltpunkte#gettsim.functions.entgeltpunkte_lohn) earning points for the wages earned in the last year." Or is the calculation based here on `bruttolohn_vorj_m`? Using DAG graph, I only see bruttolohn_m impacting entgeltpunkte_lohn.

Proposed implementation

### Considered alternatives

Maybe provide some tutorial examples on it or make a precise wording ( to which year the input variable refers, to which year the output variable refers, what is just entgeltpunkte, ..)

**Comment by hmgaudecker** [comment]
Yeah, the pensions part has never been really used so far, I believe. It is getting a major overhaul in #275, maybe this is being solved along the way there already?

**Comment by hmgaudecker** [comment]
Once again following an x-link... @ChristianZimpelmann, will this be closed by #275 ?

**Comment by ChristianZimpelmann** [comment]
Depends on if you, @hendshe, find this clear enough now. 

- `entgeltpunkte` is an input variable and specifies the accumulated sum of Entgeltpunkte before the current year.
- `entgeltp_update_lohn` (former name: `entgeltpunkte_lohn`) calculates the number of Entgeltpunkte that are added in the current year.
- `entgeltpunkte_update` calculates the accumulated sum of Entgeltpunkte including the current year (the sum of the two former variables, because we don't consider Entgeltpunkte through other sources like parenting)

**Comment by hendshe** [comment]
Thanks! To be honest, I have not worked on it since then. I see now that you have changed some of the namings. I guess the issue was getting information on the very first point since this is not offered in the data. Anyways, thanks for your comment above, I hope it is clear for other users too. If something pops up, I will comment once again here. And feel free to close the issues if you think it is resolved.
