### ISSUE TITLE
Intermediate variables could not be computed along with targets

### ISSUE THREAD

**Issue by hendshe** [iza-institute-of-labor-economics/gettsim#296]
### Bug description

Adding intermediate variables (which are not typical out variables) to the list of targets produces the following error 
### To Reproduce
targets = [
         
             "regelbedarf_m_vermögens_check_hh ",
             "arbeitsl_geld_2_eink_hh ",         
             
]

### Expected behavior

ValueError: The following targets have no corresponding function:
### Screenshots/Error messages

![image](https://user-images.githubusercontent.com/77800456/125204058-93980380-e27b-11eb-9d2e-a9b500c9722c.png)
### System

- OS: [e.g. Windows 10]

**Comment by ChristianZimpelmann** [comment]
Can you try without the whitespace at the end?

**Comment by hendshe** [comment]
Unfortunately still doesn't work

**Comment by ChristianZimpelmann** [comment]
Ok, that's strange. Can you post the full code to reproduce the error please?

**Comment by hendshe** [comment]
Is this sufficient?
```
targets = [
             "unterhaltsvors_m",
             "regelbedarf_m_vermögens_check_hh ",
             "arbeitsl_geld_2_eink_hh ",   
]
result = compute_taxes_and_transfers(
    data=data,
    params=policy_params,
    targets=targets,
    functions=policy_functions,
    columns_overriding_functions=[
    "anz_kinder_hh",
    "anz_minderj_hh",
]
)
result.head(3)
```

**Comment by ChristianZimpelmann** [comment]
Yes, thanks!

But the strings in the target list still contain whitespaces at the end! That way it cannot work.

**Comment by hendshe** [comment]
Thanks, Christian! I was just about to post that it is now solved, I didn't pay attention to the white spaces in strings earlier, only removed the last empty line.
