### ISSUE TITLE
Simplify notation for piecewise_quadratic tax schedule

### ISSUE THREAD

**Issue by ChristianZimpelmann** [iza-institute-of-labor-economics/gettsim#298]
### Current and desired situation

Currently, the parameters are defined in a rather unintuitive way as seen below.

```
params_dict_fdp["eink_st"]["eink_st_tarif"] = {
    0: {
      "lower_threshold": -np.inf,
      "upper_threshold": 9744,
      "rate_linear": 0,
      "rate_quadratic": 0,
      "intercept_at_lower_threshold": 0,
    },
    1: {
      "upper_threshold": 90000,
      "rate_linear": 0.14,
    },
    2: {
      "upper_threshold": np.inf,
      "rate_linear": 0.42,
      "rate_quadratic": 0,
    }
}
```

### Proposed implementation

Think about more intuitive representation.

**Comment by hmgaudecker** [comment]
I do not think this can be simplified much. What do you find not intuitive about it?

What needs improvement, though, is the interface for adjusting things after a policy environment has been set up. See our private conversation on Zulip *(occurred to me while preparing an exam, so could not make it public at the time :smile:)*

**Comment by ChristianZimpelmann** [comment]
Then, I misunderstood @hmgaudecker's message.
