### ISSUE TITLE
API for children

### ISSUE THREAD

**Issue by Eric-Sommer** [iza-institute-of-labor-economics/gettsim#30]
There are a couple of issues which would make the setup of a custom data set as input to `tax_transfer()` cumbersome at the moment. Let's collect them here.

- [ ] There are many variables counting the number of children in different age brackets: `[child_num, child3_6_num, child7_13_num, ...]`. This is due to the scattered system of benefits in Germany. To get rid of this, each function could compute the necessary values itself, based on age of each household member. This would also reduce the amount of data carried from one function to the next.

**Comment by hmgaudecker** [comment]
Thanks. Let us please go for one issue per topic rather collecting many different things in one.

**Comment by hmgaudecker** [comment]
Content-wise: Sounds good. We also need to add links between parents and children (relevant for larger households,  re-married people, kids > 16,  etc.)

E.g., not at all obvious if you have members age 55, 52, 22 and the youngest being a student. Probably parents receiving child benefits, but better make the link explicit.

I would think that all taxes / transfers are going to the parents (any exceptions? BAFöG?). So we would loop over the connected kids and calculate tax breaks, child benefits, Unterhaltsvorschuss, who knows what.

**Comment by Eric-Sommer** [comment]
> Content-wise: Sounds good. We also need to add links between parents and children (relevant for larger households, re-married people, kids > 16, etc.)
> E.g., not at all obvious if you have members age 55, 52, 22 and the youngest being a student. Probably parents receiving child benefits, but better make the link explicit.

This should actually be done in the data preparation already. If the 22-year old son is a student, he is in the same tax unit. If he is employed, he is a tax unit on his own. 

> I would think that all taxes / transfers are going to the parents (any exceptions? BAFöG?). 

It is usually easier to assign benefits (e.g. kindergeld) to the children and compare it with their income / hours worked (there used to be thresholds) first. Child alimony is explicitly an income of the child which e.g. matters for the means test of the Kinderzuschlag. We don't care on which bank account the benefit is transferred to.

> So we would loop over the connected kids and calculate tax breaks, child benefits, Unterhaltsvorschuss, who knows what.

I rather thought along the lines of inserting the household / tax unit as a whole and then count the children below 7 years (e.g. for ALGII).

**Comment by hmgaudecker** [comment]
> > Content-wise: Sounds good. We also need to add links between parents and children (relevant for larger households, re-married people, kids > 16, etc.)
> > E.g., not at all obvious if you have members age 55, 52, 22 and the youngest being a student. Probably parents receiving child benefits, but better make the link explicit.
> 
> This should actually be done in the data preparation already. If the 22-year old son is a student, he is in the same tax unit. If he is employed, he is a tax unit on his own.

I do not think this is feasible. [I am outside my level of detailed understanding for what follows]. If the kid works for < x Euros a month in addition to being a student, he remains in the tax unit, right? At least parents will still receive child benefit. This will be something for GETTSIM to take care of. 

> > I would think that all taxes / transfers are going to the parents (any exceptions? BAFöG?).
> 
> It is usually easier to assign benefits (e.g. kindergeld) to the children and compare it with their income / hours worked (there used to be thresholds) first. Child alimony is explicitly an income of the child which e.g. matters for the means test of the Kinderzuschlag. We don't care on which bank account the benefit is transferred to.

Well, you did not in the applications you had :-) In a collective model of household behaviour, this may matter a great deal. I'd always calculate a few more things and keep them around rather than taking shortcuts. May make sense, of course, to store it with the kid, and sum later. 

> > So we would loop over the connected kids and calculate tax breaks, child benefits, Unterhaltsvorschuss, who knows what.
> 
> I rather thought along the lines of inserting the household / tax unit as a whole and then count the children under the age of 6 (e.g. for ALGII).

Well, what I am trying to say is that you may have two previously-married household members, living together, unmarried, each bringing two kids along. Two separate tax units, one household. We will need to keep track of which kid belongs to which partner for some benefits, right? Can't hurt in any case.

**Comment by Eric-Sommer** [comment]
We deal with exactly these cases via the tax unit / household distinction. 

Household 1: If the kid is in education **and** above 18, he is in the same tax unit and the parents receive child benefit (or child tax credit). The income threshold for former years is secondary and conditional in being in education. Then, child benefit is assigned first on the kid (`kindergeld`) and then summed up (`kindergeld_tu` and `kindergeld_hh`). 
 If he is not in education, he is a tax unit on his own, i.e. no child benefit. In ALGII terms however, they form the same household. 

> Two separate tax units, one household. We will need to keep track of which kid belongs to which partner for some benefits, right? Can't hurt in any case.

You are right, I was not explicit about this. We actually have `child_num` and `child_num_tu` (along with all the age brackets) to account for this. But one does not have to bother that much if the correct unit is fed into the function. For income tax, you would get automatically `child_num_tu` while you get `child_num` for ALGII.

**Comment by hmgaudecker** [comment]
> We deal with exactly these cases via the tax unit / household distinction.
> 
> Household 1: If the kid is in education **and** above 18, he is in the same tax unit and the parents receive child benefit (or child tax credit). The income threshold for former years is secondary and conditional in being in education. Then, child benefit is assigned first on the kid (`kindergeld`) and then summed up (`kindergeld_tu` and `kindergeld_hh`).
> If he is not in education, he is a tax unit on his own, i.e. no child benefit. In ALGII terms however, they form the same household.

My point is that distinguishing between these cases should be the responsibility of GETTSIM, not the user. 

So, for all people who form a household we need to feed in the relations between them. Or at least we need to provide functionality to do that. 

> > Two separate tax units, one household. We will need to keep track of which kid belongs to which partner for some benefits, right? Can't hurt in any case.
> 
> You are right, I was not explicit about this. We actually have `child_num` and `child_num_tu` (along with all the age brackets) to account for this. But one does not have to bother that much if the correct unit is fed into the function. For income tax, you would get automatically `child_num_tu` while you get `child_num` for ALGII.

Yes, and under the new interface we first calculate it and then feed the correct stuff into functions.

**Comment by MaxBlesch** [comment]
I would close this. The original issue was solved a long time ago and we now calculate all these things in [`demographic_vars.py`](https://github.com/iza-institute-of-labor-economics/gettsim/blob/master/gettsim/demographic_vars.py). For the discussion of non standard households, I think we have #89. Any objections?
