### ISSUE TITLE
Inflated tax values

### ISSUE THREAD

**Issue by hendshe** [iza-institute-of-labor-economics/gettsim#307]
Hi all,
### Bug description
While checking the values of the taxes predicted by gettsim, there are some implausibly inflated values that I cannot track whz they are inflated. Since I did not include the intermediate variables needed for the calculation of these taxes among my targets.

We should be speaking here about monthly taxes, therefore the values are too high (parameters are set for 2018). And tu_id and hid coincide here. Any clue?
### Ex.
pid	hid	abgelt_st_tu	soli_st_tu	   eink_st_tu	bruttolohn_m	       Vermögen_hh
1	9	0	             29567.824	   537596.8	           0	                    2005000
2	9	0	             29567.824	   537596.8	           0	                    2005000
3	9	0	             29567.824	   537596.8	           0                       2005000
4	9	0	             29567.824	   537596.8	           0                       2005000
5	9	0	             29567.824	   537596.8	           0             	    2005000
1	2	0	             17560.51	   319282	               4000	                    633000
2	2	0	             17560.51	   319282	               3800              	    633000
3	2	0	             17560.51	   319282	                  0	                    633000

### Expected behavior
It would be good to set a cap for the taxes simulated by gettsim (abgelt_st_tu, soli_st_tu , eink_st_tu) in case this is set by law, I don't know if it is the case. But I know that for income tax at least, the top tax rate should be 45%.

### System
- OS: [e.g. Windows 10]

**Comment by ChristianZimpelmann** [comment]
It seems like these households have some other source of income in addition to the labor earnings (e.g. from self-employment, rents, etc.). Please check the components of `sum_brutto_eink` and/or the inputs you put into GETTSIM to find out which one it is.

I hope this helps to find the source of the high taxes.

**Comment by hmgaudecker** [comment]
> We should be speaking here about monthly taxes, therefore the values are too high (parameters are set for 2018). And tu_id and hid coincide here. Any clue?

Taxes are always at an annual level. In fact, any variable that does not have `_m` for monthly at the end is annual.

No Lohnsteuer modelled so far, see the PR for that.

**Comment by hendshe** [comment]
Yes, now I see, thank you both! Apparently, this comes from the rental income input variable. Thanks also for the remark about Lohnsteuer/payroll tax. 
Could we tell, when comparing the SOEP and GETTSIM's taxes on offer, and except for payroll tax that is not modelled yet, how comparable GETTSIM's taxes to these aggregates in the [SOEP ]. The payroll taxes in the SOEP refer to the insurance tax(es) (https://www.diw.de/documents/publikationen/73/diw_01.c.809647.de/diw_ssp0922.pdf) (I11111, I11112).

**Comment by ChristianZimpelmann** [comment]
I think it should be the sum of abgelt_st_tu, soli_st_tu, and eink_st_tu as you suggested at the beginning. But the variable description reads:

```quote
The tax estimates come from Schwarze (1995). Taxes are estimated for each tax unit
within the household and then summed over all tax units within the household to arrive at a total household tax burden. The estimated tax burdens include federal income
taxes and solidarity surplus tax. These routines are described in Schwarze (1995). No
algorithms are provided for the tax estimates
```

So it depends on which sources of income are considered in their imputation algorithm (based on Schwarze)

**Comment by mjbloemer** [comment]
> No algorithms are provided for the tax estimates.

That sentence that always bothered me in the PEQUIV Codebook ;)

I guess now they use the DIW STSM? It would be nice to see a direct comparison one day using various MSMs.
