### ISSUE TITLE
Clarify meaning of `kaltmiete_m_hh`

### ISSUE THREAD

**Issue by ChristianZimpelmann** [iza-institute-of-labor-economics/gettsim#309]
### Current and desired situation

Kaltmiete sounds to me like the Nettokaltmiete is meant (rent without any additional payments). To my understanding, for Wohngeld, ALG 2, and Grundsicherung, however, the Bruttokaltmiete is relevant (including kalte Nebenkosten).

https://www.bonn.de/themen-entdecken/soziales-gesellschaft/angemessene-miethoehen-in-bonn.php
https://de.wikipedia.org/wiki/Kaltmiete

### Proposed implementation

- Find out if my understanding is correct. @Eric-Sommer @stichnoth @mjbloemer ?
- If yes, change the description of the input variable and potentially the variable name.

**Comment by mjbloemer** [comment]
I think your understanding is correct. For Wohngeld see § 9 https://www.buzer.de/gesetz/8380/a156464.htm. Most important thing is to separate heating cost.

Also, for KdU some statistics and definitions what is included in Unterkunftskosten/Betriebskosten/Heizkosten at https://statistik.arbeitsagentur.de/SiteGlobals/Forms/Suche/Einzelheftsuche_Formular.html?nn=1524064&topic_f=kdu-kdu

**Comment by Eric-Sommer** [comment]
I agree. In my view, `kaltmiete` should be interpreted as Brutto-Kaltmiete, including costs for elevator, garbage and the like. In other words, `kaltmiete` is `warmmiete` minus heating cost.

**Comment by hmgaudecker** [comment]
Thanks.

My vote is for renaming to `bruttokaltmiete_m_hh` to make the difference with everyday language clear.

**Comment by ChristianZimpelmann** [comment]
That is my favourite, too. Problem is that it has 19 characters and in GEP 1 we restricted ourselves to 17 characters.

But I would like to increase this limit anyway. (see my comment in #244)
