### ISSUE TITLE
Improve description of input variable ``vermögen_hh``

### ISSUE THREAD

**Issue by ChristianZimpelmann** [iza-institute-of-labor-economics/gettsim#326]
### Current and desired situation

``vermögen_hh`` is currently described as "Wealth of household". But for the calculation of transfers certain parts of wealth are typically excluded (e.g. private home, personal chattels).

### Proposed implementation

- [x] Find out wealth definition for all transfer types
- [x] If anyhow possible find a common definition and add this definition to the documentation
- [ ] Potentially, rename the variable
- [ ] Add testcases for Arbeitslosengeld 2 with positive wealth (see #331, [precise link](https://github.com/iza-institute-of-labor-economics/gettsim/pull/331#commitcomment-64644909))
- [ ] Check if tests for other transfers test for wealth allowance

### Considered alternatives

- If definitions differ too much, we might need to split up the input variable into categories.

**Comment by ChristianZimpelmann** [comment]
@LauraGergeleit, has put together this overview how wealth is defined for different transfers (Thanks!):

# Vermögensbegriff bei Transferleistungen

ALGII = Grundsicherung für Arbeitslose
GSA/E = Grundsicherung im Alter/ bei Erwerbsminderung
WoGe = Wohngeld
KiZu = Kinderzuschlag

| **Nicht zum Vermögen gezählt**                                                    | ALGII | GSA/E | WoGe  | KiZu  |
| --------------------------------------------------------------------------------- | ----- | ----- | ----- | ----- |
| angemessener Hausrat                                                              |   x   |   x   |   x   |   x   |
| angemessenes Kraftfahrzeug für jede erwerbsfähige Person                          |   x   | x(HF) |   x   |   x   |
| Vermögensgegenstände für Altersvorsorge u. Altersvorsorgevermögen                 |   x   |   x   |   x   |   x   |
| selbstgenutztes Hausgrundstück/Eigentumswohnung v. angemessener Größe             |   x   |   x   |   x   |   x   | 
| Vermögen z. Beschaffung/Erhaltung eines Hausgrundstücks für Pflegebedürftige      |   x   |   x   |   x   |   x   |
| Vermögen zum Aufbau/Sicherung einer Lebensgrundlage o. Gründung eines Hausstandes |   x   |   x   |   x   |   x   |
| Familien- und Erbstücke                                                           | x(HF) |   x   |       | x(HF) |
| Sachen u. Rechte, wenn Verwertung unwirtschaftlich oder eine besondere Härte wäre |   x   |   x   |       |   x   |
| Gegenstände zur Aufnahme/Forsetzung der Berufsausbildung/ Erwerbstätigkeit        |   x   |   x   |   x   |   x   |
| Gegenstände zur Befriedigung geistiger Bedürfnisse                                |       |   x   |   x   |       |

HF = Härtefall

My suggestion:

- We can stick with a single wealth variable for now.
- Change description: "Wealth of household" -> "Wealth of household that is taken into account for the calculation of transfer"
- Leave variable name as is. (Alternative would be to change it as follows: `vermögen_hh` -> `berücks_vermögen_hh`)

@hmgaudecker @Eric-Sommer @mjbloemer, what do you think?

**Comment by Eric-Sommer** [comment]
I agree 100% 👌. Renaming is not necessary IMO. Thanks @LauraGergeleit for compiling this overview!

**Comment by hmgaudecker** [comment]
Great work, many thanks! Caseworker discretion really means something here, then...

I think we should definitely change the name. As per the list above, the content of the variable will exclude the entire wealth of many households. In the lower 70% of the wealth distribution, the variable has nothing to do with how economists ordinarily would use the term. If I prepared any data set just looking at the variable names and not paying close attention to the descriptions, I'd make big mistakes.

My favourite would be `vermögen_bedürftigk_hh` ("Vermögen für Bedürftigkeitsprüfungen")

The table above should go to the documentation along with an explainer, links to the laws / regulations, and eventually best practices for preparing data sets.

**Comment by ChristianZimpelmann** [comment]
I am fine with changing the name (@hmgaudecker's point also seems relevant). However, `vermögen_bedürftigk_hh` is too long (for basic input variables, we restrict ourselves to 20 characters).

`berücks_vermögen_hh` would fit exactly (still my favourite). Any other ideas? `vermögen_bedürf_hh` would work.

**Comment by hmgaudecker** [comment]
Oh yes, forgot to mention that the restriction might be interpreted as "excluding suffixes" :wink:. I am sort of serious on that one. 

What I don't like about the `berücks_` version is that it does not make clear at all what it is taken into account for. Why do we need so many characters in German? Compare `vermögen_für_bedürftigkeitsprüfung` to `assets_in_means_test` (would almost work written out fully) :cry: 

So yes, probably `vermögen_bedürft_hh` -- any reason you cut the "t" at the end?

**Comment by ChristianZimpelmann** [comment]
> So yes, probably vermögen_bedürft_hh -- any reason you cut the "t" at the end?

No 😅 So let's go for `vermögen_bedürft_hh`.

@LauraGergeleit, I think you can add this issue to your ToDo list
