### ISSUE TITLE
`berechne_vorsorge_bis_2004` uses variables that aren't defined anywhere

### ISSUE THREAD

**Issue by ChristianZimpelmann** [iza-institute-of-labor-economics/gettsim#329]
### Bug description

The function `berechne_vorsorge_bis_2004` uses the input `anzahl_erwachsene` which is not defined anywhere and should be probably `anz_erwachsene_hh`. 

We need to check this (and the other arguments) properly.

**Comment by ChristianZimpelmann** [comment]
Just realized that this function is not used as a function that is part of the DAG, but used directly. Would be better to specify it as inner function then. 

I will start a PR soon.

**Comment by hmgaudecker** [comment]
Good testcase out of the box for that aggregation component of GEP-04 😊

**Comment by ChristianZimpelmann** [comment]
> Would be better to specify it as inner function then.

This already happened during #355.

Can be closed.
