### ISSUE TITLE
Showcase the implementation of a custom reform (e.g., UBI)

### ISSUE THREAD

**Issue by tobiasraabe** [iza-institute-of-labor-economics/gettsim#34]
We want to showcase the implementation of a custom reform to make users comfortable with the package.

A possible candidate is the UBI because it is interesting and 643e8106257e7514a7deb0126ce89f49734950fd contains some code examples which can be reused.

**Comment by Eric-Sommer** [comment]
Building Blocks:
- Specify reform parameters, either altering existing ones or introducing new ones.
- copy `tax_transfer()` to an alternative module (e.g. `tax_transfer_ubi()`).
    - If nothing has changed *or monetary parameters only* have changed for some tax-ben element, call the respective function.
    - For larger reform blocks, one needs to formulate alternative functions.
    - Some elements may even become obsolete. (`kiz` as prime example)
- There will be an overall wrapper which will need to be told which reforms to run (`tax_transfer()` will always be run).
- Testing can and should be done with hypothetical households.

**Comment by hmgaudecker** [comment]
Closing this for now, this is too far in the future.
