### ISSUE TITLE
Unify use of German or Englisch for math variables (sum, avg, ..)

### ISSUE THREAD

**Issue by ChristianZimpelmann** [iza-institute-of-labor-economics/gettsim#346]
### Current and desired situation

We use a mix of `sum`, `summe`, `durchschnittl`, `avg`

### Proposed implementation

- [ ] Decide for either English or German
- [ ] Make respective changes

### Advantages of considered alternatives

- German: would be more consistent since other parts of column names are typically in German
- English: shorter

**Comment by hmgaudecker** [comment]
I think it should be English, brevity beats consistency in the current setup. I only saw one German math expression, too.
