### ISSUE TITLE
Reconsider structure of `brutto_eink_X`

### ISSUE THREAD

**Issue by hmgaudecker** [iza-institute-of-labor-economics/gettsim#347]
### Current and desired situation

- Some of the `brutto_eink_X` variables are just annualised versions of monthly quantities (e.g., `brutto_eink_5` is the annualised version of `kapitaleink_m`. Worse, after considering allowances, it is called `kapitaleink_minus_pauschbetr`.
- The name `brutto` suggests to me that these are unconditional gross incomes. However, some things are subtracted (e.g., `werbungskosten` for `brutto_eink_4` are subtracted but `sparerpauschbetrag` is not in `brutto_eink_5`, see above)
- There is some value in keeping these names from the law, but there is value in having names describing concepts, too.
- Aside: `brutto_eink_1` seems wrong (should be 3?) and we will want to add agriculture/forestry (1) and business enterprises (2). Maybe not measured in the SOEP but elsewhere.

**Comment by Eric-Sommer** [comment]
Just three points:
- I agree in general, this is yet another IZAMOD rudiment. The appropriate legal term is 'Einkünfte'. 
- When it comes to income tax, having variables corresponding to legal terms outwieights descriptive names in my opinion.
- Not subtracting `sparerpauschbetrag` in the calculation of `bruttp_eink_5` seems [wrong](https://de.wikipedia.org/wiki/Eink%C3%BCnfte_aus_Kapitalverm%C3%B6gen_(Deutschland)).

**Comment by hmgaudecker** [comment]
@Eric-Sommer @mjbloemer -- based on personal experience, I am pretty sure the clipping at zero is wrong:

```py
def brutto_eink_6(vermiet_eink_m: FloatSeries) -> FloatSeries:
    """Aggregate monthly gross rental income to yearly income.

    Parameters
    ----------
    vermiet_eink_m
        See basic input variable :ref:`vermiet_eink_m <vermiet_eink_m>`.

    Returns
    -------

    """
    return (12 * vermiet_eink_m).clip(lower=0)
```

Same for the other categories. That is, if you make losses in one domain, you lower the total taxable income. Thoughts?

**Comment by hmgaudecker** [comment]
Just repeating what I [put on Zulip](https://gettsim.zulipchat.com/#narrow/stream/224837-High-Level-Architecture/topic/renaming/near/274891226):

| old                                                 | new                          | comment                                          |
| --------------------------------------------------- | ---------------------------- | ------------------------------------------------ |
| brutto_eink_1                                       | eink_selbst                  | Not sure we want to clip at zero here?           |
| brutto_eink_1_tu                                    | eink_selbst_tu               |                                                  |
| brutto_eink_4                                       | eink_abhängig_beschäftigt    | Not sure we want to clip at zero here?           |
| brutto_eink_4_tu                                    | eink_abhängig_beschäftigt_tu |                                                  |
| kapitaleink_m                                       | kapitaleink_brutto_m         |                                                  |
| brutto_eink_5                                       | kapitaleink_brutto           | Not sure we want to clip at zero here?           |
| brutto_eink_5_tu                                    | kapitaleink_brutto_tu        |                                                  |
| kapitaleink_minus_pauschbetr                        | kapitaleink                  |                                                  |
| brutto_eink_6                                       | eink_vermietung                 | Not sure we want to clip at zero here?    |
| brutto_eink_6_tu                                    | eink_vermietung_tu              |                                                  |
| brutto_eink_7                                       | eink_rente_zu_verst          |                                                  |
| brutto_eink_7_tu                                    | eink_rente_zu_verst_tu       |                                                  |
| zu_verst_ges_rente                                  | eink_rente_zu_verst_m        | had suggested brutto_eink_7_m before             |
| zu_verst_ges_rente_tu                               | eink_rente_zu_verst_tu_m     | had suggested brutto_eink_7_m_tu before          |
| sum_brutto_eink                                     | sum_eink                     | plus all derived from that                       |
| wohngeld_brutto_eink_tu, wohngeld_sonstiges_eink_tu | wohngeld_eink_tu             | combine in one, had suggested differently before |

Just for some context: The `brutto` part was not true at all, most actually calculate the net income explicitly. This version should also be very clear when things are just divided by 12 for getting monthly values (we might miss a couple still).

**Comment by mjbloemer** [comment]
The clipping is wrong, yes. Maybe there is a better, simple approximation? Generally allow losses to freely offset any other income category (which would still be an approximation)? Thoughts are only keywords: horizontaler/vertikaler Verlustausgleich, Verlustvortrag, Verlustrücktrag, permanent losses in one domain might be considered "Liebhaberei" in the long run, the rules differ across the seven income domains... another rabbit hole.

**Comment by hmgaudecker** [comment]
:scream:

Yes, we won't manage or aim to replicate tax preparation programmes... This just seemed like a first-order mistake to me, there is just no reason to clip. Things come directly from the data, essentially, with few exceptions (`werbungskostenpauschale` etc.) we don't look at deductions much, so scope for what you describe seems limited.

Thanks!

**Comment by mjbloemer** [comment]
Yes. That is what I mean: No clipping would be a better approximation even without other rules in place here.
