### ISSUE TITLE
Check determination of unemployment benefits

### ISSUE THREAD

**Issue by hmgaudecker** [iza-institute-of-labor-economics/gettsim#354]
### Bug description

1. `berechtigt_für_arbeitsl_geld` currently checks for:

   ```py
   (summe_ges_priv_rente_m == 0)
   ```
   
   This does not seem likely. I can't believe that if I happen to draw 20 Euros from a private pension contract starting at age 55, I lose any eligibility for `arbeits_los_geld` starting at that age.

2. The variables `arbeitsl_lfdj_m`, `arbeitsl_vorj_m`, `arbeitsl_vor2j_m` are just aggregated up and then things are determined for the entire year. Currently means that if `arbeitsl_vorj_m + arbeitsl_vor2j_m = 13` and `arbeitsl_lfdj_m = 12`, people qualify as ineligible.
 
   Ideally would want to have, if eligibility is for 24 months, that `arbeitsl_vorj_m + arbeitsl_vor2j_m = 18` means half a year of eligibility in the current year, but that would have severe downstream consequences (check `arbeitsl_geld_2` eligibility just for a few months etc.. This would be a large painful operation.

   In any case, this does not seem to be the ideal way of discretizing. Need to think through.

**Comment by ChristianZimpelmann** [comment]
I think this was fully addressed by #457. @hmgaudecker, do you agree?

**Comment by hmgaudecker** [comment]
Not fully, actually, sorry this slipped through in the review.

> 1. `berechtigt_für_arbeitsl_geld` currently checks for:
>        ```python
>        (summe_ges_priv_rente_m == 0)
>        ```
>            
>        This does not seem likely. I can't believe that if I happen to draw 20 Euros from a private pension contract starting at age 55, I lose any eligibility for `arbeits_los_geld` starting at that age.

This check is now replaced by

```python
alter < regelaltersgrenze
```

but if I draw my **public** pension fully before that age, I won't get them anymore (we just talked about that with @TeBackh the other day after lunch...).

But it would be better to open a small follow-up issue for that rather than keeping this open.

**Comment by TeBackh** [comment]
seems like checking for whether ```jahr_renteneintr ``` is filled would do the job. at least until Teilrente is implemented

**Comment by hmgaudecker** [comment]
Fixed in #457  except for the tiny issue in #543.
