### ISSUE TITLE
Policy parameter policy_params["soz_vers_beitr"]["beitr_satz"]["ges_pflegev"]["standard"] is wrong for 2022

### ISSUE THREAD

**Issue by JuergenWiemers** [iza-institute-of-labor-economics/gettsim#373]
The policy parameter policy_params["soz_vers_beitr"]["beitr_satz"]["ges_pflegev"]["standard"] is wrong for 2022

Minimal code example:
```
import numpy as np
import pandas as pd
from gettsim import set_up_policy_environment
from gettsim.config import ROOT_DIR

for year in range(2016, 2023):
    policy_params, policy_functions = set_up_policy_environment(date=f"{year}-01-01")
    print(year, policy_params["soz_vers_beitr"]["beitr_satz"]["ges_pflegev"]["standard"])
```

The parameter for 2022 should be 0.01525, not 0.01175.

**Comment by hmgaudecker** [comment]
Have not checked correctness, but I'd trust you on this one! 

No need for a code example in this case. 

Would you mind starting the Pull Request? Probably just a matter of changing that one number in the YAML file. If tests need adjustment, I'd be happy to look into that.

**Comment by JuergenWiemers** [comment]
O.k., I'm going to try this. My first pull request (ever)!

**Comment by hmgaudecker** [comment]
> O.k., I'm going to try this. My first pull request (ever)!

And it might have set the record for the most quickly merged PR in GETTSIM right away. Great job! :smile:
