### ISSUE TITLE
Automatic type conversion of imported variables from Stata

### ISSUE THREAD

**Issue by JuergenWiemers** [iza-institute-of-labor-economics/gettsim#375]
### Current and desired situation

When using Stata's "Python integration" to directly import Stata data sets into GETTSIM (i.e., without recourse to intermediate files on the hard disk), currently the imported data does not conform to the data types required by GETTSIM. The notebook attached to [this](https://gettsim.zulipchat.com/#narrow/stream/320439-GETTSIM-Workshop-2022/topic/GETTSIM.2FStata-Integration/near/278193203) Zulip post illustrates the current behavior. It would help Stata users if this conversion would happen automatically.

### Proposed implementation

A convenience function like `pdataframe_from_stata()`, which wraps `pystata.stata.pdataframe_from_data()` and converts the variable types to the types needed. See [here](https://www.stata.com/python/pystata/stata.html#pystata.stata.pdataframe_to_data) for the documentation of the PyStata interface. Without arguments, `pystata.stata.pdataframe_from_data()` imports all variables in the currently active Stata dataframe. It might be desirable to only import the variables required by GETTSIM. This would automatically check whether all of the variables needed in GETTSIM are present in the currently active Stata dataframe and issue a warning if required variables are missing.

**Comment by ChristianZimpelmann** [comment]
Thank you for pointing this out!

I think we can fix most (hopefully all) of the problems by implementing automatic type conversions within `compute_taxes_and_transfers` (independent of pystata).

Advantages:
- Automatic type conversion is also helpful for "usual" Python users
- We don't need to add pystata as a dependency of our package (I actually think that functions for conversions between stata, python, and other languages, shouldn't be part of GETTSIM. They might, however, be collected in a separate helper repository if there is demand for it)

In more detail, I suggest the following changes:
- Rename the function `check_if_series_has_internal_type` to `convert_series_to_internal_type`
- For each expected type, try to convert series to expected internal type.
- Throw a comprehensible exception if type conversion fails.
- Write a few tests that test whether type conversions are as expected and whether exception is thrown when conversion should not work.
