### ISSUE TITLE
Potential Bug in calculation of "Sonstige Vorsorgeaufwendungen"

### ISSUE THREAD

**Issue by michaelhebsaker** [iza-institute-of-labor-economics/gettsim#376]
### Bug description
In script: vorsorgeaufw.py  "Vorsorgeaufwendungen" are calculated. which are later needed for the calculation of a taxable income.
From my point of view, parts of the code are not correct. Let me discuss the following code snippet.

v. 0.5.0 code is:
```
def vorsorgeaufw_ab_2020(
...
sonstige_vors = 12 * (
            ges_pflegev_beitr_m
            + (1 - eink_st_abzüge_params["vorsorge_kranken_minderung"])
            * ges_krankenv_beitr_m
        )
        limit_below = sonstige_vors + 12 * arbeitsl_v_beitr_m
        limit_above = eink_st_abzüge_params["vorsorge_sonstige_aufw_max"]

        out = min(max(sonstige_vors, limit_below), limit_above)
```

From my point of view, there are two possible mistakes and I have one issue with the naming. Let me briefly explain myself:

1) Consider following line of code:
```
limit_below = sonstige_vors + 12 * arbeitsl_v_beitr_m
```
The scalar(?) **sonstige_vors** is used here. 
In the calculation of **sonstige_vors** only the "Basis GKV" is considered by:
```
 (1 - eink_st_abzüge_params["vorsorge_kranken_minderung"])
            * ges_krankenv_beitr_m
```
which is correct if you are exceeding the limit of 1900€ for a "abhangig beschäftigte" person. 
But it is not correct when it is used to calculate **limit_below**.
Please compare here the following quote.
"Ein Anspruch auf Krankengeld gehört jedoch nicht zum Basisschutz. Deshalb kürzt das Finanzamt bei Pflichtversicherten den Kran­ken­ver­si­che­rungsbeitrag pauschal um 4 Prozent. Dieser unberücksichtigte Betrag und die Beiträge für Wahlleistungen oder eine Aus­lands­kran­ken­ver­si­che­rung kannst Du nur dann als sonstige Vorsorgeaufwendungen geltend machen, wenn der Höchstbetrag von 1.900 Euro noch nicht ausgeschöpft ist." (see e.g. [Source1](https://www.finanztip.de/vorsorgeaufwendungen/), [Source2](https://www.haufe.de/steuern/finanzverwaltung/was-sind-sonstige-vorsorgeaufwendungen_164_417272.html). Of course much better would it be to give reference to EStG, but pretty sure the above mentioned sources are right in that case.)
The second part of the quote states that full payments of GKV should be included in **limit_below**.

2) Consider the following line of code:
```
out = min(max(sonstige_vors, limit_below), limit_above)
```

From my understanding of the code you are restricting **out**, to take no value larger than **limit_above**, which is here 1900€ for 
a "abhangig beschäftigte" person.

Please compare here the following quote.
"Zu den Sonderausgaben, die Du in **voller Höhe** von der Steuer absetzen kannst, gehören auch die Beiträge für Pfle­ge­ver­si­che­rung und Kran­ken­kas­se – aber nur die, die Dich auf sozialhilfegleichem Niveau absichern. Das ist die sogenannte Basiskrankenversicherung. Der von einer Kran­ken­kas­se erhobene Zusatzbeitrag zählt auch dazu" (see e.g. [Source1](https://www.finanztip.de/vorsorgeaufwendungen/), [Source2](https://www.haufe.de/steuern/finanzverwaltung/was-sind-sonstige-vorsorgeaufwendungen_164_417272.html). Of course much better would it be to give reference to EStG, but pretty sure the above mentioned sources are right in that case.)
From my point of view, the quote states that a Basiskrankenversicherung is fully deductible.

I personally don't like the coding of a nested min(max)) combination.

3) I want to discuss my issues with the naming. The naming here is from my point of view, not well aligned with the law termini.

Suggestions would be:
**sonstige_vors** -> **basiskrankenversicherung**

**limit_below** -> **sonstige_vors**

**limit_above** -> **max_sonst_vors**

### Expected behavior
1) leads to calculations of Vorsorgeaufwendungen, which are sligtly too low. Nothing dramatic, but still wrong for certain income intervals. For Single Households i would quess this is relevant for monthly incomes between 1200 and 1800€.

2) leads to calculations of Vorsorgeaufwendungen, which might be too low. For Single Households i would quess this is relevant for monthly incomes above 1800€ approx.

3) naming might help, to read code easier

Combining 1)-3): a suggestion for the code would be:

```
basiskrankenversicherung = 12 * (
            ges_pflegev_beitr_m
            + (1 - eink_st_abzüge_params["vorsorge_kranken_minderung"])
            * ges_krankenv_beitr_m
        )
        sonst_vors_max = eink_st_abzüge_params["vorsorge_sonstige_aufw_max"]
        sonst_vors = min(12 * (arbeitsl_v_beitr_m + ges_pflegev_beitr_m + ges_krankenv_beitr_m), sonst_vors_max)

        out = max(basiskrankenversicherung, sonst_vors)
```

I hope I got it right here...
Open for discussions.

**Comment by ChristianZimpelmann** [comment]
Thanks for pointing this out!

I am not an expert and I must say the sources are not easy to understand. But I think it makes sense. @mjbloemer, @JuergenWiemers, do you agree based on your implementations?

**Comment by m-pannier** [comment]
I am currently working on a revision of the "Vorsorge" code for the ifo-MSM. From my perspective, the comments about the potential mistakes made by @spreet41 do hold true. In addition, I consider the code suggestion by @spreet41 to be the right approach to solve these issues.

For the second point,

> From my understanding of the code you are restricting out, to take no value larger than limit_above, which is here 1900€ for a "abhangig beschäftigte" person.

I can also add a reference to the EStG, § 10 Abs. 4 Satz 4: "Übersteigen die Vorsorgeaufwendungen im Sinne des Absatzes 1 Nummer 3 die nach den Sätzen 1 bis 3 zu berücksichtigenden Vorsorgeaufwendungen, sind diese abzuziehen und ein Abzug von Vorsorgeaufwendungen im Sinne des Absatzes 1 Nummer 3a scheidet aus."

This quote in the EStG essentially confirms what the other sources had already hinted at.

**Comment by ChristianZimpelmann** [comment]
Thanks, @m-pannier! @spreet41, would you like to start a PR for this issue and implement the suggested changes?

If you have any questions, you can always contact me.
