### ISSUE TITLE
Set up a code of conduct.

### ISSUE THREAD

**Issue by tobiasraabe** [iza-institute-of-labor-economics/gettsim#39]
### Current and desired situation

Currently, we have no code of conduct. We want to have one.

### Proposed implementation

I have only skimmed some documents, but the scipy ecosystem seems to provide several examples.

- https://www.scipy.org/codes-of-conduct.html

### Considered alternatives

There is not alternative :).

**Comment by janosg** [comment]
After very superficial skimming I'm in favor of the Python Software Foundation Code of Conduct. Mainly because it is very skimming-friendly which increases the chances that people follow it. But any other from the list is also ok. I would then also use the same one for estimagic.

**Comment by tobiasraabe** [comment]
And it is probably the most discussed coc. If it is fine with you, @hmgaudecker, I would copy the sections our community and our standards and set up a document.

**Comment by hmgaudecker** [comment]
Closed via #46
