### ISSUE TITLE
Some tests are not strict enough

### ISSUE THREAD

**Issue by JuergenWiemers** [iza-institute-of-labor-economics/gettsim#391]
This is related to #389. As of now, four of our tests using `pandas.testing.assert_series_equal` use extremely relaxed tolerances, in particular `rtol=1`. These tests are: `test_eink_st`, `test_elterngeld`, `test_vorsorgeaufw`, `test_zu_verst_eink`.

What do I mean by "extremely relaxed"? Regarding the tolerance parameters `rtol` and `atol`, the [pandas documentation](https://pandas.pydata.org/docs/reference/api/pandas.testing.assert_series_equal.html) for `assert_series_equal` refers to the documentation of `math.is_equal` from the standard library [here](https://docs.python.org/3/library/math.html#math.isclose). According to the latter documentation, two numbers `a` and `b` are considered equal if

```python
abs(a-b) <= max(rtol * max(abs(a), abs(b)), atol)
```

is `True`. This implies that the test passes for `rtol=1` and arbitrarily small settings of `atol` as long as `a` and `b` have the same sign (if `a==0` then the comparison is true for all `b` and vice versa). 

Interpreting the condition above as a function of `a`, `b` for fixed parameters `rtol` and `atol`, the plotted "truth function" (with `True`interpreted as 1 and `False` as 0) looks like this (`rtol=1`, `atol=1e-8`):

![graph](https://user-images.githubusercontent.com/22220065/167816596-2ced1d5e-0a5b-4778-9881-f96895ee474e.jpg)

This is not how we want this function to look. Instead, we want the "truth function" to have this (stylized) shape (with `rtol=1e-1, atol=1e-1`, to make it more obvious what the parameters do): A narrow "ridge of truth", which gets a bit wider for larger (in absolute terms) values of `a` and `b` 

![graph2](https://user-images.githubusercontent.com/22220065/167831698-7aa673d5-ca2a-4de8-813e-b15b765650f1.jpg)

With `rtol=1`, e.g., 1000 and 0 are considered to be equal, which explains why the tests passed in #389 even though the calculated "ALG I" was completely wrong.

Try this:

```Python
import pandas as pd
from pandas.testing import assert_series_equal

a = pd.Series([0, 1000])
b = pd.Series([1000, 0])
c = pd.Series([0, -1000])

assert_series_equal(a, b, rtol=1, atol=1e-8)
assert_series_equal(b, c, rtol=1, atol=1e-8)

d = pd.Series([1e-3, 1000.0])
e = pd.Series([-1e-3, 1000.0])

assert_series_equal(d, e, rtol=1, atol=1e-8)
```

The first two tests pass, the third fails. 

Most (all?) outcome variables are non-negative by construction. Thus, using `rtol=1` in `test_eink_st`, `test_elterngeld`, `test_vorsorgeaufw`, and `test_zu_verst_eink` implies that these tests _cannot_ fail, which is probably not what we want. 😉  

The hard part is to find a more appropriate setting for `rtol`, which is likely test-specific. I tried to replace `rtol=1` with `rtol=1e-3`, which leads to 19 failing tests. Even a quite relaxed `rtol=1e-1` leads to a couple of failing tests. Anyway, simply changing `rtol` to a "reasonable value" is only part of the solution. We will also have to check why these tests fail for more appropriate settings of `rtol`.

**Comment by hmgaudecker** [comment]
Great catch!

General lesson: When developing tests, it is **extremely** important to try out cases that you expect to fail. E.g., tweak a test that should pass just a tiny bit.

This of course seems to be due to just a misinterpretation of what `rtol` does.

I think we want a very small `rtol` actually (none of our computations should lead to numerical errors). Best set it to zero. We can tune `atol` according to whatever is needed for rounding.

**Comment by hmgaudecker** [comment]
I'd still leave the default at zero. For most cases, we really should not expect any simulation error at all.

And we can always change it on a case by case basis if some particular test requires it.

Thanks!
