### ISSUE TITLE
rente für (besonders) langjährig Versicherte (inc. rente mit 63) 

### ISSUE THREAD

**Issue by TeBackh** [iza-institute-of-labor-economics/gettsim#395]
### Current and desired situation

Missing implementation of deduction free retirement of **very** **long** term insured (45+ years) -- "rente mit 63". Feature requested in issue #348. 

Missing implementation of deduction free earlier retirement for **long** term insured (35 years = very many people) ~ Regelaltersgrenze, which is relevant for cohorts pre 1953. --> full retirement age (FRA) < normal retirement age (NRA)

### Proposed implementation

-[ ] Add age thresholds for long term insured in ges_rente.yaml
-[ ] Add age thresholds for very long term insured
-[ ] implement function to determine eligibility
-[ ] change deductions function for eligible persons (zugangsfaktor)

**Comment by ChristianZimpelmann** [comment]
Sounds good!

But I am not sure about

> choose approximation for insurance years

Insurance years should be an input variable such that the user needs to make these approximations outside of GETTSIM.
