### ISSUE TITLE
Mindest­bei­trag ges.Krankenversicherung für haupt­be­ruf­lich Selb­stän­dige 

### ISSUE THREAD

**Issue by JHermann99** [iza-institute-of-labor-economics/gettsim#404]
### Current and desired situation

Currently when calculating the health insurance contributions for Selbstständige, the Beitragssatz is applied to the self employed income from -inf to the Beitragsbemessungsgrenze. This causes unwanted behaviour if the income is below zero, as a negative value is calculated for the health insurance contribution.

The real life implementation includes a [Mindestbeitrag](https://www.tk.de/techniker/leistungen-und-mitgliedschaft/informationen-versicherte/veraenderung-berufliche-situation/versichert-als-selbststaendige/haeufige-fragen-fuer-selbststaendige/hoehe-herleitung--mindestbeitrag-hauptberuflich-selbststaendige-2007008) for Selbstständige, which is calculated on the basis of a Mindesteinkommen on which the Beitragssatz is applied.

The Mindesteinkommen is [derived from](https://dejure.org/gesetze/SGB_V/240.html#Abs4:S1) the [Bezugsgröße](https://de.wikipedia.org/wiki/Bezugsgr%C3%B6%C3%9Fe). The Parameter Bezugsgröße already exists in GETTSIM. 

### Proposed implementation

To implement this, Mindesteinkommen has to be calculated. Then `max(mindesteinkommen, eink_selbst_m)` chooses if the Beitragssatz is applied to the Mindesteinkommen or the actual income.

**Comment by hmgaudecker** [comment]
Many thanks, sounds reasonable. Care to open a PR? Best would be to start from testcases with {negative, zero, positive but below mindesteinkommen} income and then implement a solution. Happy to help out.

I invited you to contribute to the repo, so you don't have create a PR from your fork but can work on a branch here directly.

**Comment by JHermann99** [comment]
Thanks, seems I was too quick with the forked PR. 
This is the code I tested the solution on: 

```
import pandas as pd
import numpy as np


from gettsim import set_up_policy_environment
from gettsim import compute_taxes_and_transfers

df = pd.DataFrame(index=[0,1,2,3])
df["p_id"] = [0,1,2,3]
df["hh_id"] = [0,1,2,3]
df["tu_id"] = [0,1,2,3]    
df["kind"] = False
df["bruttolohn_m"] = float(0)
df["alter"] = int(40)
df["rentner"] = False
df["alleinerz"] = False
df["wohnort_ost"] = False
df["in_priv_krankenv"] = False
df["in_ausbildung"] = False
df["selbstständig"] = True
df["hat_kinder"] = False
df["betreuungskost_m"] = float(0)
df["sonstig_eink_m"] = float(0)
df["eink_selbst_m"] = [-1000,0,1000,2000]
df["eink_vermietung_m"] = float(0) 
df["kapital_eink_m_tu"] = float(0)
df["kapitaleink_brutto_m"] = float(0)
df["bruttokaltmiete_m_hh"] = float(0)
df["heizkosten_m_hh"] = float(0)
df["wohnfläche_hh"] = int(100)
df["bewohnt_eigentum_hh"] = False
df["arbeitsl_monate_lfdj"] = int(0)
df["arbeitsl_monate_vorj"] = int(0)  
df["arbeitsl_monate_v2j"] = int(0)  
df["arbeitsstunden_w"] = int(0)
df["bruttolohn_vorj_m"] = df["bruttolohn_m"]
df["geburtstag"] = int(1)
df["geburtsmonat"] = int(1)
df["geburtsjahr"] = int(1970)
df["jahr_renteneintr"] = int(2030)
df["m_elterngeld"] = int(12)
df["m_elterngeld_vat"] = int(12)
df["m_elterngeld_mut"] = int(12)
df["behinderungsgrad"] = int(0)
df["schwerbeh_g"] = False
df["mietstufe"] = int(3)
df["immobilie_baujahr_hh"] = int(2005)
df["vermögen_hh"] = float(0)
df["entgeltp"] = float(0)
df["grundr_zeiten"] = int(0)
df["grundr_bew_zeiten"] = int(0)
df["grundr_entgeltp"] = float(0)
df["priv_rentenv_beitr_m"] = float(0)
df["priv_rente_m"] = float(0)

targets = [
    "ges_krankenv_beitr_m",
]

policy_params, policy_functions = set_up_policy_environment(2020)

result = compute_taxes_and_transfers(
    data=df,
    functions=policy_functions,
    params=policy_params,
    targets=targets,
)

result

```
