### ISSUE TITLE
Variable for number of claimed Kinderfreibeträge

### ISSUE THREAD

**Issue by JakobWegmann** [iza-institute-of-labor-economics/gettsim#407]
### Current and desired situation

Currently, the amount of Kinderfreibetrag (`eink_st_kinderfreib_tu`) is calculated based on the number of children with a claim on Kindergeld (`anz_kinder_mit_kindergeld_tu`) within the tax unit. So far, there exists no variable for the number of claimed Kinderfreibetrag. This is a problem as the claimed Kinderfreibetrag can be split up after divorce. 

When not provided as part of columns_overriding_functions, the variable `anz_kinder_mit_kindergeld_tu` is calculated in `aggregation_kindergeld` in `kindergeld.py` based on the number of children with the bool `kindergeld_anspruch` being equal to 1 and therefore only allows integers. 

### Proposed implementation

Implementing a new variable `anz_kinder_kinderfreib_tu`. 

The issue is strongly related to #379 as the exact implementation depends on the used "household concept" and the interaction between Unterhaltsvorschuss, Kindergeld and Kinderfreibetrag (see discussion [here](https://gettsim.zulipchat.com/#narrow/stream/309997-Taxes/topic/Kinderfreibetrag/near/288540326)).

**Comment by MImmesberger** [comment]
Closed via #676
