### ISSUE TITLE
Function out- and input variables

### ISSUE THREAD

**Issue by MaxBlesch** [iza-institute-of-labor-economics/gettsim#42]
### Current and desired situation

I added an module where all the function outputs are saved. We could do the same with all the input variables. Then we could call from the tax_transfer.py and the tests these variables and have an aligned structure.

### Proposed implementation

We could save the variable names in an extra module.

### Considered alternatives

- Save them in the config file.
- Create some yaml or json file.
- Save them next to the individual function code.

**Comment by hmgaudecker** [comment]
I do not understand yet. A link to that file would be good here. Thanks!

**Comment by hmgaudecker** [comment]
This is where my comment on #45 just came from... Is this still relevant?

**Comment by MaxBlesch** [comment]
Now the input and output columns are saved in tax_transfer and in the tests. 

If we later need this information for specifying the function input for cudf (at least, thats how I understood you) and for the checks if the necessary variables are there, we will have the same information in several places. I still think we should find one place for each information.(Right now I would prefer next to the functions in the according pyfiles) 

If this can wait or we are not going to do it at all, we can just close!

**Comment by hmgaudecker** [comment]
Eventually we will need to do it in some automated way, so let us close this for now.
