### ISSUE TITLE
Add Bürgergeld 2023

### ISSUE THREAD

**Issue by hmgaudecker** [iza-institute-of-labor-economics/gettsim#434]
Just a reminder, still in flux. But we'll need to be fast.

We could start by discussing how we will deal with renaming. That is, it looks like many things will be quite similar to `arbeitsl_geld_2` in the sense that the reform will be much smaller than `arbeitsl_hilfe` -> `arbeitsl_geld_2` back in the day. But names change quite strongly [draft of the law](https://dserver.bundestag.de/btd/20/038/2003873.pdf) has lots of parts like:

> In Satz 1 werden in dem Satzteil vor dem Semikolon die Wörter „Arbeitslosengeld II und Sozialgeld“ durch das Wort „Bürgergeld“ ersetzt.

**Comment by ChristianZimpelmann** [comment]
> We could start by discussing how we will deal with renaming.

Out options are:

- `keep `arbeitl_geld_2` and make notes that it is now called Bürgergeld
- rename everything to `bürgergeld` and make notes that it was called Arbeitslosengeld 2 until 2022.
- keep old functions and create new parameters, modules, and functions which exist from 2023 on (which are mostly duplicates of the existing ones, as far as I understand.

I think how important the renaming is, depends on how salient the new name will be in a few months. 

My proposal: Stick with Option 1 for now. Make a reminder to check in 6-12 months how prevalent the term Bürgergeld is used and potentially change to option 2 oder 3.

**Comment by hmgaudecker** [comment]
Just a lagged variable like for `arbeitsl_geld` (right?) should be fine. For now it'll be okay to focus on applications with annual periods, I think. Else people will need to construct in the data.

**Comment by ChristianZimpelmann** [comment]
So I guess `bürgerg_bezug_vorj`?

**Comment by hmgaudecker** [comment]
Sounds good!
