### ISSUE TITLE
Clearify definition and use of `sonstig_eink_m`

### ISSUE THREAD

**Issue by ChristianZimpelmann** [iza-institute-of-labor-economics/gettsim#438]
### Problem

 - The definition of `sonstig_eink_m` is currently unclear.
 - Therefore, it is not clear (at least for me) if the use in the code over different transfers is consistent.

### Current Use

  - The documentation describes it as "Additional income"
  - It is counted for `arbeitsl_geld_2`, `wohngeld` and `grunds_im_alter`
  - Conversely, it is not considered for the calculation of taxes and social insurance contributions
  
### ToDo

  - Write down clear definition
  - Check consistency over taxes and transfers
  
@Eric-Sommer @mjbloemer, do you have an idea what kind of income is meant?

**Comment by Eric-Sommer** [comment]
Thanks for bringing this up, @ChristianZimpelmann . 

If I recall correctly, introducing this income component helped align actual and simulated benefit recipients.

Digging into the old data preparation, `sonstig_eink_m` entails the following:
- Private transfers, e.g. alimony payments to spouse or child, and other private transfers.
- certain public transfers out of scope of then IZAMOD, such as maternity payments, social assistance for special circumstances, social assistance for elderly, Unterhaltsvorschuss, payments for war victims, unemployment assistance pre 2005, Bafög

They are not subject to income tax (although sometimes subject to Progressionsvorbehalt (see #126). However, they constitute regular income and thus may help avoiding ALG2 receipt.

A few of these items have become obsolete (e.g. Unterhalt and Unterhaltsvorschuss), but we might think about spitting this into 
- private transfers not subject to income taxation, but relevant for means-test
- public transfers **not simulated by gettsim** subject to Progressionsvorbehalt and relevant for means-test
- public transfer **not simulated by gettsim** and only relevant for means-test

These items would need to be documented accordingly. 

Alternatively, we could focus on the implementing the relevant items into gettsim (Bafög?) and leave only private transfers as additional input.

**Comment by ChristianZimpelmann** [comment]
Thanks, Eric! That makes sense!

I would then propose to adjust the description of the variables to sth like: 

"Additional income: includes private transfers and public transfers that are not yet implemented in GETTSIM (e.g. Bafög, Kriegsopferfürsorge)"

The implementation seems correct then (with the exception of Progressionsvorbehalt which is documented in #126)
