### ISSUE TITLE
ENH: Automate execution of notebooks as part of building the documentation

### ISSUE THREAD

**Issue by hmgaudecker** [iza-institute-of-labor-economics/gettsim#469]
#### Is your feature request related to a problem?

#466 reverted unwanted behavior introduced in #429 that turned up only when manually executing the notebooks for the documentation.

The ideal way would be to only ever commit empty notebooks and to execute things automatically when the documentation is built. Should be possible based on https://docs.jupyter.org/en/latest/running.html#using-a-command-line-interface

To do

- [ ] Figure out how to execute our notebooks from the command line
- [ ] Ideally, continue in case of errors in notebooks 
- [ ] Capture exceptions, continue in case of expected errors (e.g., advanced usage has some) but fail for unexpected ones
- [ ] Include as part of the documentation build
- [ ] Figure out whether there is a pre-commit hook removing the output from notebooks before committing.

Might be relevant for estimagic as well, so pinging @janosg @timmens in case they have ideas / suggestions / faced similar issues.

**Comment by janosg** [comment]
We had that in estimagic but always ran into resource constraints on readthedocs (already when building the conda environment) so we went back to manual building. But I think this has changed (conda uses less memory, readthedocs migh have better hardware) and I would like to revisit it. 

Executing the notebooks as part of the build is quite simple using [nbsphinx](https://nbsphinx.readthedocs.io/en/0.8.10/). 

Pre-commit hooks for removing notebook outputs also exist. E.g. [this one](https://github.com/roy-ht/pre-commit-jupyter).

**Comment by hmgaudecker** [comment]
Great, thanks! 

That was super-helpful and ) to implement. Means you earned yourself some work (quick review + https://github.com/OpenSourceEconomics/estimagic/pull/420) :innocent: 

Notes:
- Most actively developed hook seems to be [nbstripout](https://github.com/kynan/nbstripout#using-nbstripout-as-a-pre-commit-hook)
- Helpful link is to tag notebook cells with `raises-exception`: https://nbsphinx.readthedocs.io/en/0.8.10/allow-errors-per-cell.html
