### ISSUE TITLE
BUG: Parameters for "minimum child alimony" before 2016 are missing in "unterhalt.yaml"

### ISSUE THREAD

**Issue by JuergenWiemers** [iza-institute-of-labor-economics/gettsim#479]
Because of these missing parameters all simulations with 
```python
policy_params, policy_functions = set_up_policy_environment(2015)
```
and earlier years and at least one means-tested benefit as target fail with
```python
KeyError: 'mindestunterhalt'
```
on the current main branch. 

ToDo:

- [ ] Remove `unterhaltsvors_m` from test fixtures for `full_taxes_and_transfers` pre 2016. Currently there so that no error is raised.

**Comment by ChristianZimpelmann** [comment]
Thanks! This should be indeed fixed.

A difficulty will be to find the correct reference of the parameter as the [Mindestunterhaltsverordnung](https://www.buzer.de/1_Mindestunterhalt-Verordnung.htm#buildInHistory) is only available from 2016 on.

If I understand correctly, the parameter was based on the [Düsseldorfer Tabelle](https://www.olg-duesseldorf.nrw.de/infos/Duesseldorfer_Tabelle/Tabelle-2018/Duesseldorfer-Tabelle-2018.pdf) before. We should check whether it is also mentioned in a BGBl.

**Comment by hmgaudecker** [comment]
Thanks to both of you! 

IIRC, this would not be the only occasion where informal numbers were translated into law only at later date.

It seems easy enough to just get the first row of each year's Düsseldorfer Tabelle and to update [unterhalt.yaml](https://github.com/iza-institute-of-labor-economics/gettsim/blob/main/src/_gettsim/parameters/unterhalt.yaml) accordingly. 

However, this is unlikely to happen **very** soon (say a month ?) and if someone had numbers floating around for earlier years, a PR would be appreciated. 

If someone tackles this a couple of additional notes:
-  I find the mixing of operators in the keys (< vs <=: "*unter 6, unter 12, bis 17 Jahre*") confusing and would prefer 5 / 11 / 17 or 6 / 12 / 18
- Incidentally, it is 6 / 12 / 18 in `unterhaltsvors_altersgrenzen`, but these do not seem to be used anywhere and can be safely deleted, AFAICT

**Comment by JuergenWiemers** [comment]
> However, this is unlikely to happen **very** soon (say a month ?) and if someone had numbers floating around for earlier years, a PR would be appreciated.

Sorry, no time for a PR right now, but you can find the "Düsseldorfer Tabellen" all the way back to 1962 [here](https://www.dfgt.de/index.php?tid=66). 
Longer versions with table notes (but only back to 2005) can be found [here](https://www.olg-duesseldorf.nrw.de/infos/Duesseldorfer_Tabelle/).

> If I understand correctly, the parameter was based on the [Düsseldorfer Tabelle](https://www.olg-duesseldorf.nrw.de/infos/Duesseldorfer_Tabelle/Tabelle-2018/Duesseldorfer-Tabelle-2018.pdf) before. We should check whether it is also mentioned in a BGBl.

Hans-Martin is right, there was no legal basis for the minimum child alimony before 2016. The courts simply made up the "Düsseldorfer Tabellen" to fill that legal gap. 

Also note that between 1990 and 2007 the minimum child alimony in the new federal states and Berlin was determined by the "Berliner Tabellen" (also no legal basis). They were essentially identical to the "Düsseldorfer Tabellen", but they had two additional lowest income groups, which resulted in a lower minimum child alimony than in the old federal states. Unfortunately, Google didn't find me a nice archive for those tables. Here is an [example](https://www.olg-duesseldorf.nrw.de/infos/Duesseldorfer_Tabelle/Tabelle_2005/2005-07-01_Berliner-Tabelle.pdf).

**Comment by mjbloemer** [comment]
We only need this for Unterhaltsvorschuss, right? I don't think the Düsseldorfer Tabellen legally play a direct role for Unterhaltsvorschuss (or do they @ritter9 ?). As far as I understand it, the calculation of Unterhaltsvorschuss differed before 2016:

In general, Unterhaltsvorschuss is Mindestunterhalt according to § 1612a BGB minus Kindergeld for a first child ([§ 2 UVG](https://www.buzer.de/gesetz/2978/a42169.htm)).

- before 2016: Unterhaltsvorschuss is relative to sächliches Existenzminimum of the child (§ 1612a BGB). So it is just `sächl_existenzmin` part of Kinderfreibetrag minus Kindergeld1. No need for Mindestunterhalt parameters. Note that the younger age group as a factor of 0.87.

- from 2016 on, § 1612a (1) BGB still links to "steuerfrei zu stellenden sächlichen Existenzminimum" but has a new Verordnungsermächtigung in § 1612a (4) (note the change https://www.buzer.de/gesetz/6597/al51825-0.htm). Here the new Mindesunterhaltsverordnung with the fixed parameters comes in.

**Comment by JuergenWiemers** [comment]
@mjbloemer is right. I could have seen that by simply looking at our own model. 🙈 Yes, Unterhaltsvorschuss is unrelated to the Mindestunterhalt from the Düsseldorfer Tabelle, see [here](https://de.wikipedia.org/wiki/Unterhaltsvorschuss). Also, I guess we need an additional function for `unterhaltsvors_m` before 01.07.2017, because up to that time only children below 12 were entitled, see [here](https://www.bmfsfj.de/bmfsfj/aktuelles/alle-meldungen/ausweitung-des-unterhaltsvorschusses--113572).

**Comment by JuergenWiemers** [comment]
I also think the test for the Unterhaltsvorschuss for children aged 12 to 17 might be too strict, see [here](https://www.stmas.bayern.de/fibel/unterhaltsvorschuss.php#:~:text=Unterhaltsvorschuss%20wird%20auf%20Antrag%20gew%C3%A4hrt,Jahren%20h%C3%B6chstens%20314%20%E2%82%AC%20monatlich.), in particular:

> Vom 12. bis zur Vollendung des 18. Lebensjahres erhalten Alleinerziehende Unterhaltsvorschuss, wenn das Kind
>- im Inland bei einem seiner Elternteile lebt, der ledig, verwitwet oder geschieden ist oder von seinem Ehegatten oder Lebenspartner dauernd getrennt lebt,
>- nicht oder nicht regelmäßig Unterhalt von dem anderen Elternteil oder nach dessen Ableben oder dem Ableben eines Stiefelternteils keine Waisenbezüge in einer bestimmten Mindesthöhe erhält und
>- keine Leistungen nach dem Sozialgesetzbuch II bezieht _oder_
>- durch den Unterhaltsvorschuss die Hilfebedürftigkeit des Kindes vermieden werden kann _oder_
>- der betreuende Elternteil über Einkommen von mindestens 600 € verfügt.

Note the "or"s connecting the last three bullet points. Looking at `unterhaltvors_m`, it seems we only consider a child from 12 to 17 to be entitled only if the gross wage of the single parent is higher than 600€:

https://github.com/iza-institute-of-labor-economics/gettsim/blob/62188ae8ee91cdb0d7f89570f12eff35ee3bdf62/src/_gettsim/transfers/unterhalt.py#L60-L72

**Comment by mjbloemer** [comment]
One reason the SGB II condition has not been modelled correctly might be that Unterhaltsvorschuss is essentially deducted from ALG II (or included as relevant income for ALG II just like Kindergeld). Actually, this sounds a bit like another Günstigerprüfung (or Vorrangigkeitsprüfung as UV is *vorrangig*, I think § 12a SGB)). However, I'm not sure how relevant this is.

**Comment by mjbloemer** [comment]
I implemented the years 2009 to 2015 in https://github.com/iza-institute-of-labor-economics/gettsim/pull/790 which will close this issue.

@JuergenWiemers: Could you make a separate issue out of your [comment on the other conditions for the older age group for the policy environment from 2017-07](https://github.com/iza-institute-of-labor-economics/gettsim/issues/479#issuecomment-1377742006)?
