### ISSUE TITLE
Remove `grouped_cumsum`, used for `kindergeld`

### ISSUE THREAD

**Issue by hmgaudecker** [iza-institute-of-labor-economics/gettsim#482]
We are deliberately ignoring the error that `grouped_cumsum` is deprecated. Plus, we do not have an implementation for Jax.

Currently it is only being used to aggregate `kindergeld_anspruch` to the tax unit level, we will need to think of a different way of doing that, probably while working on #379.

**Comment by MImmesberger** [comment]
Done in #694
