### ISSUE TITLE
BUG: Take care of flake8-bugbear B028 error

### ISSUE THREAD

**Issue by ChristianZimpelmann** [iza-institute-of-labor-economics/gettsim#489]
### Bug description

In several PR's (e.g. #458), pre-commits fail due to [this](https://github.com/PyCQA/flake8-bugbear/commit/ef39e9a1b5306393ce42ea231d3174449a929c81) change in `flake8-bugbear`.

> **B028**: Consider replacing ``f"'{foo}'"`` with ``f"{foo!r}"`` which is both easier to read and will escape quotes inside ``foo`` if that would appear.

### Two options how to fix

- Make changes in code base as suggested.
- Ignore error **B028**

**Comment by hmgaudecker** [comment]
I kind of like the suggestion that is made (and learned about new syntax). But also fine with ignoring for the moment, which is probably better.

In general, we should harmonize hooks across projects and my plan would be to use the all-new setup from estimagic for the hook settings. However, for comparing setups we should have yaml linting set to the same options in both projects and so far, there is none in estimagic (see [here](https://github.com/OpenSourceEconomics/estimagic/issues/426)).
