### ISSUE TITLE
ENH: Add information when certain reforms were introduced

### ISSUE THREAD

**Issue by ChristianZimpelmann** [iza-institute-of-labor-economics/gettsim#491]
#### Is your feature request related to a problem?

Regelaltersrente (NRA) is in `ges_rente.yaml` constant after 1984 (only dependend on birth year).

In reality, that regime seems only be in place from 2007 on.

For the calculation of actual pensions this doesn't matter, but it is relevant when somebody wants to look at expected retirement ages of subjects.

Also: Check pension functions whether `dates_active`-decorators are needed.

**Comment by hmgaudecker** [comment]
Another example would be Vorsorgeaufwendungen, originally set on a path to a new regime 2005-2025. There was a discrete change announced in 2022, that the last three years of the transition would happen more quickly, so the new regime would be in place already in 2023. Implemented in #476.

Not sure how much of that we want to have in here, but for forward-looking agents in 2020 this definitely was not to be expected with 100% certainty...

**Comment by hmgaudecker** [comment]
Another example would be to change the interface of the functions determining age eligibility rules in the pensions case so that discussions like this https://github.com/iza-institute-of-labor-economics/gettsim/pull/428#discussion_r1088075001 don't come up.
