### ISSUE TITLE
BUG: Introductory phase of Rente für besonders langjährig Versicherte is imprecise

### ISSUE THREAD

**Issue by TeBackh** [iza-institute-of-labor-economics/gettsim#493]
### Bug description

Imprecise parameter input of Rente für besonders langjährig Versicherte. Unnecessary part in the parameter definition

- [x] Set age to 63 for all cohorts before 1953 from 1.7.2014

**Comment by hmgaudecker** [comment]
Thanks! I must admit that I do not quite follow. Can you elaborate a little on which parameter is imprecise and what is the proposed solution?

**Comment by TeBackh** [comment]
Since 1st of July 2014 all cohorts up to cohort 1952 could claim the pension for very long term insured with 63 instead of 65. Since the people born before 1.7.1949 were already 65 by then they were not affected and the people born between 1.7.1949 and 1.7.1951 could not retire with 63 because they had some age between 63 and 65 by the time of introduction. In the previous set up this mechanical "gradual "  reduction  in the retirement age that is caused by the introduction date was explicitely written in the parameter setup, which was unnecessary since the introduction date should do the job alone. and further we only incorporated a decrease from cohort 1950 and not from 1949.5 (which was "inprecise" or basically wrong).
-- and it was my own bug -- I fix it

**Comment by hmgaudecker** [comment]
Cool, thanks! 

Hold on a bit until we have the new structure with time-varying functions in place. The possibility to retire for that reason simply should not be there before 2014-07-01, implementing that will be natural fairly soon. Age should not play a role then (other than being in the window $[63, 65)$ )

**Comment by TeBackh** [comment]
I had done it already, was only fighting with the pre commit hooks. (Laura's tests depend on it , thats why I wanted to fix it quickly)
