### ISSUE TITLE
BUG: Revise ALG 2 Regelsatz for adult children

### ISSUE THREAD

**Issue by ChristianZimpelmann** [iza-institute-of-labor-economics/gettsim#499]
### Bug description

Regelsatz for children (`arbeitsl_geld_2_kindersatz_m_hh_ab_2011`) is currently calculated as:

```
    # Sum payments for each age group
    out = (
        arbeitsl_geld_2_params["regelsatz"][6] * anz_kinder_bis_6_hh
        + arbeitsl_geld_2_params["regelsatz"][5] * anz_kinder_ab_7_bis_13_hh
        + arbeitsl_geld_2_params["regelsatz"][4] * anz_kinder_ab_14_bis_24_hh
    )
```
However, Regelbedarfsstufe seem to be only relevant until the age of 18. For older children, Regelsatz 3 is relevant if I am not mistaken. See:

- [§ 20 V SGB II.](https://www.gesetze-im-internet.de/sgb_2/__20.html#:~:text=%C2%A7%2020%20Regelbedarf%20zur%20Sicherung,pers%C3%B6nliche%20Bed%C3%BCrfnisse%20des%20t%C3%A4glichen%20Lebens.)
- [Wikipedia](https://de.wikipedia.org/wiki/Regelbedarf)

@Eric-Sommer, @mjbloemer, can you confirm this?

**Comment by Eric-Sommer** [comment]
I agree 👍 . I have no idea why it's implemented this way.
