### ISSUE TITLE
Convert to a useful structure as installable package

### ISSUE THREAD

**Issue by hmgaudecker** [iza-institute-of-labor-economics/gettsim#5]
- Waf / https://github.com/hmgaudecker/econ-project-templates are still a leftover from the days where we were thinking along the lines of a joint taxes/transfers + behavioural model.
- Need to discuss this first

**Comment by hmgaudecker** [comment]
@tobiasraabe, @MaxBlesch: With #25 on the way, we should actually get this done more quickly. Seems fairly straightforward, too. Basically, get rid of the src/{analysis, data_management, ...} layer and move everything into subfolders gettsim/tests, right? Waf can go completely and we may just need to specify the dependencies as opposed to a full conda environment. Thoughts?

**Comment by tobiasraabe** [comment]
Just two thoughts for the moment.

- You can decide whether you want to ship the tests with the package or have them outside.
- If numba is a dependency, this can never be a pip package. Uploading it on anaconda.org is always possible and we can copy the recipes from estimagic or respy. Thanks to ``@janosg``.

**Comment by hmgaudecker** [comment]
1. It never hurts to send them along.
2. Conda is enough indeed.

Re 1., one tricky thing is how to make it easy for users to implement reforms without touching the source of the package and at the same time make it easy to create a pull request for that...

**Comment by tobiasraabe** [comment]
If I understand you correctly, the last point was also one of the main talking point in Janos' presentation with the computer scientists, right? We should start a separate issue where we discuss the advantages and disadvantages of providing an API for custom functions, use monkey patching or something different. Or do you already have a plan and I missed it?

I think if users come up with a custom function, they already understand something of the inner workings of ``gettsim``. It is probably very local knowledge, but with the help of a maintainer, they might become a full contributor next time.

**Comment by hmgaudecker** [comment]
> If I understand you correctly, the last point was also one of the main talking point in Janos' presentation with the computer scientists, right? We should start a separate issue where we discuss the advantages and disadvantages of providing an API for custom functions, use monkey patching or something different. Or do you already have a plan and I missed it?

No, you did not. And you are right, of course, that this is, of course a much bigger fish than to be handled in this issue. 

> I think if users come up with a custom function, they already understand something of the inner workings of `gettsim`. It is probably very local knowledge, but with the help of a maintainer, they might become a full contributor next time.

Yes, the way I envision this is that there will be all kinds of reforms that are being contemplated and put into code. Not many of them will make it into the core package. But it should be easy to put them online somewhere eventually make them part of the package.

**Comment by hmgaudecker** [comment]
So, @tobiasraabe, would you mind just going ahead with this? Something like:
```
git tag final_version_with_waf
git mv src/analysis/tax_transfer.py gettsim
git mv src/analysis/tax_transfer_functions gettsim
git rm -rf src .mywaflib waf.py
```
And then adjust setup and tests?

**Comment by tobiasraabe** [comment]
Yes. Should I include the upload to Anaconda in the same PR?

**Comment by hmgaudecker** [comment]
Sure, why not? We should create a gettsim account there, I suppose.

Tobias Raabe <notifications@github.com> schrieb am Mo., 30. Sep. 2019,
13:40:

**Comment by tobiasraabe** [comment]
If you have a personal account, then I can just create an organization called gettsim and give us admin rights. Or do you want the organization be called something similar to iza which is already occupied.

**Comment by hmgaudecker** [comment]
hmgaudecker. Let"s call it gettsim. Thanks!
