### ISSUE TITLE
Monetary unit of parameters and data set

### ISSUE THREAD

**Issue by mjbloemer** [iza-institute-of-labor-economics/gettsim#52]
> > > I think every monetary value in param.xls is currently in Euro; DM values are converted to Euro (which makes it just a little bit harder when comparing to the written law).
> > 
> > 
> > Perfect. I have no strong opinion on whether we want to convert those values now, but eventually DM would seem to make more sense to me.
> 
> There is one exception, namely the tax tariff parameters before 2002. The others are in Euro; initially because SOEP delivers all incomes in Euro as well. I'd prefer to sticking to Euro all the way. If you do a long-term analysis, you'd report in Euro anyway. It's easier to convert incomes rather than parameters, as there are lots of parameters (shares) which must not be converted.

I think we are on the same page in the sense that internally, we will do everything in Euros. 

I disagree on parameters being more difficult to convert. That may be the case in Stata if you have to store all these animals in macros, but here? 

```python
def convert_dm_to_euro(dm):
    return dm / 1.95583

if unit == "Euro":
    val = raw_val
elif unit == "DM":
    val = convert_dm_to_euro(dm)
else:
   raise ValueError(f"Monetary Unit unknown: {raw_val}")
```

So this is only about how to store the input parameters and I think the idea of sticking close to the law is good there. As I wrote previously, whether we want to do that right away or do that at some later point (please open an issue in that case once we close this one, @mjbloemer lest we forget) I do not care much.

What we want to support in terms of input data is a wholly different question.

_Originally posted by @hmgaudecker in https://github.com/iza-institute-of-labor-economics/gettsim/issues/31#issuecomment-547781434_

**Comment by Eric-Sommer** [comment]
Related to this: It might be worth to indicate whether a parameter is monetary or a (percentage) share or something else (e.g. an a age threshold)

**Comment by hmgaudecker** [comment]
Also see the discussion here: https://gettsim.zulipchat.com/#narrow/stream/212222-general/topic/param/near/180365079

**Comment by Eric-Sommer** [comment]
do we want to add this dimension in #148?

**Comment by hmgaudecker** [comment]
Yes, I would say so. Can you add a note or start drafting a section there, enumerating the possible options?

**Comment by hmgaudecker** [comment]
Might be a good thing for an RA not great in Python. @MaxBlesch, pls. keep in mind for 23/7

**Comment by hmgaudecker** [comment]
General thing is addressed in [GEP 3](https://gettsim.readthedocs.io/en/latest/geps/gep-03.html), for specific conversions we should open individual issues.
