### ISSUE TITLE
BUG: need for feasible retirement ages in ges_rente.yaml

### ISSUE THREAD

**Issue by TeBackh** [iza-institute-of-labor-economics/gettsim#535]
### Bug description

Parameter definition for retirement ages need to represent the actually feasible retirement ages (instead of those written in the law. )

- [ ] fix thresholds in ```altersgrenze_besonders_langj_versicherte:```

**Comment by hmgaudecker** [comment]
Thanks! Just to be sure, we should fix this as part of PR #428 since the correct (I believe) tests are already in place now.
