### ISSUE TITLE
ENH: Class for policy functions

### ISSUE THREAD

**Issue by lars-reimann** [iza-institute-of-labor-economics/gettsim#538]
#### Is your feature request related to a problem?

Users can attach additional information to policy functions using decorators, which provides a nice interface for them to work with. Often, we cannot immediately transform the decorated function, however, so we need to store the arguments of the decorator somewhere. Since decorators can be applied in any order and can potentially wrap a function, adding a property to the decorated function and ensuring it gets carried along is the best solution. Currently, this data is stored in a dictionary called  [`__info__`](https://github.com/iza-institute-of-labor-economics/gettsim/pull/534).

Once, all decorators are processed, however, the dictionary is cumbersome to work with:
1. We need to ensure the dictionary exists, which is not the case for functions without decorators.
2. We need to ensure specific keys exist before accessing them or provide default values.
3. Any logic needs to be defined externally (e.g. we cannot just ask a policy function whether it is active at a given date).

#### Describe the solution you would like to see

Once all decorators are processed, create an instance of the following class:

```py
class PolicyFunction:
    def __init__(
        self,
        f: Callable,
        dag_key: str,
        start_date: datetime.date,
        end_date: datetime.date
    ):
        ...

    def is_active_at_date(date: datetime.date) -> bool:
        ... 
```

Any code downstream should work with policy functions instead of normal Python callables.

If https://github.com/OpenSourceEconomics/dags/issues/13 gets implemented, `PolicyFunction` could also extend `DagFunction` and pass the dag_key along to the super constructor.

#### Interface breaking implications

Only changes how we internally work with policy functions.

#### Additional context

Discussion started [here](https://github.com/iza-institute-of-labor-economics/gettsim/pull/534#discussion_r1109684925).

**Comment by hmgaudecker** [comment]
Fixed by #787.
