### ISSUE TITLE
ENH: Add Kindesunterhalt

### ISSUE THREAD

**Issue by ChristianZimpelmann** [iza-institute-of-labor-economics/gettsim#541]
#### Is your feature request related to a problem?

GETTSIM does not consider alimony payments of a parent outside the household -- only Unterhaltsvorschuss which is payed to all single parents.

####  ToDo:

- Add new input variable `kindesunterhalt_m`
- Pay Unterhaltsvorschuss only if no (or not enough?) `kindesunterhalt`
- consider `kindesunterhalt` everywhere where we currently consider `unterhaltsvors_m`

**Comment by hmgaudecker** [comment]
Why would we need to call it **`kindes`**`unterhalt_m` ? Should it not be obvious because the variable is at the individual level and attached to a child? I do not see yet why we would need a separate variable for ex-partners.

**Comment by ChristianZimpelmann** [comment]
Since child alimony can be also payed for individuals older than 18, there might be subject that receive both kind of alimony payments. When working on this issue, we should check whether we need to differentiate

**Comment by hmgaudecker** [comment]
You mean parents divorced, I got married at 18, divorced at 20, move back in with my mom, attend school, and my ex-partner and father both need to pay alimony? I'd say that by the time a court has decided on what my ex-partner needs to pay, I've reached age 25.

**Comment by ChristianZimpelmann** [comment]
Could very well be. But we still need to find out whether we need to know which kind of alimony payments it is. Just based on the age of the recipient, we cannot be sure in some cases.

**Comment by ChristianZimpelmann** [comment]
Important will be to take into account child benefit which is payed to the parent with whom the child lives, but the other parent can deduct half of it from alimony payments.

**Comment by hmgaudecker** [comment]
> Could very well be. But we still need to find out whether we need to know which kind of alimony payments it is. Just based on the age of the recipient, we cannot be sure in some cases.

Alright, good point. Let's just stick to two variables `kindesunterhalt_m` and `partner_unterhalt_m` then. Explicit is better than implicit and this makes it clear what we are talking about.

> Important will be to take into account child benefit which is payed to the parent with whom the child lives, but the other parent can deduct half of it from alimony payments.

We'll definitely need two variables, maybe `kindesunterhalt_brutto_m` and `kindesunterhalt_netto_m` for that. In most datasets (asking the single parent how much she receives; records of the actual payments), you would never see the gross version. Different for court records or in example households.
