### ISSUE TITLE
Remove some cruft and set up coverage statistics

### ISSUE THREAD

**Issue by hmgaudecker** [iza-institute-of-labor-economics/gettsim#58]
A look at the coverage statistics reveals that:

* Not surprisingly, `release.py` and `setup.py` have zero coverage: https://codecov.io/gh/iza-institute-of-labor-economics/gettsim. @tobiasraabe, is it possible to tell codecove.io to focus on the gettsim subfolder? Is there anything outside of that folder that we would want to know about?
* In the gettsim folder, only auxiliary.py has some missing stuff: https://codecov.io/gh/iza-institute-of-labor-economics/gettsim/src/master/gettsim/auxiliary.py. @MaxBlesch @Eric-Sommer @mjbloemer:
  * Can we just delete the uprate function?
  * Can we delete the "adult_married" *unit* ?

**Comment by MaxBlesch** [comment]
If there is not a real reason to keep the uprate functio, I will open a PR and submit a suggestion to remove auxiliary.py.

**Comment by Eric-Sommer** [comment]
For now, we can put the uprating aside. In practice, it is pretty important if data year and policy year differ. But this can be easily re-implemented.

`adult_married` is now defined within the functions where it is needed and can also be discarded.

**Comment by mjbloemer** [comment]
I have the impression that every uprating of monetary variables of the input data set should be done on the data preparation side.

**Comment by MaxBlesch** [comment]
Removed auxiliary.py with #59

**Comment by MaxBlesch** [comment]
This can be closed?

**Comment by hmgaudecker** [comment]
Closed via #59 and #64
