### ISSUE TITLE
ENH: new Pflegeversicherung regime from 2023-07-01

### ISSUE THREAD

**Issue by Eric-Sommer** [iza-institute-of-labor-economics/gettsim#595]
The contribution rate for elderly care is going to increase on 2023-07-01 ([draft](https://dserver.bundestag.de/btd/20/069/2006983.pdf))

Moreover, the top-up is going to be changed. So far, every adult above 23 without children has to pay a top-up *unless* he/she receives *Bürgergeld*  (not sure we have that covered already). Now, the top-up rate is reduced by the number of children, starting with the second child. More importantly, children are only considered until they are 25. See also [here](https://www.iwkoeln.de/fileadmin/user_upload/Studien/Kurzberichte/PDF/2023/IW-Kurzbericht_2023-Pflegeversicherungsbeitrag.pdf).

- [ ] check whether we exempt receivers of Bürgergeld
- [ ] implement new top-up regulation

**Comment by hmgaudecker** [comment]
Good catch that #593 needs an associated issue :wink:

**Comment by Eric-Sommer** [comment]
👍 I only searched through the issues, not the PRs 😁
