### ISSUE TITLE
ENH: API redesign

### ISSUE THREAD

**Issue by hmgaudecker** [iza-institute-of-labor-economics/gettsim#596]
A collection of ideas, some to be implemented before a version 1.0

Currently:

1. Set up policy environment
2. Compute taxes and transfers

Desired: Two options

1. One-stop-shop
2. Much more fine-grained exposure

E.g., the behavior of `columns_overriding_functions` has stopped making much sense now that we have automatic aggregation / time unit conversion (see [discussion in #583](https://github.com/iza-institute-of-labor-economics/gettsim/pull/583#issuecomment-1611845663)). Should become much more obvious once we set up the environment taking into account the structure of the data.

**Comment by ChristianZimpelmann** [comment]
seems like a duplicate of #378

**Comment by hmgaudecker** [comment]
Indeed, thanks! I did have in mind we had come up with something, but searched only for "API"...
