### ISSUE TITLE
BUG: Add Elterngeld maximum income threshold

### ISSUE THREAD

**Issue by ChristianZimpelmann** [iza-institute-of-labor-economics/gettsim#599]
### Bug description

- Elterngeld is not payed out if income of parents is above some income threshold. See [§ 1 Absatz 8 BEEG](https://www.gesetze-im-internet.de/beeg/__1.html):

> Ein Anspruch entfällt, wenn die berechtigte Person im letzten abgeschlossenen Veranlagungszeitraum vor der Geburt des Kindes ein zu versteuerndes Einkommen nach § 2 Absatz 5 des Einkommensteuergesetzes in Höhe von mehr als 250 000 Euro erzielt hat. Erfüllt auch eine andere Person die Voraussetzungen des Absatzes 1 Satz 1 Nummer 2 oder der Absätze 3 oder 4, entfällt abweichend von Satz 1 der Anspruch, wenn die Summe des zu versteuernden Einkommens beider Personen mehr als 300 000 Euro beträgt.

- There seem to have been several changes through the last years: https://www.elterngeld.net/einkommensgrenzen.html#:~:text=Einkommensgrenzen%20beim%20Elterngeld&text=F%C3%BCr%20Elternpaare%20entf%C3%A4llt%20der%20Elterngeldanspruch,Euro%20hatten%20(%C2%A7%201%20Abs.
- The threshold is supposed to be lowered further: https://www.spiegel.de/politik/deutschland/bundesregierung-kuerzt-beim-elterngeld-a-ee9c4dd6-094a-41da-9a69-7ee604a79f83

**Comment by MImmesberger** [comment]
Closed via #756
