### ISSUE TITLE
ENH: Add automated test for synthetic data to make sure default targets can be created based on it.

### ISSUE THREAD

**Issue by ChristianZimpelmann** [iza-institute-of-labor-economics/gettsim#611]
#### Is your feature request related to a problem?

When introducing a new input variable it [can happen](https://github.com/iza-institute-of-labor-economics/gettsim/pull/603) that we forget to include the variable in `synthetic.py`.

#### Describe the solution you would like to see

Add automated test which:
- uses synthetic.py to create a dataset
- runs `compute_taxes_and_transfers` with default targets

**Comment by MImmesberger** [comment]
Closed because this duplicates #733
