### ISSUE TITLE
ENH: Taking the month of retirement into account for pension benefit calculation

### ISSUE THREAD

**Issue by MImmesberger** [iza-institute-of-labor-economics/gettsim#612]
#### Is your feature request related to a problem?

Currently, the `ges_rente_zugangsfaktor` function only considers the year of retirement and compares it to the year of birth. Hence, in the current implementation, individuals that retire early or late are treated as if they retired 0, 12, 24,... months before or after the statutory retirement age threshold.

The calculation of the Zugangsfaktor should be sensitive to the month of retirement. The calculation of pension benefits depends on how many months early or late the person retires.

#### Describe the solution you would like to see

The current implementation of the statutory retirement age thresholds is already based on the month of birth. The only missing part is probably the correct calculation of the Zugangsfaktor.

**Comment by TeBackh** [comment]
Variables ``geburtsmonat`` and ``geburtstag`` (probably $\in \[1,31\]$) are already input variables (``config.py`` line 130, 131), so even day precision should work.
