### ISSUE TITLE
Convert test data to yaml.

### ISSUE THREAD

**Issue by tobiasraabe** [iza-institute-of-labor-economics/gettsim#62]
### Current and desired situation

- The tests require ods-files which can only be read with a pip package which blocks making gettsim conda installable. #61 
- We have five data formats (csv, json, yaml, ods, xlsx). json can be replaced with yaml.
- Consider to tackle #63 along the way.

### Proposed implementation

*Discussing*

### Considered alternatives

*Discussing*

**Comment by tobiasraabe** [comment]
@MaxBlesch @mjbloemer Hi Maximilans, can we simply convert ods to csv? Do we need the ods, but keep duplicated csvs for the tests? You definitely have a better overview. What are your thoughts?

**Comment by mjbloemer** [comment]
I have never looked at the test data and I have actually no idea how that works. So I have no opinion on that.

My gut feeling is that it should be csv. yaml was for the params especially because of the structure.

**Comment by tobiasraabe** [comment]
@mjbloemer I am sorry for pinging you. I thought you have already worked on that, but @MaxBlesch just told me that I was mistaken.

**Comment by hmgaudecker** [comment]
That was my suggestion actually because I thought you had some code for converting Excel to YAML. But csv sounds reasonable for a table structure.

**Comment by Eric-Sommer** [comment]
As I mentioned earlier (#31), I have a strong preference for keeping `ods` along with `csv`. Our tests are pretty complicated. Infact, most tests I set up fail initially because the test is wrong. I just created a new test by copying one from existing rows and building on top of that. Without the formulas, one would need to start from scratch and possibly repeat the same mistakes.

**Comment by MaxBlesch** [comment]
I agree for different reasons with Eric and would like for now to keep the sheets as well. I suggest a subfolder in test_data called formula sheets, where we keep the ods files. In the test_data folder we keep just csv files. If all agree I would set this up and adapt the code.

**Comment by hmgaudecker** [comment]
Fine. We just do not want to have an ods dependency because of the way we develop our tests. 

Sounds like doing that in Python/Pandas would be the better way to go, though, if the formulas are important.

**Comment by MaxBlesch** [comment]
I would open a separate issue for that and just do the discussed way first. Then we can upload to Anaconda!

**Comment by Eric-Sommer** [comment]
> Sounds like doing that in Python/Pandas would be the better way to go, though, if the formulas are important.

True, but then you test python code with python code.
