### ISSUE TITLE
BUG: Deactivated functions are used by `compute_taxes_and_transfers`

### ISSUE THREAD

**Issue by ChristianZimpelmann** [iza-institute-of-labor-economics/gettsim#626]
### Bug description

In #618, the functions `abgelt_st_y_tu` is made available only from 2009 on. However, in 2008 you can still request `abgelt_st_y_tu` without recieving an error. While `abgelt_st_y_tu` is not part of `policy_functions`, when calling `compute_taxes_and_transfers`, GETTSIM seems to collect the function from `PATHS_TO_INTERNAL_FUNCTIONS`

Interestingly, I get an error as expected if the `change_name` attribute is used in the decorator:

```python
@dates_active(start="2009-01-01", change_name="abgelt_st_y_tu")
def abgelt_st_y_foo_tu(zu_verst_kapitaleink_y_tu: float, abgelt_st_params: dict) -> float:
    pass
```

### Proposed solution

Is there any reason functions from `PATHS_TO_INTERNAL_FUNCTIONS` are still collected in `compute_taxes_and_transfers` instead of just having all active functions in `policy_params`?

**Comment by hmgaudecker** [comment]
Thanks for the report!

> Interestingly, I get an error as expected if the `change_name` attribute is used in the decorator

You mean, when calling `compute_taxes_and_transfers` and requesting `abgelt_st_y_tu` as a target? And no error if the change_name keyword is not present?

**Comment by ChristianZimpelmann** [comment]
Yes, I call `compute_taxes_and_transfers` and request `abgelt_st_y_tu` (which should be only active from 2009 on) for a year before 2008.

If there exists a function `abgelt_st_y_tu` in the code base, I do not get an error.
If there exists a function `abgelt_st_y_foo_tu` in the code base whose name is changed by date_active decorator, I do get an error as expected.

**Comment by hmgaudecker** [comment]
@lars-reimann, could you have a look at this one, please?
