### ISSUE TITLE
Add ALG II transfer withdrawal 2005-01-01 to 2005-09-30

### ISSUE THREAD

**Issue by mjbloemer** [iza-institute-of-labor-economics/gettsim#66]
Check accurate modelling before 2005-10-01. Add parameter source and notes.

Just a collection of notes here:
-  § 11 b since 2011 (amendment by [B. v. 13.05.2011 BGBl. I S. 850](https://offenegesetze.de/veroeffentlichung/bgbl1/2011/23#page=2), [Artikel 2 G. v. 24.03.2011 BGBl. I S. 453](https://offenegesetze.de/veroeffentlichung/bgbl1/2011/12#page=5)) this changed `a2eg1`.  [~~Berichtigung der Bekanntmachung der Neufassung des Zweiten Buches Sozialgesetzbuch is just a typo~~](https://offenegesetze.de/veroeffentlichung/bgbl1/2011/53#page=14), see also https://www.buzer.de/gesetz/12141/a200124.htm
- before 2011 and § 11b, in § 30? See https://www.buzer.de/gesetz/2602/al27368-0.htm and original see [G. v. 24.12.2003 BGBl. I S. 2954 (Viertes Gesetz für moderne Dienstleistungen am Arbeitsmarkt, in force 2005-01-01)](https://offenegesetze.de/veroeffentlichung/bgbl1/2003/66#page=44) and [Gesetz zur Neufassung der Freibetragsregelungen für erwerbsfähige Hilfebedürftige (Freibetragsneuregelungsgesetz), in force 2005-10-01](https://offenegesetze.de/veroeffentlichung/bgbl1/2005/49#page=55)
- see also [§ 67](https://www.sozialgesetzbuch-sgb.de/sgbii/67.html) on 2005-01-01 to 2005-09-30 rule

**Comment by Eric-Sommer** [comment]
this can be closed now, right?

**Comment by mjbloemer** [comment]
> this can be closed now, right?

not yet. Maybe with #87.
