### ISSUE TITLE
ENH: Remove hard-coding of SGB II age groups

### ISSUE THREAD

**Issue by hmgaudecker** [iza-institute-of-labor-economics/gettsim#668]
#### Is your feature request related to a problem?

`arbeitsl_geld_2_kindersatz_m_hh_ab_2011` currently does:

```py
        arbeitsl_geld_2_params["regelsatz"][6] * anz_kinder_bis_5_hh
        + arbeitsl_geld_2_params["regelsatz"][5] * anz_kinder_ab_6_bis_13_hh
        + arbeitsl_geld_2_params["regelsatz"][4] * anz_kinder_ab_14_bis_17_hh
        + arbeitsl_geld_2_params["regelsatz"][3] * anz_kinder_ab_18_bis_24_hh
```

Similarly, #582 introduced hard-coded `25`s in `groupings.py`

#### Describe the solution you would like to see

Include mappings of `regelbedarfsstufen` to min/max ages. In the above code snippet, work at the individual level.

**Comment by MImmesberger** [comment]
In this context, I'm wondering how we understand the relation of `alleinerz` and the Einstandspartner. Does `p_id_einstandspartner>0` imply `not alleinerz` (if there are any children of course)? I think it does.
