### ISSUE TITLE
BUG: Add last year's income as an input variable for Elterngeld

### ISSUE THREAD

**Issue by MImmesberger** [iza-institute-of-labor-economics/gettsim#692]
### Bug description

As discussed in #690, GETTSIM uses this year's income as an approximation for last year's income when calculating Elterngeld. 

Instead, we should use last year's income as a basic input variable to correctly compute Elterngeld. At the same time, we should have the Elterngeld-relevant income as an output variable to facilitate computations in panel data.

**Comment by ChristianZimpelmann** [comment]
There is a similar problem for `grundrente` which requires income from two (or three?) years ago.

See [docstring of `_grundr_zuschlag_eink_vor_freibetrag_m`](https://github.com/iza-institute-of-labor-economics/gettsim/blob/6b6093d71b175fbba0c58f054ca562f009900407/src/_gettsim/transfers/grundrente.py#L27)

**Comment by hmgaudecker** [comment]
And ALG I, in case we want to expand the scope here.
