### ISSUE TITLE
BUG: Time conversion fails for user inputs

### ISSUE THREAD

**Issue by MImmesberger** [iza-institute-of-labor-economics/gettsim#699]
### Bug description

When playing around with the tests for Elterngeld in #694, I noticed that `eink_st_m_sn` is not recognised as a the time converted counterpart of `eink_st_y_sn`. The same happens for `soli_st_m_sn`. Changing the income tax input in any of the Elterngeld tests reproduces the error.

Is it intentional that we don't convert data inputs or is that a bug?

On `main` the Elterngeld test takes care of this via 
```python
df["soli_st_y_tu"] = df["soli_st_m"].groupby(df["tu_id"]).transform("sum") * 12
```

**Comment by hmgaudecker** [comment]
Sounds like a case we did not think about to me! Can you check, please, @lars-reimann ?

**Comment by lars-reimann** [comment]
That happens because there are policy functions with the correct names (`eink_st_y_sn` and `soli_st_y_sn`). Those currently have higher priority than data columns for different time periods. Should that be changed?

**Comment by hmgaudecker** [comment]
Yes, I think that's a reasonable change. We would create endless confusion if we kept the current state and claimed something like "time period does not matter".
