### ISSUE TITLE
BUG: Grouping of `eink_st_y_sn` on other levels

### ISSUE THREAD

**Issue by MImmesberger** [iza-institute-of-labor-economics/gettsim#701]
### Bug description

Can we make `eink_st_y_hh` available? Just encountered it when editing the tutorials.

**Comment by hmgaudecker** [comment]
Why would we want to have that? I am not sure whether it is helpful to define a general function for that.

You could write a function that disaggregates `eink_st_y_sn` to the individual level and then let the aggregation magic work.

**Comment by MImmesberger** [comment]
It would be super useful to have an easy replacement for `tu` in applications. But I just realised that `sn` is not a subset of `hh`, so it really doesn't make much sense.
