### ISSUE TITLE
DOC: Documentation on supported groupings

### ISSUE THREAD

**Issue by ChristianZimpelmann** [iza-institute-of-labor-economics/gettsim#723]
Is there any documentation on the groupings we are currently supporting? Would be great to have a short description of who is expected to be in that group (not sure about Familiengemeinschaft `fg` for example).

**Comment by MImmesberger** [comment]
The groups are documented in [GEP 01](https://gettsim.readthedocs.io/en/latest/geps/gep-01.html#column-names-a-k-a-variables-in-stata), but are not yet part of the proper tutorial.

**Comment by ChristianZimpelmann** [comment]
Thanks! Very helpful although `ehe` and `eg` are still missing there.

I also found the `SUPPORTED_GROUPINGS` dictionary now which provides some more context and is all I need for now. There, I am just not sure whether `fg` can consist of an adult (say 30 year old) and his/her parents. The description reads as if it is possible (`Maximum of two generations`), but the code base seems to imply that a `fg` consists of at most two adults.

**Comment by hmgaudecker** [comment]
fg is basically the potential bg, before removing children with too high
incomes. So I guess the answer is no.

Christian Zimpelmann ***@***.***> schrieb am Do., 25. Apr.
2024, 09:14:

**Comment by MImmesberger** [comment]
Closed via #737. The documentation can be accessed [here](https://gettsim.readthedocs.io/en/latest/gettsim_developer/hh_concepts.html).
