### ISSUE TITLE
BUG: input variable `vermögen_bedürft_bg` uses endogeneous grouping

### ISSUE THREAD

**Issue by ChristianZimpelmann** [iza-institute-of-labor-economics/gettsim#724]
### Bug description

- we request the input variable `vermögen_bedürft_bg` however this grouping is endogeneous. Also, it is used for `hh`-wide transfers like Wohngeld which seems incorrect if `bg` and `hh` differ. Probably should be `vermögen_bedürft_hh` (which we somehow need to distribute on Bedarfsgemeinschaften) or we request individual-level wealth?

See also #412

**Comment by hmgaudecker** [comment]
Great catch, thanks a lot! 

Despite my comment in #412, I think individual-level is the way to go now. It is ultimately what matters in many cases and anything else would be introducing lots of complexity on the GETTSIM side. 

At some point, we need a data preparation guide... There we could explain and make suggestions like trying different ways for distributing wealth measured at some group level.
