### ISSUE TITLE
Convert remaining Excel-files to YAML

### ISSUE THREAD

**Issue by hmgaudecker** [iza-institute-of-labor-economics/gettsim#73]
### Current and desired situation

We mostly removed the dependence on Excel, but `pensions.xlsx` is still around.

### Proposed implementation

Same as in #54 

- [ ] Convert `pensions.xlsx` to YAML format
- [ ] Adjust data loading whereever we call `pd.read_excel`
- [ ] Remove `xlrd` as a dependency in `environment.yml` and `meta.yaml`
- [ ] Remove lines 28 and 29 (starting with `# household` and  `# wg.to_excel`) in wohngeld.py

**Comment by Eric-Sommer** [comment]
There is a bit of overlap between the two files, namely in the pension contribution rate. You can remove this from the pensions file while you're at it and instead refer to the `tb` parameter (you need to double that one though).

**Comment by hmgaudecker** [comment]
Would it make sense to wait for #79? It just does not make sense to have pensions  separate... Would they not just become part of _ges_renten_vers_ (or whatever we end up calling it)?

**Comment by Eric-Sommer** [comment]
One could integrate them into `param.yaml`. I wouldn't do it now because
- the pension parameters contain not only legal parameters, but empirical values like sum of contributions, number of contributors etc.
- the pension stuff is far less mature than the other parameters. I collected all the values for the *Rentenformel* without quite knowing how they will be dealt with in the end. If one does dynamic simulation, lots of these values will be endogenously set from the model. Until we have a definitive plan on how to simulate future pensions, I feel it's easier to keep them apart.

**Comment by hmgaudecker** [comment]
> the pension parameters contain not only legal parameters, but empirical values like sum of contributions

This seems perfectly fine to have in params.yaml. It is a value that is relevant for calculations, which will not change anymore. I do not care much whether it is a law or from somewhere else.

> number of contributors etc.

This does not seem to be relevant, or is it for the Nachhaltigkeitsfaktor etc.?

> the pension stuff is far less mature than the other parameters. I collected all the values for the _Rentenformel_ without quite knowing how they will be dealt with in the end. If one does dynamic simulation, lots of these values will be endogenously set from the model. Until we have a definitive plan on how to simulate future pensions, I feel it's easier to keep them apart.

Well, they **are** separate under the new structure, right?

Let us keep them in and maybe add notes expressing your uncertainty about some parameters during review.

**Comment by Eric-Sommer** [comment]
> > number of contributors etc.
> 
> This does not seem to be relevant, or is it for the Nachhaltigkeitsfaktor etc.?

https://de.wikipedia.org/wiki/Rentenanpassungsformel => Rentnerquotient.
 
> Let us keep them in and maybe add notes expressing your uncertainty about some parameters during review.

OK, go ahead

**Comment by mjbloemer** [comment]
For the legal parameters we nee the note and I agree that these parameters should end up in a param.yaml.

Do we need a note key for the change of empirical values?

**Comment by hmgaudecker** [comment]
Agreed. We should have links to the sources for the empirical values, too. 

But let us please continue further discussion like this in #86.

**Comment by hmgaudecker** [comment]
Closed in #111
