### ISSUE TITLE
BUG: Unterhaltsvorschuss and Unterhalt needed on child level

### ISSUE THREAD

**Issue by ChristianZimpelmann** [iza-institute-of-labor-economics/gettsim#735]
### Bug description

- `unterhaltsvors_m` used to be calculated on the child level (for all parents the variable was zero) (it wasn't well documented that way I guess)
- It was changed to be calculated on the parent level (the variable is now zero for all children)
- This leads to errors in the calculation of transfers (Wohngeld and Kinderzuschlag) in which Unterhaltsvorschuss is deducted on the child-level as child income (which is handled differently to parent income)
- On a similar note, it is currently not clearly described whether the input variable `kind_unterh_erhalt_m` is expected to be specified on the child or parent level. The Unterhaltsvorschuss module seems to imply that we expect it on the parent level which again doesn't fit to how it is used for the calculation of transfers

Was there an important reason for the change? 

- If yes, we need to rewrite the transfer modules or rather create additional child-level variables which we can create there.
- Otherwise, I would argue in favor of reverting it back to child level.
- Either way, we most likely need to know which child received how much Unterhalt, the parent level is not enough.

Note:
- Slightly related to #357

**Comment by ChristianZimpelmann** [comment]
I just checked the tests:
- We have no test for Wohngeld in which the household also receives Unterhalt or Unterhaltsvorschuss -> need to add some
- We have a few test for Kinderzuschlag in which the household receives Unterhalt
  - As expected the Unterhalt is > 0 for the child, not the parent
  - No tests in which the household receives Unterhaltsvorschuss -> need to add some
- We have no test for Unterhaltsvorschuss in which the household receives Unterhalt -> need to add some

**Comment by MImmesberger** [comment]
Interesting, I didn't know that when implementing this in #694. 

Currently, we calculate the Unterhaltsvorschuss claim on the child level via `_unterhaltsvors_anspruch_pro_kind_m`, aggregate it to the parent level and then deduct the actual received unterhalt on the parent level. IIRC we have done that for the simple reason that Unterhaltsvorschuss and Unterhalt are paid out to the parent (hence, disposable income on the parent level; not in a legal but in a practical sense) and not to the child.

Importantly, we do not depict which person(s) pay(s) Unterhalt to the parent (the sum of Unterhalt payments is a basic input var), so we cannot trace down which parent paid which Unterhalt for which child. Hence, we cannot use the machinery introduced in #722 to handle this. 

For Wohngeld and the other transfers, is the maximum Unterhaltsvorschuss relevant? Or the actual Unterhalt received? Or the Unterhaltsvorschuss that is paid out (Unterhalt already deducted)?

**Comment by hmgaudecker** [comment]
> Currently, we calculate the Unterhaltsvorschuss claim on the child level via `_unterhaltsvors_anspruch_pro_kind_m`, aggregate it to the parent level and then deduct the actual received unterhalt on the parent level. IIRC we have done that for the simple reason that Unterhaltsvorschuss and Unterhalt are paid out to the parent (hence, disposable income on the parent level; not in a legal but in a practical sense) and not to the child.

So Christian can use `_unterhaltsvors_anspruch_pro_kind_m` and all is fine?

> Importantly, we do not depict which person(s) pay(s) Unterhalt to the parent (the sum of Unterhalt payments is a basic input var), so we cannot trace down which parent paid which Unterhalt for which child. Hence, we cannot use the machinery introduced in #722 to handle this.

Please change that so that `unterhalt_empf_m` (or so, I am guessing) is a basic input variable. The previous choice is a consequence of sticking closely to the SOEP. To be consistent with other cases, we should let the user impute.

> For Wohngeld and the other transfers, is the maximum Unterhaltsvorschuss relevant? Or the actual Unterhalt received? Or the Unterhaltsvorschuss that is paid out (Unterhalt already deducted)?

Actual and, if required, Unterhaltsvorschuss IMU.

**Comment by ChristianZimpelmann** [comment]
> So Christian can use _unterhaltsvors_anspruch_pro_kind_m and all is fine?

Not quite as this variable does not consider Unterhalt the child received. We will need a new variable which deducts `kind_unterh_erhalt_m` on the child level. Then we have Unterhaltsvorschuss on the child level.

We can then easily create a new variable on the parent level on the Unterhaltsvorschuss they receive for all their children.

A more general question is which of those variables should be called `unterhaltsvors_m` and how the other should be called. 

> Please change that so that unterhalt_empf_m (or so, I am guessing) is a basic input variable. 

You mean a variable on child level? Yes, I think we will need that.

> Actual and, if required, Unterhaltsvorschuss IMU.

Yes!
