### ISSUE TITLE
BUG: Kindergeldübertrag

### ISSUE THREAD

**Issue by MImmesberger** [iza-institute-of-labor-economics/gettsim#742]
### Bug description

The current version of GETTSIM doesn't support the Kindergeldübertrag.

The Kindergeldübertrag is relevant whenever children are not part of the Bedarfsgemeinschaft of their parents (e.g. due to enough income through Unterhalt). Then, the Kindergeld that is not necessary to cover the needs of the child are considered as parental income for Bürgergeld.

**Comment by MImmesberger** [comment]
To do this, we need to transfer the Kindergeld computed on the parental level back to the children (to compare Bedarf and Einkommen) and then transfer the Übertrag back to parents.

[This website] suggests that when transferring Kindergeld from parents to children, children do not receive the actual amount of Kindergeld they are responsible for on the parental level (then, the first born child would get a different amount than the second child), but they receive an average (total Kindergeld divided by number of children).

**Comment by hmgaudecker** [comment]
Only matters until 2022 anyhow, right? If anyone ever needs it at this level of detail in the past, they can implement it. For now, just use whatever is easiest to implement in the current policy environment and flag it for the past.

**Comment by MImmesberger** [comment]
Yes exactly. But the website implies we don't have to distinguish between the two regimes, two birds with one stone.

**Comment by hmgaudecker** [comment]
I did not follow the link, was just worried that dividing by "the number of children" might need some work in case this is not about children in the bg but about all children of a parent, which might be living with the former partner etc.

All the better if that is no problem!

**Comment by ChristianZimpelmann** [comment]
This seems to be an important step towards endogenizing `eigenbedarf_gedeckt`.
