### ISSUE TITLE
BUG: ALG 2 no Mehrbedarf für Alleinerziehende is paid if child is in separate Bedarfsgemeinschaft (in the same household)

### ISSUE THREAD

**Issue by ChristianZimpelmann** [iza-institute-of-labor-economics/gettsim#748]
### Bug description

[The law](https://www.gesetze-im-internet.de/sgb_2/__21.html) on Mehrbedarf for single parents does specify that the children have to live in the same household. There does not seem to be a restriction that they have to be in the same Bedarfsgemeinschaft.

However, if a child forms a separate BG (`eigenbedarf_gedeckt = True`), we currently do not pay Mehrbedarf for single parents to the parent.

### ToDo
- check whether my interpretation of the law is correct
- if this is confirmed, rewrite `_arbeitsl_geld_2_alleinerz_mehrbedarf_m_bg` such that (some) input variables refer to the `fg` level

**Comment by MImmesberger** [comment]
I agree with your interpretation. I changed the inputs from `bg` to `fg` in #753

**Comment by MImmesberger** [comment]
Closed via #753
