### ISSUE TITLE
ENH: Remove `eigenbedarf_gedeckt` in Kindergeldübertrag

### ISSUE THREAD

**Issue by MImmesberger** [iza-institute-of-labor-economics/gettsim#758]
Kindergeldübertrag uses `eigenbedarf_gedeckt` to make sure that the child is not in the same Bedarfsgemeinschaft as parents (because then, Kindergeld may be counted as income twice). Conditioning on this exogenous variable is not necessary, we can either

- Make sure that the child is not in the same BG as parents via an endogenous variable
- Calculate income in a way that the double Kindergeld bug doesn't occur (preferred)

**Comment by hmgaudecker** [comment]
Isn't this "just" a matter of:

- in `bg_id_numpy`, use a condition derived from something like `_diff_kindergeld_kindbedarf_m` (I guess, using `kindergeld_anspruch` and `_mean_kindergeld_per_child_m_fg`) instead of `eigenbedarf_gedeckt`
  
  *Btw, the implementation `kindergeld_anz_ansprüche` does not seem to make much sense at the individual level, right? Will always return the value for one child instead of the average in whatever grouping?*
- Then continue with `_mean_kindergeld_per_child_m_bg` when doing any stuff in SGB-II  realm

?

**Comment by MImmesberger** [comment]
>in `bg_id_numpy`, use a condition derived from something like `_diff_kindergeld_kindbedarf_m` (I guess, using `kindergeld_anspruch` and `_mean_kindergeld_per_child_m_fg`) instead of `eigenbedarf_gedeckt`

Sounds good! In `_diff_kindergeld_kindbedarf_m` we would need to use an individual version of `arbeitsl_geld_2_regelbedarf_m_bg`. Then we could throw out the exogenous `eigenbedarf_gedeckt` entirely, or am I missing something?

> Btw, the implementation kindergeld_anz_ansprüche does not seem to make much sense at the individual level, right? Will always return the value for one child instead of the average in whatever grouping?

Maybe I don't understand your comment correctly, but `kindergeld_anz_ansprüche` also returns values larger than 1. It is created via
```python
aggregate_by_p_id_kindergeld = {
    "kindergeld_anz_ansprüche": {
        "p_id_to_aggregate_by": "p_id_kindergeld_empf",
        "source_col": "kindergeld_anspruch",
        "aggr": "sum",
    },
}
```

> Then continue with `_mean_kindergeld_per_child_m_bg` when doing any stuff in SGB-II realm

I don't see why we would want to use the mean Kindergeld on the parental level? I think we're fine with using `kindergeld_zur_bedarfsdeckung_m`. If Kindergeldübertrag is 0, all is fine. If it is positive, we have to be careful when aggregating to the household level (to not count Kindergeldübertrag and `kindergeld_zur_bedarfsdeckung_m` twice. But I already added a comment regarding this to the relevant docstring in #753

**Comment by hmgaudecker** [comment]
> > in `bg_id_numpy`, use a condition derived from something like `_diff_kindergeld_kindbedarf_m` (I guess, using `kindergeld_anspruch` and `_mean_kindergeld_per_child_m_fg`) instead of `eigenbedarf_gedeckt`
> 
> Sounds good! In `_diff_kindergeld_kindbedarf_m` we would need to use an individual version of `arbeitsl_geld_2_regelbedarf_m_bg`. Then we could throw out the exogenous `eigenbedarf_gedeckt` entirely, or am I missing something?

Exactly. `eigenbedarf_gedeckt` is just a Boolean based on  `_diff_kindergeld_kindbedarf_m` < 0 *(I might have a sign error here)*

**Comment by hmgaudecker** [comment]
> > Btw, the implementation kindergeld_anz_ansprüche does not seem to make much sense at the individual level, right? Will always return the value for one child instead of the average in whatever grouping?
> 
> Maybe I don't understand your comment correctly, but `kindergeld_anz_ansprüche` also returns values larger than 1. It is created via
> 
> ```python
> aggregate_by_p_id_kindergeld = {
>     "kindergeld_anz_ansprüche": {
>         "p_id_to_aggregate_by": "p_id_kindergeld_empf",
>         "source_col": "kindergeld_anspruch",
>         "aggr": "sum",
>     },
> }
> ```

My bad. I meant `_mean_kindergeld_per_child_gestaffelt_m`, which uses it as an input.

**Comment by hmgaudecker** [comment]
> > Then continue with `_mean_kindergeld_per_child_m_bg` when doing any stuff in SGB-II realm
> 
> I don't see why we would want to use the mean Kindergeld on the parental level? I think we're fine with using `kindergeld_zur_bedarfsdeckung_m`. If Kindergeldübertrag is 0, all is fine. If it is positive, we have to be careful when aggregating to the household level (to not count Kindergeldübertrag and `kindergeld_zur_bedarfsdeckung_m` twice. But I already added a comment regarding this to the relevant docstring in #753

Apologies, got confused what is at the child and what is at the parent level. What I meant was "aggregate a child-level variable in its mean version to the Bedarfsgemeinschaft-level"

**Comment by ChristianZimpelmann** [comment]
During the policy project, I used this function to check whether my manual setting of `eigenbedarf_gedeckt ` was correct. Maybe helpful..

```
def _arbeitsl_geld_2_bedarf_über_einkommen_kind_m(
    arbeitsl_geld_2_regelbedarf_m_bg: float,
    _arbeitsl_geld_2_nettoeink_ohne_transfers_m: float,
    kindergeld_zur_bedarfsdeckung_m: float,
    kind_unterh_erhalt_m: float,
    unterhaltsvors_m: float,
) -> float:
    """ALG 2 needs of a child that exceeds their own income.

    If this value is negative, the child's income is sufficient to cover their needs
    and the child constitutes a Bedarfsgemeinschaft of their own.

    # TODO (@MImmesberger): Use this function to endogenize `eigenbedarf_gedeckt` and,
    hence, the creation of Bedarfsgemeinschaft.
    https://github.com/iza-institute-of-labor-economics/gettsim/issues/758

    Note: arbeitsl_geld_2_regelbedarf_m_bg has to be replaced by
    arbeitsl_geld_2_regelbedarf_m. Until then, the function is only correct if
    `eigenbedarf_gedeckt == True` for the child.
    
    Parameters
    ----------
    arbeitsl_geld_2_regelbedarf_m_bg
        See :func:`arbeitsl_geld_2_regelbedarf_m_bg`.
    _arbeitsl_geld_2_nettoeink_ohne_transfers_m
        See :func:`_arbeitsl_geld_2
    kindergeld_zur_bedarfsdeckung_m
        See :func:`kindergeld_zur_bedarfsdeckung_m`.
    kind_unterh_erhalt_m
        See :func:`kind_unterh_erhalt_m`.
    unterhaltsvors_m
        See :func:`unterhaltsvors_m`.

    Returns
    -------

    """
    out = (
        arbeitsl_geld_2_regelbedarf_m_bg
        - _arbeitsl_geld_2_nettoeink_ohne_transfers_m
        - kindergeld_zur_bedarfsdeckung_m
        - kind_unterh_erhalt_m
        - unterhaltsvors_m
    )

    return out

**Comment by hmgaudecker** [comment]
Just linking related issue, which also proposes calculating the `regelbedarf` at the individual level: #668
