### ISSUE TITLE
Move zve_list to `policy_for_date` and make it year-dependent

### ISSUE THREAD

**Issue by Eric-Sommer** [iza-institute-of-labor-economics/gettsim#76]
### Bug description

In #61, the definition of `zve_list` was not moved into `policy_for_date` and is still in `test_favorability_check`. It also must not be in `calculate_tax_transfers`. Moreover, it needs to be year-sensitive.

### Solution

    if year >= 2009:
        tb["zve_list"] = ["nokfb", "kfb", "abg_nokfb", "abg_kfb"]
    else:
        tb["zve_list"] = ["nokfb", "kfb"]

**Comment by hmgaudecker** [comment]
Seems like  `policy_for_date` is the right place for this?

**Comment by Eric-Sommer** [comment]
Absolutely

**Comment by MaxBlesch** [comment]
Will do it these days!
