### ISSUE TITLE
Azure CI build reports success on Linux despite failing tests

### ISSUE THREAD

**Issue by hmgaudecker** [iza-institute-of-labor-economics/gettsim#77]
### Bug description

https://dev.azure.com/iza-institute-of-labor-economics/gettsim/_build/results?buildId=263

has a failing test (test_alg2[2011]) on all platforms; the result is exactly the same everywhere. But the Linux build incorrectly reports success.

**Comment by hmgaudecker** [comment]
Any ideas, @tobiasraabe ?

**Comment by tobiasraabe** [comment]
I am a little bit confused. Maybe pytest's error code is suppressed by the success of pre-commit in the same block. I could test it in #50. Is it okay for you, @Eric-Sommer?

**Comment by hmgaudecker** [comment]
Why don't you just open a new PR and make some test fail temporarily for checking the pipeline? We will need one for merging the changes anyhow.
