### ISSUE TITLE
inconsistent treatment of `tb_pens`

### ISSUE THREAD

**Issue by Eric-Sommer** [iza-institute-of-labor-economics/gettsim#78]
### Bug description

`tax_transfer()` accepts no `tb_pens` is handed over. However, if you do this, the pension function breaks. So the non-existence of `tb_pens` is not checked for.

### Suggested Solution

As pensions will be crucial for long-term analyses and their calculation does not make much sense without these parameters, I suggest making `tb_pens` mandatory.

**Comment by hmgaudecker** [comment]
I would tend to mark close this as invalid. There is no reason other than path dependence that `tb_pens` is treated in any different way from `tb`.  So this will be gone eventually. 

The only thing we document for the moment is `calculate_tax_and_transfers` and this does the right thing, no?
