### ISSUE TITLE
Develop strategy for endogenizing program takeup

### ISSUE THREAD

**Issue by MaxBlesch** [iza-institute-of-labor-economics/gettsim#8]
in the future, there will be a state variable (0/1) on whether or not a household applies for benefits. This should be treated accordingly in the benefit functions. Alternatively, you would (not) call the benefit functions at all and assign a zero value instead.

**Comment by hmgaudecker** [comment]
We should make that more precise -- could well be that households apply for some programs, but not for others. That will require careful design once we are settling in on the overall function interfaces.

**Comment by Eric-Sommer** [comment]
closed...moved to zulip.

**Comment by hmgaudecker** [comment]
Link for reference https://gettsim.zulipchat.com/#narrow/stream/215726-Take-Up-and.20Discretion/topic/Benefit.20takeup.20decision/near/182159437
