### ISSUE TITLE
Doublecheck tests

### ISSUE THREAD

**Issue by MaxBlesch** [iza-institute-of-labor-economics/gettsim#80]
### Bug description

In an earlier PR I came across some strange values in the test data. Therefore I included TODOs in 

- test_zve.py, 
https://github.com/iza-institute-of-labor-economics/gettsim/blob/0323de5170658415d2dba08694d0645c716ba213/gettsim/tests/test_zve.py#L82

- test_arbeitslosengeld_ui.py
https://github.com/iza-institute-of-labor-economics/gettsim/blob/0323de5170658415d2dba08694d0645c716ba213/gettsim/tests/test_arbeitslosengeld_ui.py#L52

- test_tax_sched.py
https://github.com/iza-institute-of-labor-economics/gettsim/blob/0323de5170658415d2dba08694d0645c716ba213/gettsim/tests/test_tax_sched.py#L51

We need to doublecheck the test data if this is just due to rounding errors, due to false formulas calculating the data or errors in the functions.

**Comment by hmgaudecker** [comment]
> test_zve.py, test_arbeitslosengeld_ui.py and test_tax_sched.py .

Would you have links to a branch, ... ?

**Comment by MaxBlesch** [comment]
This is for test_zve.py. 
https://github.com/iza-institute-of-labor-economics/gettsim/blob/0323de5170658415d2dba08694d0645c716ba213/gettsim/tests/test_zve.py#L82
