### ISSUE TITLE
API for tax units and household types

### ISSUE THREAD

**Issue by Eric-Sommer** [iza-institute-of-labor-economics/gettsim#83]
### Current and desired situation

The input data contain a number of demographic information derived from individual information. Examples include:

1. The definition of tax_units and their size.
2. The number of children in a given age (see #30) and the definition of a child itself.
3. The household type (Single, Single Parent, Couple without kids, Couple with kids, [other]). This also affects dummy variables, such as `married` and `zveranl`.

As these are currently dealt with in the data preparation, they are a black box to GETTSIM users. Moreover, it leads to more required input variables and thus more burden on the user.

### Proposed implementation

Create functions for each of the items above which return the variables `hhsize`, `hhsize_tu`, `child_num`, `hhtype` etc. based on the following variables only:

| Variable       | Explanation      |
|-----------|-------------------|
| `pid`       | Personal ID       |
| `female`    |                   |
| `age`       |                   |
| `ineducation` |         |
| `mother_id` | `pid` of mother |
| `father_id`  |  `pid` to Father                  |
| `child_id`    | `pid` to own child                  |
| `partner_id` |  `pid` to partner                   |

### Considered alternatives

leave as is, which is not feasible in the long run.

**Comment by hmgaudecker** [comment]
In the long run, handling the data structures sensibly and efficiently will be a much bigger question. So, IIUC, `mother_id` and the subsequent variables are not part of the data for the moment, right? I think they probably should be, but that would be part of the "right" overhaul.

For now, would some simple Pandas constructs not do?
```
hhsize = household['age'].count()
nadults = household.query('age > 27 | age >=18 & ineducation == False)
...
```
(not that we should hard-code these ages in the long run :-))

**Comment by Eric-Sommer** [comment]
Adding these ids is part of this task.

**Comment by hmgaudecker** [comment]
As I said, this will be rather the level of a GEP than a task and require very careful design.

**Comment by hmgaudecker** [comment]
Let's leave this to GEP 2.
