### ISSUE TITLE
Rounding is missing for several taxes / transfers

### ISSUE THREAD

**Issue by MaxBlesch** [iza-institute-of-labor-economics/gettsim#88]
### Bug description

Right now there are rounding functions in the code. We want to be as exact as possible and don't loose any information.

For example:
https://github.com/iza-institute-of-labor-economics/gettsim/blob/1b59c617b6b0c6f4acf845128988b60e207bc028/gettsim/taxes/calc_taxes.py#L138

### TODO:
- [ ] Remove all rounding functions.

**Comment by hmgaudecker** [comment]
Well this is not "as exact as possible" in terms of GETTSIM's core mission of representing the German laws. They often state that things be rounded to the next Euro.

But the ensuing pain of getting correct numerical derivatives in choice models is more than worth deviating there IMHO.

**Comment by Eric-Sommer** [comment]
The most flexible solution would be to insert a global Option whether to round or not. There is a use case for both and we do it in izamod as well.

Also note that `.as type(int)` is also a rounding operation

**Comment by hmgaudecker** [comment]
> The most flexible solution would be to insert a global Option whether to round or not. There is a use case for both and we do it in izamod as well.

Yeah, eventually we may want to think about it again but I do not want to support the added complexity during the transition phase. @MaxBlesch, maybe you can add a standard comment in all places where you remove it, so it would be simpler to get back to the current state?

> Also note that `.astype(int)` is also a rounding operation

Yes. Ouch.

In general, I simply cannot imagine coming to substantively different conclusions economically depending on whether you round or not. Or does anyone have an example?

**Comment by Eric-Sommer** [comment]
I don't have an economically meaningful example either. But I believe our model should also be able to deliver the correct Wohngeld payment for a given household. And in real life, wohngeld happens to be paid in steps of 5€. Let me just list the other real-life rounding incidents that come to my mind for later reference:

1. Wohngeld in steps of 5€.
2. Kinderzuschlag in steps of 5€.
3. Vorsorgeaufwendungen are rounded up.
4. Income tax is rounded down.

I agree with the transitional argument. We could also add a tag "rounding taken out".

**Comment by Eric-Sommer** [comment]
I like the idea. One would need one additional general function for rounding down and rounding up to the next €.

**Comment by Eric-Sommer** [comment]
Related: The output currently includes six digits. Which is fine for behavioral modelling, but we might need an option to round to cents.
![grafik](https://user-images.githubusercontent.com/44068467/86965236-811a5400-c167-11ea-83b1-001f2374df04.png)

**Comment by hmgaudecker** [comment]
That one is quick to do on the user side:
```py
df = df.round(2)
```
I do not think we should do anything on our side before we get around to the real fix.

**Comment by ChristianZimpelmann** [comment]
I agree that we should have both options at some point.

But I am very much in favor of having the default at the moment that we round wherever it is explicitely written in the law. In some occations it can really make a difference (e.g. for Grundrente Bonus Entgeltpunkte which are multiplied by number of months in Grundrentenbewertungszeiten (and Rentenwert), see #275). Otherwise, also the tests needed to be adjusted.

I think it would be helpful to first focus on representing the law and having exact tests.

**Comment by hmgaudecker** [comment]
Well, we would likely have to adjust many more tests elsewhere.

The main original motivation for GETTSIM was to allow using it in models that require numerical optimisation to solve. Creating discontinuities that do not have economic importance (like all those roundings to the nearest Euro in the tax system) would run directly counter to that. 

I am not sure about the economic magnitude of the rounding in #275. In any case, why not use it as a testbed to support optional rounding? Add a parameter to `set_up_policy_environment` (`round_pension_parameters` or so) and see whether it works?

**Comment by ChristianZimpelmann** [comment]
> In any case, why not use it as a testbed to support optional rounding?

Sounds like a good solution 👍

**Comment by ChristianZimpelmann** [comment]
After merging #316, the next step would be to reintroduce rounding where applicable (based on the list by @Eric-Sommer above.

**Comment by hmgaudecker** [comment]
Longer list of thIngs to do [here](https://gettsim.zulipchat.com/#narrow/stream/309998-GEPs/topic/GEP.2005/near/269556151), courtesy of  @mjbloemer.

Ticking those items off sounds like a good RA job, @ChristianZimpelmann can you add a suitable assignee?

**Comment by ChristianZimpelmann** [comment]
Yes, that's definitely one of the next tasks! Will do.

**Comment by hmgaudecker** [comment]
Closed in #343

**Comment by ChristianZimpelmann** [comment]
We are still missing some occasions where rounding is applied in practice. 

I adjusted the title. This list by @Eric-Sommer would be a good starting point:

1. Wohngeld in steps of 5€.
2. income is deducted from Kinderzuschlag in steps of 10€ (until 07/2019)
3. Vorsorgeaufwendungen are rounded up.
4. Income tax is rounded down.
5. Unterhaltsvorschuss is rounded up.

**Comment by hmgaudecker** [comment]
> In addition: Wohngeld is only payed out if at least 10€

Yes, though we'll need to think hard about whether that can be included in the machinery or not. I distantly remember that we thought it would not be so easy, but let's see.

@MImmesberger, should be a good issue to work on for seeing different stuff across the entire codebase. No rush in implementing (=scale of months rather than days).

**Comment by MImmesberger** [comment]
> Wohngeld is only payed out if at least 10€

And Unterhaltsschuss if at least 5€. Do we have an issue for that? If not, I can create one.

**Comment by MImmesberger** [comment]
> And in real life, wohngeld happens to be paid in steps of 5€.

@Eric-Sommer
Regarding the calculation of the Wohngeld, I haven't found a source for this. The calculated Wohngeld is rounded to the nearest Euro, the Wohngeldgesetz didn't change in this regard in (at least) the last 15ish years. But "in real life" suggests that this is something that is not codified by law?
Or did your comment refer to the rounding rules regarding the [calculation of certain parts of the Wohngeld formula](https://www.buzer.de/gesetz/8380/al52320-0.htm) until 2016?
