### ISSUE TITLE
Correct treatment of 'non-standard' households

### ISSUE THREAD

**Issue by Eric-Sommer** [iza-institute-of-labor-economics/gettsim#89]
### Bug description

As soon as a household does not fit into the four classical categories (Single, Single Parent, Couple, Couple with kids), things get complicated when it comes to the benefit system in particular. We haven't properly sorted this issue out yet. Examples include:

- [ ] how to treat the additional need for single parents in case there are more adults? In other words, how should a single parent be defined?
- [ ] Wohngeld and ALG2 apply different household concepts. You may have the core family eligible for ALG2, while there are other persons under the same roof eligible for Wohngeld (see [discussion](https://www.bbsr.bund.de/BBSR/DE/Veroeffentlichungen/Sonderveroeffentlichungen/2015/DL_Wohngeld.pdf?__blob=publicationFile&v=3), in particular section 5.4). This affects both the calculation of claims and a proper evaluation of different claims within in a household.
- [ ] The treatment of pensioners' eligibility for benefits is related to that. They are eligible to wohngeld, but not to ALG2, although "Grundsicherung im Alter" basically pays the same amount. Pensioners are also hardly covered in the tests as of now.

This issue can be solved by looking in particular at exemplary cases from the literature and applying them as test cases.

**Comment by hmgaudecker** [comment]
Thanks. 
1. will be an interesting case to keep in mind when designing our data structures. I think that should be doable with the right structure on linkages between persons.
2. is tough. Is one a subset of the other at least? Else I do not see how we could ever get away without defining two different household ids. Not sure whether that is actually worth the pain. 
3. Same as 2. -- can you please edit towards "eligibility **for xxx**? 

Would be great if you could link some of the test cases you think are important.

**Comment by hmgaudecker** [comment]
(I do not consider this a bug given that the state-of-the-art simulators do not seem to handle this correctly, either)

**Comment by Eric-Sommer** [comment]
Yes, they are nested but apparently the other way round than I thought. In a nutshell, for ALG2, a household is the core family: mom, dad and dependent kids. The adult, working child under the same roof however counts to the same wohngeld household. As my link suggests, this is a growing phenomenon.

**Comment by hmgaudecker** [comment]
(cold sweat disappearing... non-nestedness would have been **really** painful)

**Comment by MImmesberger** [comment]
Partially closed by #694. All things that are not yet done are covered by more specific issues (thinking of #270 and #710).
