### ISSUE TITLE
Kinderzuschlag used to be paid only 36 months

### ISSUE THREAD

**Issue by Eric-Sommer** [iza-institute-of-labor-economics/gettsim#90]
### Bug description

We assign Kinderzuschlag if the household is eligible. [From 2005 to 2008](https://www.buzer.de/gesetz/1166/al10977-0.htm), it was however only paid up to 36 months.

### Possible Solution

Do not pay Kinderzuschlag at all from 2005 to 2008. This is parallel to the treatment of "Unterhaltsvorschuss" prior to 2017. This would require a small change in `policies_for_date`.

**Comment by hmgaudecker** [comment]
So is this an issue unless somebody wanted to simulate what would have happened if the 2005-2008 system had been in place in the long run? dd.mm.2005-31.12.2007 <= 36 months, so the restriction did not bind for anyone?  Or am I missing something?

**Comment by Eric-Sommer** [comment]
You are right. Since it was in place only 36 months, no-one can have been paid it for a longer time. Shame on me. Can be closed.
